import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-dragoon',
  templateUrl: './dragoon.component.html',
  styleUrls: ['./dragoon.component.css']
})
export class DragoonComponent implements OnInit {

  constructor() { }

  today: Date = new Date();

  skills: any[] = [
    {
      isDisabled: "false",
      name: "精准刺",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Dragoon/Action_01.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/k_Q1zZVmdBmR240Xj6jDJGMiMA.png",
      tname: "枪术师",
      ticon: "",
      lvl: "Lv1",
      classification: "战技",
      cast: "即时",
      recast: "2.5秒",
      cost: "-",
      distant: "3",
      range: "0",
      rangeType: "zero",
      content: "对目标发动物理攻击　威力：290",
      change: "威力从160变更为290。"
    },
    {
      isDisabled: "false",
      name: "贯通刺",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Dragoon/Action_02.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/k_Q1zZVmdBmR240Xj6jDJGMiMA.png",
      tname: "枪术师",
      ticon: "",
      lvl: "Lv4",
      classification: "战技",
      cast: "即时",
      recast: "2.5秒",
      cost: "-",
      distant: "3",
      range: "0",
      rangeType: "zero",
      content: "对目标发动物理攻击　威力：140<BR>连击条件：精准刺　连击中威力：350",
      change: "威力从100变更为140。<br>连击中威力从250变更为350。"
    },
    {
      isDisabled: "false",
      name: "龙剑",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Dragoon/Action_03.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/k_Q1zZVmdBmR240Xj6jDJGMiMA.png",
      tname: "枪术师",
      ticon: "",
      lvl: "Lv6",
      classification: "能力",
      cast: "即时",
      recast: "45秒",
      cost: "-",
      distant: "0",
      range: "0",
      rangeType: "zero",
      content: "效果时间内，自身发动的1次战技必定打出暴击，并且恢复自身体力<BR>该效果不适用于持续伤害等状态<BR>持续时间：5秒",
      change: "习得等级从18变更为6。<br>“恢复与伤害量相当的体力”变更为“恢复自身体力”。<br>删除“恢复量最多不会超过最大体力的10%。<br>发动范围攻击时仅对最初命中的目标生效”。<br>新增“该效果不适用于持续伤害等状态”。<br>效果时间从10秒变更为5秒。<br>复唱时间从50秒变更为45秒。"
    },
    {
      isDisabled: "false",
      name: "贯穿尖",
      ndes: "通过特职任务获得",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Dragoon/Action_04.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/k_Q1zZVmdBmR240Xj6jDJGMiMA.png",
      tname: "枪术师",
      ticon: "",
      lvl: "Lv15",
      classification: "战技",
      cast: "即时",
      recast: "2.5秒",
      cost: "-",
      distant: "15",
      range: "0",
      rangeType: "zero",
      content: "对目标发动远程物理攻击　威力：150",
      change: "威力从120变更为150。"
    },
    {
      isDisabled: "false",
      name: "开膛枪",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Dragoon/Action_05.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/k_Q1zZVmdBmR240Xj6jDJGMiMA.png",
      tname: "枪术师",
      ticon: "",
      lvl: "Lv18",
      classification: "战技",
      cast: "即时",
      recast: "2.5秒",
      cost: "-",
      distant: "3",
      range: "0",
      rangeType: "zero",
      content: "对目标发动物理攻击　威力：150<BR>连击条件：精准刺　连击中威力：320<BR>连击成功：攻击伤害提高10%<BR>持续时间：30秒",
      change: "习得等级从38变更为18。<br>连击条件从“脉冲枪”变更为“精准刺”。<br>威力从100变更为150。<br>连击中威力从240变更为320。<br>连击成功“令目标的突刺耐性降低5%”变更为“攻击伤害提高10%”。"
    },
    {
      isDisabled: "false",
      name: "直刺",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Dragoon/Action_06.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/k_Q1zZVmdBmR240Xj6jDJGMiMA.png",
      tname: "枪术师",
      ticon: "",
      lvl: "Lv26",
      classification: "战技",
      cast: "即时",
      recast: "2.5秒",
      cost: "-",
      distant: "3",
      range: "0",
      rangeType: "zero",
      content: "对目标发动物理攻击　威力：100<BR>连击条件：贯通刺　连击中威力：530<BR>“苍天龙血”状态中连击成功：龙牙龙爪效果提高　持续时间：10秒",
      change: "连击中威力从450变更为530。"
    },
    {
      isDisabled: "false",
      name: "猛枪",
      ndes: "通过特职任务获得",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Dragoon/Action_07.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/k_Q1zZVmdBmR240Xj6jDJGMiMA.png",
      tname: "枪术师",
      ticon: "",
      lvl: "Lv30",
      classification: "能力",
      cast: "即时",
      recast: "90秒",
      cost: "-",
      distant: "0",
      range: "0",
      rangeType: "zero",
      content: "一定时间内，自身发动攻击造成的伤害提高15%<BR>持续时间：20秒",
      change: "技能名称变更。<br>复唱时间从80秒变更为90秒。<br>效果更新。"
    },
    {
      isDisabled: "false",
      name: "跳跃",
      ndes: "通过特职任务获得",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Dragoon/Action_08.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/zWRkXGJIJhN7WHGGv1gVscRxmA.png",
      tname: "龙骑士",
      ticon: "",
      lvl: "Lv30",
      classification: "能力",
      cast: "即时",
      recast: "30秒",
      cost: "-",
      distant: "20",
      range: "0",
      rangeType: "zero",
      content: "跳起接近目标并发动物理攻击　威力：310<BR>攻击之后回到原位<BR>追加效果：幻象冲预备<BR>持续时间：15秒<BR>止步状态下无法发动",
      change: "威力从260变更为310。"
    },
    {
      isDisabled: "false",
      name: "回避跳跃",
      ndes: "通过特职任务获得",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Dragoon/Action_09.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/zWRkXGJIJhN7WHGGv1gVscRxmA.png",
      tname: "龙骑士",
      ticon: "",
      lvl: "Lv35",
      classification: "能力",
      cast: "即时",
      recast: "30秒",
      cost: "-",
      distant: "0",
      range: "0",
      rangeType: "zero",
      content: "向身后跳出15米距离<BR>止步状态下无法发动",
      change: "从“追加效果：自身仇恨减半。<br>加重和止步状态下会同时解除该状态”变更为“止步状态下无法发动”。"
    },
    {
      isDisabled: "false",
      name: "死天枪",
      ndes: "通过特职任务获得",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Dragoon/Action_10.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/zWRkXGJIJhN7WHGGv1gVscRxmA.png",
      tname: "龙骑士",
      ticon: "",
      lvl: "Lv40",
      classification: "战技",
      cast: "即时",
      recast: "2.5秒",
      cost: "-",
      distant: "10",
      range: "10",
      rangeType: "zero",
      content: "向目标所在方向发出直线范围物理攻击　威力：170",
      change: "威力从140变更为170。"
    },
    {
      isDisabled: "false",
      name: "破碎冲",
      ndes: "通过特职任务获得",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Dragoon/Action_11.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/zWRkXGJIJhN7WHGGv1gVscRxmA.png",
      tname: "龙骑士",
      ticon: "",
      lvl: "Lv45",
      classification: "能力",
      cast: "即时",
      recast: "60秒",
      cost: "-",
      distant: "20",
      range: "0",
      rangeType: "zero",
      content: "跳起接近目标并发动物理攻击　威力：240<BR>止步状态下无法发动",
      change: "威力从210变更为240。<br>删除“追加效果：眩晕　效果时间：2秒<br>追加效果：幻象冲预备<br>效果时间：15秒”。"
    },
    {
      isDisabled: "false",
      name: "樱花怒放",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Dragoon/Action_12.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/k_Q1zZVmdBmR240Xj6jDJGMiMA.png",
      tname: "枪术师",
      ticon: "",
      lvl: "Lv50",
      classification: "战技",
      cast: "即时",
      recast: "2.5秒",
      cost: "-",
      distant: "3",
      range: "0",
      rangeType: "zero",
      content: "对目标发动物理攻击　威力：100<BR>背面攻击威力：140<BR>连击条件：开膛枪　连击中威力：290<BR>连击中背面攻击威力：330<BR>连击成功：持续伤害<BR>威力：50　持续时间：24秒<BR>“苍天龙血”中连击成功：龙尾大回旋效果提高　持续时间：10秒",
      change: "持续伤害效果的威力从45变更为50。"
    },
    {
      isDisabled: "false",
      name: "龙炎冲",
      ndes: "通过特职任务获得",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Dragoon/Action_13.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/zWRkXGJIJhN7WHGGv1gVscRxmA.png",
      tname: "龙骑士",
      ticon: "",
      lvl: "Lv50",
      classification: "能力",
      cast: "即时",
      recast: "120秒",
      cost: "-",
      distant: "20",
      range: "5",
      rangeType: "zero",
      content: "跳起接近目标并发动火属性范围攻击　威力：380<BR>止步状态下无法发动",
      change: "威力从320变更为380。"
    },
    {
      isDisabled: "false",
      name: "战斗连祷",
      ndes: "通过特职任务获得",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Dragoon/Action_14.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/zWRkXGJIJhN7WHGGv1gVscRxmA.png",
      tname: "龙骑士",
      ticon: "",
      lvl: "Lv52",
      classification: "能力",
      cast: "即时",
      recast: "180秒",
      cost: "-",
      distant: "0",
      range: "15",
      rangeType: "zero",
      content: "一定时间内，自身与周围队员的暴击发动率提高10%<BR>持续时间：20秒",
      change: "暴击发动率从15%变更为10%。"
    },
    {
      isDisabled: "false",
      name: "苍天龙血",
      ndes: "通过特职任务获得",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Dragoon/Action_15.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/zWRkXGJIJhN7WHGGv1gVscRxmA.png",
      tname: "龙骑士",
      ticon: "",
      lvl: "Lv54",
      classification: "能力",
      cast: "即时",
      recast: "25秒",
      cost: "-",
      distant: "0",
      range: "0",
      rangeType: "zero",
      content: "一定时间内，高跳和破碎冲的威力提高30%　持续时间：30秒<BR>直刺成功时追加效果：龙牙龙爪效果提高　持续时间：10秒<BR>樱花怒放成功时追加效果：龙尾大回旋效果提高　持续时间：10秒<BR>以上两种状态在苍天龙血状态消失或执行了其他战技时自动解除<BR>发动条件：非红莲龙血状态中",
      change: "复唱时间由30秒变为25秒。"
    },
    {
      isDisabled: "false",
      name: "龙牙龙爪",
      ndes: "通过特职任务获得",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Dragoon/Action_16.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/zWRkXGJIJhN7WHGGv1gVscRxmA.png",
      tname: "龙骑士",
      ticon: "",
      lvl: "Lv56",
      classification: "战技",
      cast: "即时",
      recast: "2.5秒",
      cost: "-",
      distant: "3",
      range: "0",
      rangeType: "zero",
      content: "对目标发动物理攻击　威力：340<BR>侧面攻击威力：380<BR>追加效果：苍天龙血的持续时间延长10秒<BR>最多可延长至30秒<BR>发动条件：苍天龙血及龙牙龙爪效果提高状态中",
      change: "威力从330变更为340。<BR>侧面攻击威力从370变更为380。"
    },
    {
      isDisabled: "false",
      name: "龙尾大回旋",
      ndes: "通过特职任务获得",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Dragoon/Action_17.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/zWRkXGJIJhN7WHGGv1gVscRxmA.png",
      tname: "龙骑士",
      ticon: "",
      lvl: "Lv58",
      classification: "战技",
      cast: "即时",
      recast: "2.5秒",
      cost: "-",
      distant: "3",
      range: "0",
      rangeType: "zero",
      content: "对目标发动物理攻击　威力：340<BR>背面攻击威力：380<BR>追加效果：苍天龙血的持续时间延长10秒<BR>最多可延长至30秒<BR>发动条件：苍天龙血及龙尾大回旋效果提高状态中",
      change: "威力从330变更为340。<BR>背面攻击威力从370变更为380。"
    },
    {
      isDisabled: "false",
      name: "武神枪",
      ndes: "通过特职任务获得",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Dragoon/Action_18.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/zWRkXGJIJhN7WHGGv1gVscRxmA.png",
      tname: "龙骑士",
      ticon: "",
      lvl: "Lv60",
      classification: "能力",
      cast: "即时",
      recast: "30秒",
      cost: "「龙眼」2档",
      distant: "15",
      range: "15",
      rangeType: "zero",
      content: "向目标所在方向发出直线范围物理攻击　威力：300<BR>发动条件：苍天龙血状态中<BR>追加效果：苍天龙血变为红莲龙血<BR>发动条件：龙眼2档",
      change: "威力由270变为300。"
    },
    {
      isDisabled: "false",
      name: "音速刺",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Dragoon/Action_19.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/zWRkXGJIJhN7WHGGv1gVscRxmA.png",
      tname: "龙骑士",
      ticon: "",
      lvl: "Lv62",
      classification: "战技",
      cast: "即时",
      recast: "2.5秒",
      cost: "-",
      distant: "10",
      range: "10",
      rangeType: "zero",
      content: "向目标所在方向发出直线范围物理攻击　威力：100<BR>连击条件：死天枪　连击中威力：200<BR>连击成功：苍天龙血的持续时间延长10秒<BR>最多可延长至30秒",
      change: "连击中威力从180变更为200。"
    },
    {
      isDisabled: "false",
      name: "巨龙视线",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Dragoon/Action_20.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/zWRkXGJIJhN7WHGGv1gVscRxmA.png",
      tname: "龙骑士",
      ticon: "",
      lvl: "Lv66",
      classification: "能力",
      cast: "即时",
      recast: "120秒",
      cost: "-",
      distant: "12",
      range: "0",
      rangeType: "zero",
      content: "为自身附加巨龙右眼状态<BR>当指定一名队员为目标时，为自身附加巨龙右眼状态，为目标附加巨龙左眼状态<BR>巨龙右眼效果：攻击伤害提高10%<BR>巨龙左眼效果：攻击伤害提高5%<BR>持续时间：20秒<BR>与目标的距离超过12米无法发动巨龙左眼的效果",
      change: "变更为不需要指定一名队员为目标也可使用。"
    },
    {
      isDisabled: "false",
      name: "幻象冲",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Dragoon/Action_21.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/zWRkXGJIJhN7WHGGv1gVscRxmA.png",
      tname: "龙骑士",
      ticon: "",
      lvl: "Lv68",
      classification: "能力",
      cast: "即时",
      recast: "1秒",
      cost: "-",
      distant: "20",
      range: "0",
      rangeType: "zero",
      content: "对目标发动物理攻击　威力：300<BR>“苍天龙血”或“红莲龙血”状态中追加效果：龙眼<BR>发动条件：发动跳跃、高跳后对自身附加的幻象冲预备状态中",
      change: "威力由250变为300"
    },
    {
      isDisabled: "false",
      name: "死者之岸",
      ndes: "通过特职任务获得",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Dragoon/Action_22.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/zWRkXGJIJhN7WHGGv1gVscRxmA.png",
      tname: "龙骑士",
      ticon: "",
      lvl: "Lv70",
      classification: "能力",
      cast: "即时",
      recast: "10秒",
      cost: "-",
      distant: "15",
      range: "15",
      rangeType: "zero",
      content: "向目标所在方向发出直线范围物理攻击　威力：400<BR>发动条件：红莲龙血状态中<BR><BR>※该技能无法设置到热键栏",
      change: "威力从330变更为400。"
    },
    {
      isDisabled: "false",
      name: "山境酷刑",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Dragoon/Action_23.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/zWRkXGJIJhN7WHGGv1gVscRxmA.png",
      tname: "龙骑士",
      ticon: "",
      lvl: "Lv72",
      classification: "战技",
      cast: "即时",
      recast: "2.5秒",
      cost: "-",
      distant: "10",
      range: "10",
      rangeType: "zero",
      content: "向目标所在方向发出直线范围物理攻击　威力：100<BR>连击条件：音速刺　连击中威力：230<BR>连击成功：苍天龙血的持续时间延长10秒<BR>最多可延长至30秒<BR>",
      change: "技能名称由“山境痛苦”变更为“山境酷刑”"
    },
    {
      isDisabled: "false",
      name: "高跳",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Dragoon/Action_24.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/zWRkXGJIJhN7WHGGv1gVscRxmA.png",
      tname: "龙骑士",
      ticon: "",
      lvl: "Lv74",
      classification: "能力",
      cast: "即时",
      recast: "30秒",
      cost: "-",
      distant: "20",
      range: "0",
      rangeType: "zero",
      content: "跳起接近目标并发动物理攻击　威力：400<BR>攻击之后回到原位<BR>追加效果：幻象冲预备<BR>持续时间：15秒<BR>止步状态下无法发动",
      change: ""
    },
    {
      isDisabled: "false",
      name: "龙眼雷电",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Dragoon/Action_25.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/zWRkXGJIJhN7WHGGv1gVscRxmA.png",
      tname: "龙骑士",
      ticon: "",
      lvl: "Lv76",
      classification: "战技",
      cast: "即时",
      recast: "2.5秒",
      cost: "-",
      distant: "3",
      range: "0",
      rangeType: "zero",
      content: "对目标发动物理攻击　威力：330<BR>发动条件：龙眼雷电预备状态中<BR><BR>※该技能无法设置到热键栏",
      change: ""
    },
    {
      isDisabled: "false",
      name: "坠星冲",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Dragoon/Action_26.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/zWRkXGJIJhN7WHGGv1gVscRxmA.png",
      tname: "龙骑士",
      ticon: "",
      lvl: "Lv80",
      classification: "能力",
      cast: "即时",
      recast: "30秒",
      cost: "-",
      distant: "20",
      range: "5",
      rangeType: "zero",
      content: "跳起接近目标并发动火属性范围物理攻击　威力：600<BR>攻击复数敌人时，对目标之外的敌人威力降低30%<BR>止步状态下无法发动<BR>发动条件：红莲龙血状态中",
      change: "威力由550变为600。"
    }
  ];


  roleSkills: any[] = [
    {
      name: "内丹",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/2pih1KRjQsYAb_j4w7GkRFyglk.png",
      tiurl: "",
      tname: "",
      ticon: [
        { "url": 'https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/9muqitiUXEK0W3qnM33Nb7sATk.png', tname: '近战职业' },
        { "url": 'https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/oWWxUIO2KagIEhDXy0541MRD7M.png', tname: '远程物理职业' }
      ],
      lvl: "",
      classification: "能力",
      cast: "即时",
      recast: "120秒",
      cost: "-",
      distant: "0",
      range: "0",
      rangeType: "zero",
      content: "恢复自身体力<br>恢复力：500",
      change: ""
    },
    {
      name: "扫腿",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/h-Vwg7qPNp0rAE9sbya2c9SGC4.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/9muqitiUXEK0W3qnM33Nb7sATk.png",
      tname: "近战职业",
      ticon: [{ "url": 'https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/9muqitiUXEK0W3qnM33Nb7sATk.png', tname: '近战职业' }],
      lvl: "Lv10",
      classification: "能力",
      cast: "即时",
      recast: "40秒",
      cost: "-",
      distant: "3",
      range: "0",
      rangeType: "zero",
      content: "令目标陷入眩晕状态　持续时间：3秒",
      change: "习得等级从16变更为10。"
    },
    {
      name: "浴血",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/-V15O-XUiGmZcZZepHWlHSHngQ.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/9muqitiUXEK0W3qnM33Nb7sATk.png",
      tname: "近战职业",
      ticon: [{ "url": 'https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/9muqitiUXEK0W3qnM33Nb7sATk.png', tname: '近战职业' }],
      lvl: "Lv12",
      classification: "能力",
      cast: "即时",
      recast: "90秒",
      cost: "-",
      distant: "0",
      range: "0",
      rangeType: "zero",
      content: "一定时间内，将自身物理攻击所造成伤害的一部分转化为自身的体力<BR>持续时间：20秒",
      change: "习得等级从32变更为12。"
    },
    {
      name: "牵制",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/QZtAkrjZrFAcpoQbZ4PawsdbH4.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/9muqitiUXEK0W3qnM33Nb7sATk.png",
      tname: "近战职业",
      ticon: [{ "url": 'https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/9muqitiUXEK0W3qnM33Nb7sATk.png', tname: '近战职业' }],
      lvl: "Lv22",
      classification: "能力",
      cast: "即时",
      recast: "90秒",
      cost: "-",
      distant: "10",
      range: "0",
      rangeType: "zero",
      content: "一定时间内，令目标的力量与灵巧降低10%<BR>持续时间：10秒",
      change: "习得等级从40变更为22。<br>复唱时间从120秒变更为90秒。"
    },
    {
      name: "亲疏自行",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/6Y_LOLWQWJSjGvQYoaGNhNaP-I.png",
      tiurl: "",
      tname: "",
      ticon: [
        { "url": 'https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/rFrCBcRe9YrmPvb4fZkuFksSLw.png', tname: '防护职业' },
        { "url": 'https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/9muqitiUXEK0W3qnM33Nb7sATk.png', tname: '近战职业' },
        { "url": 'https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/oWWxUIO2KagIEhDXy0541MRD7M.png', tname: '远程物理职业' }
      ],
      lvl: "Lv32",
      classification: "能力",
      cast: "即时",
      recast: "120秒",
      cost: "-",
      distant: "0",
      range: "0",
      rangeType: "zero",
      content: "为自身张开一个防护罩，一定时间内令除特定攻击之外其他所有击退与吸引效果失效　持续时间：6秒<BR>防护罩追加效果（受到物理攻击时，发动几率100%）：攻击者减速20%　持续时间：15秒",
      change: "习得等级从12变更为32。<br>复唱时间从60秒变更为120秒。<br>适应职业新增防护职业和远程物理职业。<br>效果时间从5秒变更为6秒。"
    },
    {
      name: "真北",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/XZP5ljS8oyG6Fc82vyjrpY36Uk.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/9muqitiUXEK0W3qnM33Nb7sATk.png",
      tname: "近战职业",
      ticon: [{ "url": 'https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/9muqitiUXEK0W3qnM33Nb7sATk.png', tname: '近战职业' }],
      lvl: "Lv50",
      classification: "能力",
      cast: "即时",
      recast: "45秒",
      cost: "-",
      distant: "0",
      range: "0",
      rangeType: "zero",
      content: "一定时间内无视技能的方向要求　持续时间：10秒<BR>积蓄次数：2",
      change: "习得等级从48变更为50。<br>复唱时间从90秒变更为45秒。<br>效果时间从15秒变更为10秒。<br>新增“积蓄次数：2”。"
    }
  ];


  traits: any[] = [
    {
      isDisabled: "false",
      name: "长枪精通",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Dragoon/Trait_01.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/zWRkXGJIJhN7WHGGv1gVscRxmA.png",
      tname: "龙骑士",
      ticon: "",
      lvl: "Lv64",
      classification: "",
      cast: "",
      recast: "",
      cost: "",
      distant: "",
      range: "",
      rangeType: "zero",
      content: "龙牙龙爪命中时可以使用一次龙尾大回旋，龙尾大回旋命中时可以使用一次龙牙龙爪，并且此时的威力上升110",
      change: "龙牙龙爪和龙尾大回旋的威力上升效果从100变更为110。"
    },
    {
      isDisabled: "false",
      name: "红莲龙血",
      ndes: "通过特职任务获得",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Dragoon/Trait_02.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/zWRkXGJIJhN7WHGGv1gVscRxmA.png",
      tname: "龙骑士",
      ticon: "",
      lvl: "Lv70",
      classification: "",
      cast: "",
      recast: "",
      cost: "",
      distant: "",
      range: "",
      rangeType: "zero",
      content: "对自身附加龙眼状态<BR>在龙眼累积到第二阶段的状态下使用武神枪，苍天龙血就会变为红莲龙血<BR>在红莲龙血的状态下武神枪会变为死者之岸<BR>持续时间结束后，红莲龙血会恢复成苍天龙血<BR>发动条件：在苍天龙血状态下发动幻象冲",
      change: "红莲龙血的条件从“在龙眼累积到第三阶段”变更为“在龙眼累积到第二阶段”。"
    },
    {
      isDisabled: "false",
      name: "跳跃精通",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Dragoon/Trait_03.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/zWRkXGJIJhN7WHGGv1gVscRxmA.png",
      tname: "龙骑士",
      ticon: "",
      lvl: "Lv74",
      classification: "",
      cast: "",
      recast: "",
      cost: "",
      distant: "",
      range: "",
      rangeType: "zero",
      content: "跳跃变为高跳",
      change: ""
    },
    {
      isDisabled: "false",
      name: "长枪精通II",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Dragoon/Trait_04.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/zWRkXGJIJhN7WHGGv1gVscRxmA.png",
      tname: "龙骑士",
      ticon: "",
      lvl: "Lv76",
      classification: "",
      cast: "",
      recast: "",
      cost: "",
      distant: "",
      range: "",
      rangeType: "zero",
      content: "精准刺威力提高至290，贯通刺威力提高至140，开膛枪威力提高至150<BR>另外，在使用龙牙龙爪命中后使用龙尾大车轮时，或在使用龙尾大车轮命中后使用龙牙龙爪时，若攻击正确的方向，会对自身附加龙眼雷电预备状态<BR>持续时间：10秒<BR>效果时间内，精准刺变为龙眼雷电",
      change: ""
    },
    {
      isDisabled: "false",
      name: "龙血精通",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Dragoon/Trait_05.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/zWRkXGJIJhN7WHGGv1gVscRxmA.png",
      tname: "龙骑士",
      ticon: "",
      lvl: "Lv78",
      classification: "",
      cast: "",
      recast: "",
      cost: "",
      distant: "",
      range: "",
      rangeType: "zero",
      content: "苍天龙血与红莲龙血的持续时间延长到30秒",
      change: ""
    }
  ];

  ngOnInit(): void {
  }

  //获取攻击范围图标
  getRangeImage(rangeType: string) {
    return "../../assets/rangeUI/" + rangeType + ".png";
  }

}
