import { Component, OnInit } from '@angular/core';


@Component({
  selector: 'app-red-mage',
  templateUrl: './red-mage.component.html',
  styleUrls: ['./red-mage.component.css']
})
export class RedMageComponent implements OnInit {

  skills: any[] = [
    {
      name: "回刺",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Red Mage/Action_01.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/NRnqJxzRtbDKR1ZHzxazWBBR2Y.png",
      tname: "赤魔法师",
      ticon: "",
      lvl: "Lv1",
      classification: "战技",
      cast: "即时",
      recast: "2.5秒",
      cost: "-",
      distant: "3",
      range: 0,
      content: "对目标发动物理攻击　威力：130<BR>平衡量谱中黑魔元与白魔元都在30点以上时，该技能变为魔回刺",
      change: ""
    },
    {
      name: "摇荡",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Red Mage/Action_02.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/NRnqJxzRtbDKR1ZHzxazWBBR2Y.png",
      tname: "赤魔法师",
      ticon: "",
      lvl: "Lv2",
      classification: "魔法",
      cast: "2秒",
      recast: "2.5秒",
      cost: "魔力200",
      distant: "25",
      range: 0,
      content: "对目标发动无属性魔法攻击　威力：180<BR>追加效果：获得3点黑魔元与3点白魔元",
      change: ""
    },
    {
      name: "赤闪雷",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Red Mage/Action_03.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/NRnqJxzRtbDKR1ZHzxazWBBR2Y.png",
      tname: "赤魔法师",
      ticon: "",
      lvl: "Lv4",
      classification: "魔法",
      cast: "5秒",
      recast: "2.5秒",
      cost: "魔力300",
      distant: "25",
      range: 0,
      content: "对目标发动雷属性魔法攻击　威力：370<BR>追加效果：获得11点黑魔元<BR>追加效果（发动几率50%）：赤火炎预备　持续时间：30秒",
      change: "威力提升到370"
    },
    {
      name: "短兵相接",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Red Mage/Action_04.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/NRnqJxzRtbDKR1ZHzxazWBBR2Y.png",
      tname: "赤魔法师",
      ticon: "",
      lvl: "Lv6",
      classification: "能力",
      cast: "即时",
      recast: "40秒",
      cost: "-",
      distant: "25",
      range: 0,
      content: "冲向目标并发动物理攻击　威力：130<BR>止步状态下无法发动",
      change: ""
    },
    {
      name: "赤疾风",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Red Mage/Action_05.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/NRnqJxzRtbDKR1ZHzxazWBBR2Y.png",
      tname: "赤魔法师",
      ticon: "",
      lvl: "Lv10",
      classification: "魔法",
      cast: "5秒",
      recast: "2.5秒",
      cost: "魔力300",
      distant: "25",
      range: 0,
      content: "对目标发动风属性魔法攻击　威力：370<BR>追加效果：获得11点白魔元<BR>追加效果（发动几率50%）：赤飞石预备　持续时间：30秒",
      change: "威力提升到370"
    },
    {
      name: "散碎",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Red Mage/Action_06.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/NRnqJxzRtbDKR1ZHzxazWBBR2Y.png",
      tname: "赤魔法师",
      ticon: "",
      lvl: "Lv15",
      classification: "魔法",
      cast: "5秒",
      recast: "2.5秒",
      cost: "魔力400",
      distant: "25",
      range: "5",
      content: "对目标及其周围的敌人发动无属性范围魔法攻击　威力：120<BR>追加效果：获得3点黑魔元与3点白魔元",
      change: "习得等级从18变更为15。<br>威力从100变更为120。<br>删除“追加效果（发动几率30%）：散碎效果提高　效果时间：10秒<br>“散碎效果提高”状态中追加效果：获得10点黑魔元与10点白魔元”。<br>咏唱时间从2秒变更为5秒。"
    },
    {
      name: "赤震雷",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Red Mage/Action_07.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/NRnqJxzRtbDKR1ZHzxazWBBR2Y.png",
      tname: "赤魔法师",
      ticon: "",
      lvl: "Lv18",
      classification: "魔法",
      cast: "2秒",
      recast: "2.5秒",
      cost: "魔力400",
      distant: "25",
      range: "5",
      content: "对目标及其周围敌人发动雷属性魔法攻击　威力：120<BR>追加效果：获得7点黑魔元",
      change: ""
    },
    {
      name: "赤烈风",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Red Mage/Action_08.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/NRnqJxzRtbDKR1ZHzxazWBBR2Y.png",
      tname: "赤魔法师",
      ticon: "",
      lvl: "Lv22",
      classification: "魔法",
      cast: "2秒",
      recast: "2.5秒",
      cost: "魔力400",
      distant: "25",
      range: "5",
      content: "对目标及其周围敌人发动风属性魔法攻击　威力：120<BR>追加效果：获得7点白魔元",
      change: ""
    },
    {
      name: "赤火炎",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Red Mage/Action_09.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/NRnqJxzRtbDKR1ZHzxazWBBR2Y.png",
      tname: "赤魔法师",
      ticon: "",
      lvl: "Lv26",
      classification: "魔法",
      cast: "2秒",
      recast: "2.5秒",
      cost: "魔力200",
      distant: "25",
      range: 0,
      content: "对目标发动火属性魔法攻击　威力：300<BR>追加效果：获得9点黑魔元<BR>发动条件：赤火炎预备状态中",
      change: "威力提升到300"
    },
    {
      name: "赤飞石",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Red Mage/Action_10.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/NRnqJxzRtbDKR1ZHzxazWBBR2Y.png",
      tname: "赤魔法师",
      ticon: "",
      lvl: "Lv30",
      classification: "魔法",
      cast: "2秒",
      recast: "2.5秒",
      cost: "魔力200",
      distant: "25",
      range: 0,
      content: "对目标发动土属性魔法攻击　威力：300<BR>追加效果：获得9点白魔元<BR>发动条件：赤飞石预备状态中",
      change: "威力提升到300"
    },
    {
      name: "交击斩",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Red Mage/Action_11.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/NRnqJxzRtbDKR1ZHzxazWBBR2Y.png",
      tname: "赤魔法师",
      ticon: "",
      lvl: "Lv35",
      classification: "战技",
      cast: "即时",
      recast: "2.5秒",
      cost: "-",
      distant: "3",
      range: 0,
      content: "对目标发动物理攻击　威力：100<BR>连击条件：回刺或魔回刺　连击中威力：150<BR>平衡量谱中黑魔元与白魔元都在25点以上时，该技能变为魔交击斩",
      change: ""
    },
    {
      name: "移转",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Red Mage/Action_12.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/NRnqJxzRtbDKR1ZHzxazWBBR2Y.png",
      tname: "赤魔法师",
      ticon: "",
      lvl: "Lv40",
      classification: "能力",
      cast: "即时",
      recast: "35秒",
      cost: "-",
      distant: "5",
      range: 0,
      content: "对目标发动物理攻击　威力：200<BR>追加效果：后跳15米距离<BR>止步状态下无法发动<BR>与交剑共享复唱时间",
      change: "威力从130变更为200。<br>新增“与交剑共享复唱时间”。"
    },
    {
      name: "飞刺",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Red Mage/Action_13.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/NRnqJxzRtbDKR1ZHzxazWBBR2Y.png",
      tname: "赤魔法师",
      ticon: "",
      lvl: "Lv45",
      classification: "能力",
      cast: "即时",
      recast: "25秒",
      cost: "-",
      distant: "25",
      range: 0,
      content: "对目标发动物理攻击　威力：4440",
      change: "威力从420变更为440"
    },
    {
      name: "连攻",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Red Mage/Action_14.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/NRnqJxzRtbDKR1ZHzxazWBBR2Y.png",
      tname: "赤魔法师",
      ticon: "",
      lvl: "Lv50",
      classification: "战技",
      cast: "即时",
      recast: "2.5秒",
      cost: "-",
      distant: "3",
      range: 0,
      content: "对目标发动物理攻击　威力：100<BR>连击条件：交击斩或魔交击斩<BR>连击中威力：230<BR>平衡量谱中黑魔元与白魔元都在25点以上时，该技能变为魔连攻",
      change: ""
    },
    {
      name: "促进",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Red Mage/Action_15.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/NRnqJxzRtbDKR1ZHzxazWBBR2Y.png",
      tname: "赤魔法师",
      ticon: "",
      lvl: "Lv50",
      classification: "能力",
      cast: "即时",
      recast: "55秒",
      cost: "-",
      distant: 0,
      range: 0,
      content: "一定时间内，前3次能附加赤火炎预备状态与赤飞石预备状态的技能追加效果发动率变为100%<BR>持续时间：20秒",
      change: "效果由「一定时间内，下次能附加赤火炎预备状态与赤飞石预备状态的技能追加效果发动率变为100%」改为「一定时间内，前3次能附加赤火炎预备状态与赤飞石预备状态的技能追加效果发动率变为100%」<br>持续时间由10秒变为20秒<br>复唱时间由35秒变为55秒"
    },
    {
      name: "划圆斩",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Red Mage/Action_16.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/NRnqJxzRtbDKR1ZHzxazWBBR2Y.png",
      tname: "赤魔法师",
      ticon: "",
      lvl: "Lv52",
      classification: "战技",
      cast: "即时",
      recast: "2.5秒",
      cost: "-",
      distant: "8",
      range: "8",
      content: "向目标所在方向发出扇形范围物理攻击　威力：60<BR>平衡量谱中黑魔元与白魔元都在20点以上时，该技能变为魔划圆斩",
      change: "射程与范围由6m变为8m"
    },
    {
      name: "赤治疗",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Red Mage/Action_17.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/NRnqJxzRtbDKR1ZHzxazWBBR2Y.png",
      tname: "赤魔法师",
      ticon: "",
      lvl: "Lv54",
      classification: "魔法",
      cast: "2秒",
      recast: "2.5秒",
      cost: "魔力500",
      distant: "30",
      range: 0,
      content: "恢复目标的体力　恢复力：350",
      change: ""
    },
    {
      name: "六分反击",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Red Mage/Action_18.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/NRnqJxzRtbDKR1ZHzxazWBBR2Y.png",
      tname: "赤魔法师",
      ticon: "",
      lvl: "Lv56",
      classification: "能力",
      cast: "即时",
      recast: "35秒",
      cost: "-",
      distant: "25",
      range: "6",
      content: "对目标及其周围敌人发动范围物理攻击　威力：400",
      change: "・威力从380变更为400。<br>・删除「攻击复数敌人时，对目标之外的敌人威力降低50%」。"
    },
    {
      name: "鼓励",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Red Mage/Action_19.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/NRnqJxzRtbDKR1ZHzxazWBBR2Y.png",
      tname: "赤魔法师",
      ticon: "",
      lvl: "Lv58",
      classification: "能力",
      cast: "即时",
      recast: "120秒",
      cost: "-",
      distant: 0,
      range: "15",
      content: "一定时间内，自身发动魔法攻击造成的伤害提高10%<BR>持续时间：20秒<BR>此效果每4秒降低2%<BR>追加效果：令周围队员发动物理攻击造成的伤害提高10%<BR>持续时间：20秒<BR>此效果每4秒降低2%",
      change: ""
    },
    {
      name: "倍增",
      ndes: "通过特职任务获得",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Red Mage/Action_20.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/NRnqJxzRtbDKR1ZHzxazWBBR2Y.png",
      tname: "赤魔法师",
      ticon: "",
      lvl: "Lv60",
      classification: "能力",
      cast: "即时",
      recast: "110秒",
      cost: "-",
      distant: 0,
      range: 0,
      content: "当前平衡量谱中积累的量值翻倍<BR>追加效果：重置短兵相接和转移以及交剑的复唱时间<BR>追加效果：自身发动魔法攻击造成的伤害提高5%<BR>持续时间：10秒<BR>此技能会中断连击",
      change: "追加效果的対象新增“交剑”。<br>新增“追加效果：自身发动魔法攻击造成的伤害提高5%。<br>效果时间：10秒”。<br>复唱时间从120秒变更为110秒。"
    },
    {
      name: "震荡",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Red Mage/Action_21.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/NRnqJxzRtbDKR1ZHzxazWBBR2Y.png",
      tname: "赤魔法师",
      ticon: "",
      lvl: "Lv62",
      classification: "魔法",
      cast: "2秒",
      recast: "2.5秒",
      cost: "魔力200",
      distant: "25",
      range: 0,
      content: "对目标发动无属性魔法攻击　威力：290<BR>追加效果：获得3点黑魔元与3点白魔元",
      change: "威力从280变更为290。"
    },
    {
      name: "赤复活",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Red Mage/Action_22.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/NRnqJxzRtbDKR1ZHzxazWBBR2Y.png",
      tname: "赤魔法师",
      ticon: "",
      lvl: "Lv64",
      classification: "魔法",
      cast: "10秒",
      recast: "2.5秒",
      cost: "魔力2400",
      distant: "30",
      range: 0,
      content: "令无法战斗的目标以衰弱状态重新振作起来",
      change: ""
    },
    {
      name: "冲击",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Red Mage/Action_23.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/NRnqJxzRtbDKR1ZHzxazWBBR2Y.png",
      tname: "赤魔法师",
      ticon: "",
      lvl: "Lv66",
      classification: "魔法",
      cast: "5秒",
      recast: "2.5秒",
      cost: "魔力400",
      distant: "25",
      range: "5",
      content: "对目标及其周围敌人发动无属性范围魔法攻击　威力：220<BR>追加效果：获得3点黑魔元与3点白魔元",
      change: "效果更新。"
    },
    {
      name: "赤核爆",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Red Mage/Action_24.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/NRnqJxzRtbDKR1ZHzxazWBBR2Y.png",
      tname: "赤魔法师",
      ticon: "",
      lvl: "Lv68",
      classification: "魔法",
      cast: "即时",
      recast: "2.5秒",
      cost: "魔力400",
      distant: "25",
      range: 0,
      content: "对目标发动火属性魔法攻击　威力：600<BR>连击条件：魔连攻<BR>追加效果：获得21点黑魔元<BR>追加效果（发动几率20%）：赤火炎预备　持续时间：30秒<BR>发动时白魔元高于黑魔元则100%发动追加效果<BR>发动条件：魔连攻成功时<BR>若满足发动条件，则赤闪雷变为赤核爆<BR><BR>※该技能无法设置到热键栏",
      change: "新增“若满足发动条件，则赤闪雷变为赤核爆”。<br>新增“※该技能无法设置到热键栏”。"
    },
    {
      name: "赤神圣",
      ndes: "通过特职任务获得",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Red Mage/Action_25.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/NRnqJxzRtbDKR1ZHzxazWBBR2Y.png",
      tname: "赤魔法师",
      ticon: "",
      lvl: "Lv70",
      classification: "魔法",
      cast: "即时",
      recast: "2.5秒",
      cost: "魔力400",
      distant: "25",
      range: 0,
      content: "对目标发动无属性魔法攻击　威力：600<BR>连击条件：魔连攻<BR>追加效果：获得21点白魔元<BR>追加效果（发动几率20%）：赤飞石预备　持续时间：30秒<BR>发动时黑魔元高于白魔元则100%发动追加效果<BR>发动条件：魔连攻成功时<BR>若满足发动条件，则赤疾风变为赤神圣<BR><BR>※该技能无法设置到热键栏",
      change: "新增“若满足发动条件，则赤疾风变为赤神圣”。<br>新增“※该技能无法设置到热键栏”。"
    },
    {
      name: "交剑",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Red Mage/Action_26.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/NRnqJxzRtbDKR1ZHzxazWBBR2Y.png",
      tname: "赤魔法师",
      ticon: "",
      lvl: "Lv72",
      classification: "能力",
      cast: "即时",
      recast: "35秒",
      cost: "-",
      distant: "3",
      range: 0,
      content: "对目标发动物理攻击　威力：150<BR>与移转共享复唱时间",
      change: ""
    },
    {
      name: "续斩",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Red Mage/Action_27.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/NRnqJxzRtbDKR1ZHzxazWBBR2Y.png",
      tname: "赤魔法师",
      ticon: "",
      lvl: "Lv76",
      classification: "战技",
      cast: "即时",
      recast: "2.5秒",
      cost: "-",
      distant: "3",
      range: 0,
      content: "对目标发动物理攻击　威力：100<BR>平衡量谱中黑魔元与白魔元都在5点以上时，该技能变为魔续斩",
      change: ""
    },
    {
      name: "焦热",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Red Mage/Action_28.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/NRnqJxzRtbDKR1ZHzxazWBBR2Y.png",
      tname: "赤魔法师",
      ticon: "",
      lvl: "Lv80",
      classification: "魔法",
      cast: "即时",
      recast: "2.5秒",
      cost: "魔力400",
      distant: "25",
      range: 0,
      content: "对目标发动无属性魔法攻击　威力：700<BR>连击条件：赤核爆或赤神圣<BR>追加效果：获得7点黑魔元与7点白魔元<BR>发动条件：赤核爆或赤神圣成功时<BR>满足发动条件后，震荡变为焦热<BR><BR>※该技能无法设置到热键栏",
      change: ""
    },
    {
      name: "魔回刺",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Red Mage/Action_29.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/NRnqJxzRtbDKR1ZHzxazWBBR2Y.png",
      tname: "赤魔法师",
      ticon: "",
      lvl: "Lv1",
      classification: "战技",
      cast: "即时",
      recast: "1.5秒",
      cost: "「黑魔元」30<br>「白魔元」30",
      distant: "3",
      range: 0,
      content: "对目标发动无属性魔法攻击　威力：220<BR>发动条件：黑魔元、白魔元各30点<BR><BR>※该技能无法设置到热键栏",
      change: "威力从210变更为220。"
    },
    {
      name: "魔交击斩",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Red Mage/Action_30.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/NRnqJxzRtbDKR1ZHzxazWBBR2Y.png",
      tname: "赤魔法师",
      ticon: "",
      lvl: "Lv35",
      classification: "战技",
      cast: "即时",
      recast: "1.5秒",
      cost: "「黑魔元」25<br>「白魔元」25",
      distant: "3",
      range: 0,
      content: "对目标发动无属性魔法攻击　威力：100<BR>连击条件：回刺或魔回刺　连击中威力：290<BR>发动条件：黑魔元、白魔元各25点<BR><BR>※该技能无法设置到热键栏",
      change: ""
    },
    {
      name: "魔连攻",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Red Mage/Action_31.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/NRnqJxzRtbDKR1ZHzxazWBBR2Y.png",
      tname: "赤魔法师",
      ticon: "",
      lvl: "Lv50",
      classification: "战技",
      cast: "即时",
      recast: "2.2秒",
      cost: "「黑魔元」25<br>「白魔元」25",
      distant: "3",
      range: 0,
      content: "对目标发动无属性魔法攻击　威力：100<BR>连击条件：魔交击斩<BR>连击中威力：470<BR>发动条件：黑魔元、白魔元各25点<BR><BR>※该技能无法设置到热键栏",
      change: ""
    },
    {
      name: "魔划圆斩",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Red Mage/Action_32.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/NRnqJxzRtbDKR1ZHzxazWBBR2Y.png",
      tname: "赤魔法师",
      ticon: "",
      lvl: "Lv52",
      classification: "战技",
      cast: "即时",
      recast: "1.5秒",
      cost: "「黑魔元」20<br>「白魔元」20",
      distant: "8",
      range: "8",
      content: "向目标所在方向发出扇形范围魔法攻击　威力：200<BR>发动条件：黑魔元、白魔元各20点<BR><BR>※该技能无法设置到热键栏",
      change: "射程与范围由6m变为8m"
    },
    {
      name: "魔续斩",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Red Mage/Action_33.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/NRnqJxzRtbDKR1ZHzxazWBBR2Y.png",
      tname: "赤魔法师",
      ticon: "",
      lvl: "Lv76",
      classification: "战技",
      cast: "即时",
      recast: "2.2秒",
      cost: "「黑魔元」5<br>「白魔元」5",
      distant: "25",
      range: 0,
      content: "对目标发动无属性魔法攻击　威力：300<BR>发动条件：黑魔元与白魔元各5点<BR><BR>※该技能无法设置到热键栏",
      change: "威力由250变为300"
    }
  ];

  roleSkills: any[] = [
    {
      name: "昏乱",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Magical Ranged DPS Role Action_01.png",
      tiurl: "",
      tname: "远程魔法职业",
      ticon: [{
        url: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/8Dnf8Wy9IyxIt21y6lrE5atKt0.png",
        tname: "远程魔法职业"
      }],
      lvl: "Lv8",
      classification: "能力",
      cast: "即时",
      recast: "90秒",
      cost: "-",
      distant: "25",
      range: 0,
      content: "一定时间内，令目标的智力与精神降低10%<BR>持续时间：10秒",
      change: ""
    },
    {
      name: "即刻咏唱",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Magical Ranged DPS Role Action_02.png",
      tiurl: "",
      tname: "",
      ticon: [
        {
          url: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/V5xx3kfnREBO-2xWbTUW2Csy_Q.png",
          tname: "治疗职业"
        },
        {
          url: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/8Dnf8Wy9IyxIt21y6lrE5atKt0.png",
          tname: "远程魔法职业"
        }
      ],
      lvl: "Lv18",
      classification: "能力",
      cast: "即时",
      recast: "60秒",
      cost: "-",
      distant: 0,
      range: 0,
      content: "一定时间内，下次咏唱的魔法没有任何咏唱时间<BR>持续时间：10秒",
      change: "习得等级从32变更为18。"
    },
    {
      name: "醒梦",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Magical Ranged DPS Role Action_03.png",
      tiurl: "",
      tname: "",
      ticon: [
        {
          url: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/V5xx3kfnREBO-2xWbTUW2Csy_Q.png",
          tname: "治疗职业"
        },
        {
          url: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/8Dnf8Wy9IyxIt21y6lrE5atKt0.png",
          tname: "远程魔法职业"
        }
      ],
      lvl: "Lv24",
      classification: "能力",
      cast: "即时",
      recast: "60秒",
      cost: "-",
      distant: 0,
      range: 0,
      content: "持续恢复自身魔力<BR>效果量：50　持续时间：21秒",
      change: "删除“将自身的仇恨减半”。<br>复唱时间从120秒变更为60秒。<br>效果量从80变更为50。"
    },
    {
      name: "沉稳咏唱",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Magical Ranged DPS Role Action_04.png",
      tiurl: "",
      tname: "",
      ticon: [
        {
          url: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/V5xx3kfnREBO-2xWbTUW2Csy_Q.png",
          tname: "治疗职业"
        },
        {
          url: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/8Dnf8Wy9IyxIt21y6lrE5atKt0.png",
          tname: "远程魔法职业"
        }
      ],
      lvl: "Lv44",
      classification: "能力",
      cast: "即时",
      recast: "120秒",
      cost: "-",
      distant: 0,
      range: 0,
      content: "一定时间内，咏唱的魔法不会被任何妨碍打断<BR>同时，令除特定攻击之外其他所有击退与吸引效果失效<BR>持续时间：6秒",
      change: "复唱时间从30秒变更为120秒。<br>效果时间从5秒变更为6秒。"
    }
  ];


  traits: any[] = [
    {
      name: "连续咏唱",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Red Mage/Trait_01.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/NRnqJxzRtbDKR1ZHzxazWBBR2Y.png",
      tname: "赤魔法师",
      ticon: "",
      lvl: "Lv1",
      content: "发动有咏唱时间的魔法时，对自身附加连续咏唱状态<BR>连续咏唱效果：下次咏唱魔法不需要咏唱时间<BR>若在持续时间中发动自动攻击或能力之外的技能，会立即解除连续咏唱状态",
      change: ""
    },
    {
      name: "技能效果提高",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Red Mage/Trait_02.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/NRnqJxzRtbDKR1ZHzxazWBBR2Y.png",
      tname: "赤魔法师",
      ticon: "",
      lvl: "Lv20",
      content: "除自动攻击外的技能造成的伤害提高至基本值的1.1倍，恢复技能的恢复量也提高至基本值的1.1倍",
      change: ""
    },
    {
      name: "技能效果提高II",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Red Mage/Trait_03.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/NRnqJxzRtbDKR1ZHzxazWBBR2Y.png",
      tname: "赤魔法师",
      ticon: "",
      lvl: "Lv40",
      content: "除自动攻击外的技能造成的伤害提高至基本值的1.3倍，恢复技能的恢复量也提高至基本值的1.3倍",
      change: ""
    },
    {
      name: "摇荡效果提高",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Red Mage/Trait_04.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/NRnqJxzRtbDKR1ZHzxazWBBR2Y.png",
      tname: "赤魔法师",
      ticon: "",
      lvl: "Lv62",
      content: "摇荡变为震荡<br>将赤闪雷和赤疾风的威力提高到370,将赤火炎和赤飞石的威力提高到310。",
      change: "赤火炎和赤飞石的威力提升从300变更为310。"
    },
    {
      name: "散碎精通",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Red Mage/Trait_05.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/NRnqJxzRtbDKR1ZHzxazWBBR2Y.png",
      tname: "赤魔法师",
      ticon: "",
      lvl: "Lv66",
      content: "散碎变为冲击",
      change: ""
    },
    {
      name: "移转效果提高",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Red Mage/Trait_06.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/NRnqJxzRtbDKR1ZHzxazWBBR2Y.png",
      tname: "赤魔法师",
      ticon: "",
      lvl: "Lv72",
      content: "转移的威力提高到200",
      change: ""
    },
    {
      name: "倍增效果提高",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Red Mage/Trait_07.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/NRnqJxzRtbDKR1ZHzxazWBBR2Y.png",
      tname: "赤魔法师",
      ticon: "",
      lvl: "Lv74",
      content: "倍增的复唱时间缩短到110秒<BR>并附加自身造成的魔法伤害提高5%的效果",
      change: ""
    },
    {
      name: "六分反击效果提高",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Red Mage/Trait_08.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/NRnqJxzRtbDKR1ZHzxazWBBR2Y.png",
      tname: "赤魔法师",
      ticon: "",
      lvl: "Lv78",
      content: "六分反击的复唱时间缩短到35秒<BR>并将赤震雷与赤烈风的威力提高到120",
      change: ""
    }
  ];

  constructor() { }

  ngOnInit(): void {
  }

}
