import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-summoner',
  templateUrl: './summoner.component.html',
  styleUrls: ['./summoner.component.css']
})
export class SummonerComponent implements OnInit {

  constructor() { }

  skills: any[] = [
   {
      name: "毁灭", 
      ndes: "", 
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Summoner/Action_01.png", 
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/_3v-EDzckpsEC39oe0t4A8pLJk.png", 
      tname: "秘术师", 
      ticon: "", 
      lvl: "Lv1", 
      classification: "魔法", 
      cast: "1.5秒", 
      recast: "2.5秒", 
      cost: "魔力200", 
      distant: "25", 
      range:0, 
      content: "对目标发动无属性魔法攻击　威力：160", 
      change: "咏唱时间改为1.5秒"
   }, 
   {
      name: "Summon Carbuncle<BR>宝石兽召唤", 
      ndes: "", 
      pic: "../../assets/SMN/宝石兽召唤.png", 
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/_3v-EDzckpsEC39oe0t4A8pLJk.png", 
      tname: "秘术师", 
      ticon: "", 
      lvl: "Lv2", 
      classification: "魔法", 
      cast: "2.5秒", 
      recast: "2.5秒", 
      cost: "魔力400", 
      distant: "0", 
      range:0, 
      content: "召唤有辅助能力的宝石兽同行", 
      change: "召唤兽不在有自动攻击，和攻击技能<>仅作为使用特定技能的条件存在"
   }, 
   {
      name: "Radiant Aegis<BR>守护之光",
      ndes: "",
      pic: "../../assets/SMN/守护之光.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/_3v-EDzckpsEC39oe0t4A8pLJk.png",
      tname: "秘术师",
      ticon: "",
      lvl: "Lv2",
      classification: "能力",
      cast: "即时",
      recast: "60秒",
      cost: "-",
      distant: "0",
      range: 0,
      content: "令宝石兽发动守护之光<BR>对召唤该召唤兽的召唤师附加能够抵御一定伤害的防护罩<BR>该防护罩能够抵消相当于目标最大体力30%的伤害量<BR>持续时间：30秒<BR>积蓄次数：2<BR>发动条件：宝石兽处于同行状态<BR>该能力有单独计算的复唱时间",
      change: "新自保技能"
   }, 
   {
      name: "医术", 
      ndes: "", 
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Summoner/Action_03.png", 
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/_3v-EDzckpsEC39oe0t4A8pLJk.png", 
      tname: "秘术师", 
      ticon: "", 
      lvl: "Lv4", 
      classification: "魔法", 
      cast: "1.5秒", 
      recast: "2.5秒", 
      cost: "魔力400", 
      distant: "30", 
      range:0, 
      content: "恢复目标的体力　恢复力：400", 
      change: ""
   }, 
   {
      name: "Aethercharge<BR>以太充能", 
      ndes: "", 
      pic: "../../assets/SMN/以太充能.png", 
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/_3v-EDzckpsEC39oe0t4A8pLJk.png", 
      tname: "秘术师", 
      ticon: "", 
      lvl: "Lv6", 
      classification: "魔法", 
      cast: "即时", 
      recast: "60秒", 
      cost: "-", 
      distant:0, 
      range:0, 
      content: "对自身附加以太充能状态<BR>持续时间：15秒<BR>以太充能效果：自身发动的毁灭、毁坏威力增加50，迸裂威力增加20<BR>追加效果：对自身附加红宝石奥秘、绿宝石奥秘、黄宝石奥秘状态<BR>发动条件：自身处于战斗状态且宝石兽处于同行状态", 
      change: "新技能<BR>龙神附体（龙神召唤）下位技能，用以完善召唤低等级循环"
   }, 
   {
      name: "Summon Ruby<BR>红宝石兽召唤", 
      ndes: "", 
      pic: "../../assets/SMN/红宝石兽召唤.png", 
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/_3v-EDzckpsEC39oe0t4A8pLJk.png", 
      tname: "秘术师", 
      ticon: "", 
      lvl: "Lv6", 
      classification: "魔法", 
      cast: "即时", 
      recast: "2.5秒", 
      cost: "「红宝石奥秘」",
      distant: "25", 
      range:0, 
      content: "召唤红宝石兽，令其发动红宝石之辉<BR>冲向目标并发动火属性魔法攻击  威力：400<BR>追加效果：2档火属性以太<BR>持续时间：30秒<BR>火属性以太效果：宝石之光和宝石之耀变为火属性魔法<BR>发动条件：红宝石奥秘，且宝石兽处于同行状态<BR>不能在自身附加了土属性以太或风属性以太时使用", 
      change: "火神召唤下位技能，用以完善召唤低等级循环"
   }, 
   {
      name: "Gemshine<BR>宝石之光", 
      ndes: "", 
      pic: "../../assets/SMN/宝石之光.png", 
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/_3v-EDzckpsEC39oe0t4A8pLJk.png", 
      tname: "秘术师", 
      ticon: "", 
      lvl: "Lv6", 
      classification: "魔法", 
      cast: "2.5秒", 
      recast: "2.5秒", 
      cost: "-", 
      distant: "25", 
      range:0, 
      content: "根据自身以太效果发动对应技能<BR>火属性以太时效果：变为火属性单体攻击魔法<BR>土属性以太时效果：变为土属性单体攻击魔法<BR>风属性以太时效果：变为风属性单体攻击魔法", 
      change: "三神状态下消耗以太的单体技能"
   }, 
   {
      name: "能量吸收", 
      ndes: "", 
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Summoner/Action_10.png", 
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/_3v-EDzckpsEC39oe0t4A8pLJk.png", 
      tname: "秘术师", 
      ticon: "", 
      lvl: "Lv10", 
      classification: "能力", 
      cast: "即时", 
      recast: "60秒", 
      cost: "-", 
      distant: "25", 
      range:0, 
      content: "对目标发动无属性魔法攻击　威力：200<BR>追加效果：2档以太超流<BR>追加效果：毁绝预备<BR>持续时间：60秒<BR>与能量抽取共享复唱时间", 
      change: "威力上调、cd调整为60秒，获取1层毁绝"
   }, 
   {
      name: "溃烂爆发", 
      ndes: "", 
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Summoner/Action_09.png", 
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/_3v-EDzckpsEC39oe0t4A8pLJk.png", 
      tname: "秘术师", 
      ticon: "", 
      lvl: "Lv10", 
      classification: "能力", 
      cast: "即时", 
      recast: "3秒", 
      cost: "「以太超流」1", 
      distant: "25", 
      range:0, 
      content: "对目标发动无属性魔法攻击  威力：300<BR>发动条件：以太超流", 
      change: "由于DOT的删除，改为固定300威力能力技"
   }, 
   {
      name: "复生", 
      ndes: "", 
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Summoner/Action_07.png", 
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/_3v-EDzckpsEC39oe0t4A8pLJk.png", 
      tname: "秘术师", 
      ticon: "", 
      lvl: "Lv12", 
      classification: "魔法", 
      cast: "8秒", 
      recast: "2.5秒", 
      cost: "魔力2400", 
      distant: "30", 
      range:0, 
      content: "令无法战斗的目标以衰弱状态重新振作起来", 
      change: ""
   }, 
   {
      name: "Summon Topaz<BR>黄宝石兽召唤", 
      ndes: "", 
      pic: "../../assets/SMN/黄宝石兽召唤.png", 
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/_3v-EDzckpsEC39oe0t4A8pLJk.png", 
      tname: "秘术师", 
      ticon: "", 
      lvl: "Lv15", 
      classification: "魔法", 
      cast: "即时", 
      recast: "2.5秒", 
      cost: "「黄宝石奥秘」", 
      distant: "25", 
      range:0, 
      content: "召唤黄宝石兽，令其发动黄宝石之辉<BR>冲向目标并发动土属性魔法攻击  威力：400<BR>追加效果：4档土属性以太<BR>持续时间：30秒<BR>土属性以太效果：宝石之光和宝石之耀变为土属性魔法<BR>发动条件：黄宝石奥秘，且宝石兽处于同行状态<BR>不能在自身附加了火属性以太或风属性以太时使用", 
      change: "土神召唤下位技能，用以完善召唤低等级循环"
   }, 
   {
      name: "Summon Emerald<BR>绿宝石兽召唤", 
      ndes: "", 
      pic: "../../assets/SMN/绿宝石兽召唤.png", 
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/_3v-EDzckpsEC39oe0t4A8pLJk.png", 
      tname: "秘术师", 
      ticon: "", 
      lvl: "Lv22", 
      classification: "魔法", 
      cast: "即时", 
      recast: "2.5秒", 
      cost: "「绿宝石奥秘」", 
      distant: "25", 
      range:0, 
      content: "召唤绿宝石兽，令其发动绿宝石之辉<BR>冲向目标并发动风属性魔法攻击  威力：400<BR>追加效果：4档风属性以太<BR>持续时间：30秒<BR>风属性以太效果：宝石之光和宝石之耀变为风属性魔法<BR>发动条件：绿宝石奥秘，且宝石兽处于同行状态<BR>不能在自身附加了火属性以太或土属性以太时使用", 
      change: "风神召唤下位技能，用以完善召唤低等级循环"
   }, 
   {
      name: "迸裂", 
      ndes: "通过特职任务获得", 
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Summoner/Action_16.png", 
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/_3v-EDzckpsEC39oe0t4A8pLJk.png", 
      tname: "秘术师", 
      ticon: "", 
      lvl: "Lv26", 
      classification: "魔法", 
      cast: "2.5秒", 
      recast: "2.5秒", 
      cost: "魔力300", 
      distant: "25", 
      range: "5", 
      content: "对目标及其周围的敌人发动无属性范围魔法攻击　威力：100", 
      change: "威力上调，习得等级更变"
   },
   {
      name: "Precious Brilliance<BR>宝石之耀", 
      ndes: "", 
      pic: "../../assets/SMN/宝石之耀.png", 
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/_3v-EDzckpsEC39oe0t4A8pLJk.png", 
      tname: "秘术师", 
      ticon: "", 
      lvl: "Lv26", 
      classification: "魔法", 
      cast: "2.5秒", 
      recast: "2.5秒", 
      cost: "-", 
      distant: "25", 
      range:0, 
      content: "根据自身以太效果发动对应技能<BR>火属性以太时效果：变为火属性范围攻击魔法<BR>土属性以太时效果：变为土属性范围攻击魔法<BR>风属性以太时效果：变为风属性范围攻击魔法", 
      change: "三神状态下消耗以太的AOE技能"
   }, 
   {
      name: "毁坏", 
      ndes: "", 
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Summoner/Action_15.png", 
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/_3v-EDzckpsEC39oe0t4A8pLJk.png", 
      tname: "秘术师", 
      ticon: "", 
      lvl: "Lv30", 
      classification: "魔法", 
      cast: "1.5秒", 
      recast: "2.5秒", 
      cost: "魔力200", 
      distant: "25", 
      range:0, 
      content: "对目标发动无属性魔法攻击　威力：270", 
      change: "改为毁灭的上位替换"
   }, 
   {
      name: "Summon Ifrit<BR>火神召唤", 
      ndes: "", 
      pic: "../../assets/SMN/火神召唤.png", 
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/ZwJFxv3XnfqB5N6tKbgXKnj6BU.png", 
      tname: "召唤师", 
      ticon: "", 
      lvl: "Lv30", 
      classification: "魔法", 
      cast: "即时", 
      recast: "2.5秒", 
      cost: "「红宝石奥秘」",
      distant: "25", 
      range:0, 
      content: "召唤火神伊芙利特，令其发动地狱之火炎<BR>冲向目标并向其所在方向发动火属性扇形魔法攻击  威力：600<BR>攻击复数敌人时，对目标之外的敌人威力降低60%<BR>追加效果：2档火属性以太<BR>持续时间：30秒<BR>火属性以太效果：宝石之光和宝石之耀变为火属性魔法<BR>追加效果：深红旋风预备<BR>持续时间：永久<BR>深红旋风预备状态在发动其他属性召唤技能时结束<BR>发动条件：红宝石奥秘，且宝石兽处于同行状态<BR>不能在自身附加了土属性以太或风属性以太时使用", 
      change: "火神召唤II下位技能，用以完善召唤低等级循环"
   }, 
   {
      name: "Summon Titan<BR>土神召唤", 
      ndes: "", 
      pic: "../../assets/SMN/土神召唤.png", 
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/ZwJFxv3XnfqB5N6tKbgXKnj6BU.png", 
      tname: "召唤师", 
      ticon: "", 
      lvl: "Lv35", 
      classification: "魔法", 
      cast: "即时", 
      recast: "2.5秒", 
      cost: "「黄宝石奥秘」",
      distant: "25", 
      range:0, 
      content: "召唤土神泰坦，令其发动大地之怒<BR>冲向目标并对目标周围敌人发动土属性范围魔法攻击  威力：600<BR>攻击复数敌人时，对目标之外的敌人威力降低60%<BR>追加效果：4档土属性以太<BR>持续时间：30秒<BR>土属性以太效果：宝石之光和宝石之耀变为土属性魔法<BR>发动条件：黄宝石奥秘，且宝石兽处于同行状态<BR>不能在自身附加了火属性以太或风属性以太时使用", 
      change: "土神召唤II下位技能，用以完善召唤低等级循环"
   }, 
   {
      name: "痛苦核爆", 
      ndes: "", 
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Summoner/Action_19.png", 
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/ZwJFxv3XnfqB5N6tKbgXKnj6BU.png", 
      tname: "召唤师", 
      ticon: "", 
      lvl: "Lv40", 
      classification: "能力", 
      cast: "即时", 
      recast: "3秒", 
      cost: "「以太超流」1", 
      distant: "25", 
      range: "5", 
      content: "对目标及其周围敌人发动无属性范围魔法攻击　威力：150<BR>发动条件：以太超流", 
      change: ""
   }, 
   {
      name: "Summon Garuda<BR>风神召唤", 
      ndes: "", 
      pic: "../../assets/SMN/风神召唤.png", 
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/ZwJFxv3XnfqB5N6tKbgXKnj6BU.png", 
      tname: "召唤师", 
      ticon: "", 
      lvl: "Lv45", 
      classification: "魔法", 
      cast: "即时", 
      recast: "2.5秒", 
      cost: "「绿宝石奥秘」",
      distant: "25", 
      range:0, 
      content: "召唤风神迦楼罗，令其发动大气爆发<BR>对目标及其周围敌人发动风属性范围魔法攻击  威力：600<BR>攻击复数敌人时，对目标之外的敌人威力降低60%<BR>追加效果：4档风属性以太<BR>持续时间：30秒<BR>风属性以太效果：宝石之光和宝石之耀变为风属性魔法<BR>追加效果：螺旋气流预备<BR>持续时间：永久<BR>螺旋气流预备状态在发动其他属性召唤技能时结束<BR>发动条件：绿宝石奥秘，且宝石兽处于同行状态<BR>不能在自身附加了火属性以太或土属性以太时使用", 
      change: "风神召唤II下位技能，用以完善召唤低等级循环"
   }, 
   {
      name: "能量抽取", 
      ndes: "通过特职任务获得", 
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Summoner/Action_14.png", 
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/ZwJFxv3XnfqB5N6tKbgXKnj6BU.png", 
      tname: "召唤师", 
      ticon: "", 
      lvl: "Lv52", 
      classification: "能力", 
      cast: "即时", 
      recast: "60秒", 
      cost: "-", 
      distant: "25", 
      range: "5", 
      content: "对目标及其周围的敌人发动无属性范围魔法攻击　威力：100<BR>追加效果：2档以太超流<BR>追加效果：毁绝预备<BR>持续时间：60秒<BR>与能量吸收共享复唱时间", 
      change: "AOE版能量吸收"
   }, 
   {
      name: "毁荡", 
      ndes: "", 
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Summoner/Action_20.png", 
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/ZwJFxv3XnfqB5N6tKbgXKnj6BU.png", 
      tname: "召唤师", 
      ticon: "", 
      lvl: "Lv54", 
      classification: "魔法", 
      cast: "1.5秒", 
      recast: "2.5秒", 
      cost: "魔力200", 
      distant: "25", 
      range:0, 
      content: "对目标发动无属性魔法攻击　威力：310", 
      change: "威力上调，咏唱时间改为1.5秒"
   }, 
   {
      name: "龙神附体", 
      ndes: "", 
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Summoner/Action_22.png", 
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/ZwJFxv3XnfqB5N6tKbgXKnj6BU.png", 
      tname: "召唤师", 
      ticon: "", 
      lvl: "Lv58", 
      classification: "魔法", 
      cast: "即时", 
      recast: "60秒", 
      cost: "-", 
      distant:0, 
      range:0, 
      content: "进入龙神附体状态<BR>持续时间：15秒<BR>追加效果：毁荡和三重灾祸会分别变为星极脉冲和星极核爆<BR>追加效果：对自身附加红宝石奥秘、绿宝石奥秘、黄宝石奥秘状态<BR>发动条件：自身处于战斗状态且宝石兽处于同行状态", 
      change: "重做为以太充能上位技能，龙神召唤的下位技能。<BR>与龙神召唤类似于目前72级不死鸟附体与80级不死鸟召唤的关系<BR>技能说明持续时间为20秒，但实机演示以及技能循环推测应为15秒"
   }, 
   {
      name: "Astral Impulse<BR>星极脉冲", 
      ndes: "", 
      pic: "../../assets/SMN/星极脉冲.png", 
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/ZwJFxv3XnfqB5N6tKbgXKnj6BU.png", 
      tname: "召唤师", 
      ticon: "", 
      lvl: "Lv58", 
      classification: "魔法", 
      cast: "即时", 
      recast: "2.5秒", 
      cost: "魔力200", 
      distant: "25", 
      range:0, 
      content: "对目标发动无属性魔法攻击　威力：430<BR>发动条件：龙神附体状态中<BR><BR>※该技能无法设置到热键栏", 
      change: "龙神附体下替换毁荡的瞬发高伤单体技能"
   }, 
   {
      name: "Astral Flare<BR>星极核爆", 
      ndes: "", 
      pic: "../../assets/SMN/星极核爆.png", 
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/ZwJFxv3XnfqB5N6tKbgXKnj6BU.png", 
      tname: "召唤师", 
      ticon: "", 
      lvl: "Lv58", 
      classification: "魔法", 
      cast: "即时", 
      recast: "2.5秒", 
      cost: "魔力300", 
      distant: "25", 
      range: "5", 
      content: "对目标及其周围的敌人发动无属性范围魔法攻击　威力：180<BR>发动条件：龙神附体状态中<BR><BR>※该技能无法设置到热键栏", 
      change: "龙神附体下替换三重灾祸的瞬发高伤AOE技能"
   }, 
   {
      name: "Astral Flow<BR>星极超流", 
      ndes: "", 
      pic: "../../assets/SMN/星极超流.png", 
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/ZwJFxv3XnfqB5N6tKbgXKnj6BU.png", 
      tname: "召唤师", 
      ticon: "", 
      lvl: "Lv60", 
      classification: "魔法", 
      cast: "即时", 
      recast: "2.5秒", 
      cost: "-", 
      distant: 0, 
      range:0, 
      content: "根据自身以太和附体发动对应技能<BR>龙神附体状态下：变为死星核爆<BR>不死鸟附体状态下：变为再生之炎<BR>深红旋风预备状态下：变为深红旋风<BR>山崩预备状态下：变为山崩<BR>螺旋气流预备状态下：变为螺旋气流", 
      change: "新技能，在不同召唤时替换为不同的技能，用于整合按键"
   }, 
   {
      name: "死星核爆", 
      ndes: "", 
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Summoner/Action_23.png", 
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/ZwJFxv3XnfqB5N6tKbgXKnj6BU.png", 
      tname: "召唤师", 
      ticon: "", 
      lvl: "Lv60", 
      classification: "能力", 
      cast: "即时", 
      recast: "20秒", 
      cost: "-", 
      distant: "25", 
      range: "5", 
      content: "对目标及其周围敌人发动无属性范围魔法攻击　威力：400<BR>攻击复数敌人时，对目标之外的敌人威力降低60%<BR>发动条件：龙神附体状态中<BR><BR>※该技能无法设置到热键栏", 
      change: "星极超流在龙神附体期间的替换技能，发动后不再取消龙神附体状态"
   }, 
   {
      name: "毁绝", 
      ndes: "", 
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Summoner/Action_24.png", 
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/ZwJFxv3XnfqB5N6tKbgXKnj6BU.png", 
      tname: "召唤师", 
      ticon: "", 
      lvl: "Lv62", 
      classification: "魔法", 
      cast: "即时", 
      recast: "2.5秒", 
      cost: "魔力200", 
      distant: "25", 
      range:"5", 
      content: "对目标及其周围敌人发动无属性魔法攻击　威力：400<BR>攻击复数敌人是，对目标之外的敌人威力降低60%<BR>发动条件：毁坏强化状态中<BR>※该技能无法设置到热键栏", 
      change: "重做为AOE技能。<BR>获取方式改为由能量吸收获取，1分钟共计获取1个"
   }, 
   {
      name: "Searing Light<BR>炽热之光", 
      ndes: "", 
      pic: "../../assets/SMN/炽热之光.png", 
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/ZwJFxv3XnfqB5N6tKbgXKnj6BU.png", 
      tname: "召唤师", 
      ticon: "", 
      lvl: "Lv66", 
      classification: "能力", 
      cast: "即时", 
      recast: "120秒", 
      cost: "-", 
      distant:0, 
      range: "0", 
      content: "命令宝石兽发动炽热之光<BR>炽热之光效果：使宝石兽周围的队员攻击造成的伤害提高3%<BR>持续时间：30秒<BR>发动条件：宝石兽处于同行状态", 
      change: "新版灵护"
   }, 
    {
       name: "龙神召唤", 
       ndes: "通过特职任务获得", 
       pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Summoner/Action_29.png", 
       tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/ZwJFxv3XnfqB5N6tKbgXKnj6BU.png", 
       tname: "召唤师", 
       ticon: "", 
       lvl: "Lv70", 
       classification: "魔法", 
       cast: "即时", 
       recast: "60秒", 
       cost: "-", 
       distant:0, 
       range:0, 
       content: "进入龙神附体状态并令亚灵神巴哈姆特显现<BR>持续时间：15秒<BR>召唤后亚灵神巴哈姆特会发动真龙波攻击目标<BR>追加效果：毁荡变为星极脉冲，迸裂变为星极核爆<BR>追加效果：对自身附加红宝石奥秘、绿宝石奥秘、黄宝石奥秘状态<BR>亚灵神巴哈姆特显现时，之前召唤出的召唤兽会被暂时回收，并在显现时间结束后再次出现<BR>发动条件：自身处于战斗状态，且宝石兽处于同行状态", 
       change: "重做为龙神附体上位技能<BR>技能说明持续时间为20秒，但实机演示以及技能循环推测应为15秒"
    }, 
    {
       name: "真龙波", 
       ndes: "", 
       pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Summoner/Action_30.png", 
       tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/ZwJFxv3XnfqB5N6tKbgXKnj6BU.png", 
       tname: "召唤师", 
       ticon: "", 
       lvl: "Lv70", 
       classification: "魔法", 
       cast: "即时", 
       recast: "1.5秒", 
       cost: "-", 
       distant: "100", 
       range:0, 
       content: "对目标发动无属性魔法攻击　威力：150<BR>发动条件：亚灵神巴哈姆特显现中<BR><BR>※该技能无法设置到热键栏", 
       change: "改为全自动触发<BR>但不清楚死亡轮回是否会影响触发次数<BR>暂不可知是否还存在召唤兽系数"
    }, 
    {
       name: "龙神迸发", 
       ndes: "", 
       pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Summoner/Action_31.png", 
       tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/ZwJFxv3XnfqB5N6tKbgXKnj6BU.png", 
       tname: "召唤师", 
       ticon: "", 
       lvl: "Lv70", 
       classification: "能力", 
       cast: "即时", 
       recast: "8秒", 
       cost: "-", 
       distant: "25", 
       range:0, 
       content: "命令显现的亚灵神巴哈姆特发动死亡轮回<BR>发动条件：亚灵神巴哈姆特显现中<BR>与不死鸟迸发共享复唱时间", 
       change: "CD修改为8秒，使在15秒巴哈期间可以使用两次"
    }, 
    {
       name: "死亡轮回", 
       ndes: "", 
       pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Summoner/Action_32.png", 
       tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/ZwJFxv3XnfqB5N6tKbgXKnj6BU.png", 
       tname: "召唤师", 
       ticon: "", 
       lvl: "Lv70", 
       classification: "能力", 
       cast: "即时", 
       recast: "-", 
       cost: "-", 
       distant: "100", 
       range: "5", 
       content: "对目标及其周围敌人发动无属性范围魔法攻击　威力：650<BR>攻击复数敌人时，对目标之外的敌人威力降低60%<BR>发动条件：亚灵神巴哈姆特显现中<BR><BR>※该技能无法设置到热键栏", 
       change: "暂不可知是否还存在召唤兽系数"
    },, 
    {
       name: "Ruby Rite<BR>红宝石之仪", 
       ndes: "", 
       pic: "../../assets/SMN/红宝石之仪.png", 
       tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/ZwJFxv3XnfqB5N6tKbgXKnj6BU.png", 
       tname: "召唤师", 
       ticon: "", 
       lvl: "Lv72", 
       classification: "能力", 
       cast: "2.8秒", 
       recast: "2.5秒", 
       cost: "「火属性以太」 1", 
       distant:"25", 
       range: 0, 
       content: "对目标发动火属性魔法攻击　威力：430<BR>发动条件：火属性以太<BR><BR>※该技能无法设置到热键栏", 
       change: "宝石之光火属性以太下衍生技"
    }, 
    {
       name: "Topaz Rite<BR>黄宝石之仪", 
       ndes: "", 
       pic: "../../assets/SMN/黄宝石之仪.png", 
       tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/ZwJFxv3XnfqB5N6tKbgXKnj6BU.png", 
       tname: "召唤师", 
       ticon: "", 
       lvl: "Lv72", 
       classification: "魔法", 
       cast: "即时", 
       recast: "2.5秒", 
       cost: "「土属性以太」 1", 
       distant:"25", 
       range: 0, 
       content: "对目标发动土属性魔法攻击　威力：330<BR>追加效果：山崩预备<BR>持续时间：永久<BR>山崩预备状态在使用其他属性召唤技能时结束<BR>发动条件：土属性以太<BR><BR>※该技能无法设置到热键栏", 
       change: "宝石之光耀属性以太下衍生技"
    }, 
    {
       name: "Emerald Rite<BR>绿宝石之仪", 
       ndes: "", 
       pic: "../../assets/SMN/绿宝石之灾.png", 
       tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/ZwJFxv3XnfqB5N6tKbgXKnj6BU.png", 
       tname: "召唤师", 
       ticon: "", 
       lvl: "Lv72", 
       classification: "魔法", 
       cast: "即时", 
       recast: "1.5秒", 
       cost: "「风属性以太」 1", 
       distant:"25", 
       range: 0, 
       content: "对目标发动风属性魔法攻击　威力：230<BR>发动条件：风属性以太<BR><BR>※该技能无法设置到热键栏", 
       change: "宝石之光风属性以太下衍生技"
    }, 
    {
       name: "三重灾祸", 
       ndes: "", 
       pic: "../../assets/SMN/三重灾祸.png", 
       tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/ZwJFxv3XnfqB5N6tKbgXKnj6BU.png", 
       tname: "召唤师", 
       ticon: "", 
       lvl: "Lv74", 
       classification: "魔法", 
       cast: "2.5秒", 
       recast: "2.5秒", 
       cost: "魔力300", 
       distant:"25", 
       range: "5", 
       content: "对目标及其周围敌人发动无属性魔法攻击　威力：120", 
       change: "迸裂上位技能"
    },  
    {
       name: "不死鸟召唤", 
       ndes: "", 
       pic: "../../assets/SMN/不死鸟召唤.png", 
       tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/ZwJFxv3XnfqB5N6tKbgXKnj6BU.png", 
       tname: "召唤师", 
       ticon: "", 
       lvl: "Lv80", 
       classification: "魔法", 
       cast: "即时", 
       recast: "60秒", 
       cost: "-", 
       distant:0, 
       range:0, 
       content: "进入不死鸟附体状态并令亚灵神不死鸟显现<BR>持续时间：15秒<BR>亚灵神不死鸟显现时发动不死鸟之翼<BR>另外，召唤后亚灵神不死鸟会发动赤炎攻击目标<BR>追加效果：毁荡变为灵泉之炎，三重灾祸变为炼狱之炎<BR>追加效果：对自身附加红宝石奥秘、绿宝石奥秘、黄宝石奥秘状态<BR>发动条件：自身处于战斗状态，且宝石兽处于同行状态<BR>亚灵神不死鸟显现时，之前召唤出的宝石兽会被暂时回收，并在显现时间结束后再次出现<BR><BR>※该技能无法设置到热键栏", 
       change: "重做，不死鸟期间不再需要交替使用灵泉之炎与炼狱之炎，仅区分单体与AOE<BR>技能说明持续时间为20秒，但实机演示以及技能循环推测应为15秒"
    }, 
    {
       name: "灵泉之炎", 
       ndes: "", 
       pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Summoner/Action_34.png", 
       tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/ZwJFxv3XnfqB5N6tKbgXKnj6BU.png", 
       tname: "召唤师", 
       ticon: "", 
       lvl: "Lv80", 
       classification: "魔法", 
       cast: "即时", 
       recast: "2.5秒", 
       cost: "魔力200", 
       distant: "25", 
       range:0, 
       content: "对目标发动火属性魔法攻击　威力：430<BR>发动条件：不死鸟附体状态中<BR><BR>※该技能无法设置到热键栏", 
       change: "重做为单独的单体技能，不在为连击"
    }, 
    {
       name: "炼狱之炎", 
       ndes: "", 
       pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Summoner/Action_35.png", 
       tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/ZwJFxv3XnfqB5N6tKbgXKnj6BU.png", 
       tname: "召唤师", 
       ticon: "", 
       lvl: "Lv80", 
       classification: "魔法", 
       cast: "即时", 
       recast: "2.5秒", 
       cost: "魔力300", 
       distant: "25", 
       range: "8", 
       content: "对目标及其周围敌人发动火属性魔法攻击　威力：180<BR>发动条件：不死鸟附体状态中<BR><BR>※该技能无法设置到热键栏", 
       change: "重做为单独的AOE技能，不在为连击"
    }, 
    {
       name: "Rekindle<BR>再生之炎", 
       ndes: "", 
       pic: "../../assets/SMN/再生之炎.png", 
       tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/ZwJFxv3XnfqB5N6tKbgXKnj6BU.png", 
       tname: "召唤师", 
       ticon: "", 
       lvl: "Lv80", 
       classification: "能力", 
       cast: "即时", 
       recast: "20秒", 
       cost: "-", 
       distant:"30", 
       range: 0, 
       content: "持续恢复周围队员的体力<BR>恢复力：100　持续时间：21秒<BR><BR>※该技能无法设置到热键栏", 
       change: "星极超流在不死鸟附体期间的替换技能，学习不死鸟召唤后习得"
    }, 
    {
       name: "不死鸟之翼", 
       ndes: "", 
       pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Summoner/Action_37.png", 
       tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/ZwJFxv3XnfqB5N6tKbgXKnj6BU.png", 
       tname: "召唤师", 
       ticon: "", 
       lvl: "Lv80", 
       classification: "能力", 
       cast: "即时", 
       recast: "-", 
       cost: "-", 
       distant:0, 
       range: "15", 
       content: "持续恢复周围队员的体力<BR>恢复力：100　持续时间：21秒<BR><BR>※该技能无法设置到热键栏", 
       change: "暂不可知是否还存在召唤兽系数"
    }, 
    {
       name: "赤焰", 
       ndes: "", 
       pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Summoner/Action_38.png", 
       tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/ZwJFxv3XnfqB5N6tKbgXKnj6BU.png", 
       tname: "召唤师", 
       ticon: "", 
       lvl: "Lv80", 
       classification: "魔法", 
       cast: "即时", 
       recast: "1.5秒", 
       cost: "-", 
       distant: "100", 
       range:0, 
       content: "对目标发动火属性魔法攻击　威力：150<BR>发动条件：亚灵神不死鸟显现中<BR><BR>※该技能无法设置到热键栏", 
       change: "改为全自动触发,但不清楚天启是否会影响触发次数,暂不可知是否还存在召唤兽系数"
    }, 
    {
       name: "不死鸟迸发", 
       ndes: "", 
       pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Summoner/Action_36.png", 
       tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/ZwJFxv3XnfqB5N6tKbgXKnj6BU.png", 
       tname: "召唤师", 
       ticon: "", 
       lvl: "Lv80", 
       classification: "能力", 
       cast: "即时", 
       recast: "8秒", 
       cost: "-", 
       distant: "25", 
       range:0, 
       content: "命令显现的亚灵神不死鸟发动天启<BR>发动条件：亚灵神不死鸟显现中<BR>满足发动条件后，龙神迸发变为不死鸟迸发<BR>与龙神迸发共享复唱时间<BR><BR>※该技能无法设置到热键栏", 
       change: "CD修改为8秒，使在15秒不死鸟期间可以使用两次"
    }, 
    {
       name: "天启", 
       ndes: "", 
       pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Summoner/Action_39.png", 
       tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/ZwJFxv3XnfqB5N6tKbgXKnj6BU.png", 
       tname: "召唤师", 
       ticon: "", 
       lvl: "Lv80", 
       classification: "能力", 
       cast: "即时", 
       recast: "-", 
       cost: "-", 
       distant: "100", 
       range: "5", 
       content: "对目标及其周围的敌人发动火属性范围魔法攻击　威力：650<BR>攻击复数敌人时，对目标之外的敌人威力降低60%<BR>发动条件：亚灵神不死鸟显现中<BR><BR>※该技能无法设置到热键栏", 
       change: "暂不可知是否还存在召唤兽系数"
    }, 
    {
       name: "Ruby Catastrophe<BR>红宝石之灾", 
       ndes: "", 
       pic: "../../assets/SMN/红宝石之灾.png", 
       tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/ZwJFxv3XnfqB5N6tKbgXKnj6BU.png", 
       tname: "召唤师", 
       ticon: "", 
       lvl: "Lv82", 
       classification: "能力", 
       cast: "2.8秒", 
       recast: "2.5秒", 
       cost: "「火属性以太」 1", 
       distant:"25", 
       range: 0, 
       content: "对目标及其周围敌人发动火属性范围魔法攻击　威力：180<BR>发动条件：火属性以太<BR><BR>※该技能无法设置到热键栏", 
       change: "宝石之耀火属性以太下衍生技"
    }, 
    {
       name: "Topaz Catastrophe<BR>黄宝石之灾", 
       ndes: "", 
       pic: "../../assets/SMN/黄宝石之灾.png", 
       tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/ZwJFxv3XnfqB5N6tKbgXKnj6BU.png", 
       tname: "召唤师", 
       ticon: "", 
       lvl: "Lv82", 
       classification: "魔法", 
       cast: "即时", 
       recast: "2.5秒", 
       cost: "「土属性以太」 1", 
       distant:"25", 
       range: 0, 
       content: "对目标及其周围敌人发动土属性范围魔法攻击　威力：140<BR>追加效果：山崩预备<BR>持续时间：永久<BR>山崩预备状态在使用其他属性召唤技能时结束<BR>发动条件：土属性以太<BR><BR>※该技能无法设置到热键栏", 
       change: "宝石之耀土属性以太下衍生技"
    }, 
    {
       name: "Emerald Catastrophe<BR>绿宝石之灾", 
       ndes: "", 
       pic: "../../assets/SMN/绿宝石之灾.png", 
       tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/ZwJFxv3XnfqB5N6tKbgXKnj6BU.png", 
       tname: "召唤师", 
       ticon: "", 
       lvl: "Lv82", 
       classification: "魔法", 
       cast: "即时", 
       recast: "1.5秒", 
       cost: "「风属性以太」 1", 
       distant:"25", 
       range: 0, 
       content: "对目标及其周围敌人发动风属性范围魔法攻击　威力：100<BR>发动条件：风属性以太<BR><BR>※该技能无法设置到热键栏", 
       change: "宝石之耀风属性以太下衍生技"
    }, 
    {
       name: "深红旋风", 
       ndes: "", 
       pic: "../../assets/SMN/深红旋风.png", 
       tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/ZwJFxv3XnfqB5N6tKbgXKnj6BU.png", 
       tname: "召唤师", 
       ticon: "", 
       lvl: "Lv86", 
       classification: "魔法", 
       cast: "即时", 
       recast: "2.5秒", 
       cost: "-", 
       distant:"25", 
       range: "5", 
       content: "冲向目标并对目标及其周围敌人造成火属性范围魔法攻击  威力：430<BR>攻击复数目标时，对目标之外的敌人威力降低65%<BR>发动条件：深红旋风预备状态中<BR>止步状态下无法发动<BR><BR>※该技能无法设置到热键栏", 
       change: "星极超流在深红旋风预备状态下的替换技能，带有突进效果，与深红打击为2连击"
    }, 
    {
       name: "Crimson Strike<BR>深红强袭", 
       ndes: "", 
       pic: "../../assets/SMN/深红强袭.png", 
       tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/ZwJFxv3XnfqB5N6tKbgXKnj6BU.png", 
       tname: "召唤师", 
       ticon: "", 
       lvl: "Lv86", 
       classification: "魔法", 
       cast: "即时", 
       recast: "2.5秒", 
       cost: "-", 
       distant:"3", 
       range: "5", 
       content: "对目标及其周围敌人造成火属性范围魔法攻击　威力：430<BR>攻击复数敌人时，对目标之外的敌人威力降低65%<BR>连击条件：深红旋风<BR><BR>※该技能无法设置到热键栏", 
       change: "近战第二连"
    }, 
    {
       name: "山崩", 
       ndes: "", 
       pic: "../../assets/SMN/山崩.png", 
       tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/ZwJFxv3XnfqB5N6tKbgXKnj6BU.png", 
       tname: "召唤师", 
       ticon: "", 
       lvl: "Lv86", 
       classification: "能力", 
       cast: "即时", 
       recast: "1秒", 
       cost: "-", 
       distant:"25", 
       range: "5", 
       content: "对目标及其周围敌人造成土属性范围魔法攻击  威力：150<BR>攻击复数目标时，对目标之外的敌人威力降低70%<BR>发动条件：山崩预备状态中<BR><BR>※该技能无法设置到热键栏", 
       change: "星极超流在山崩预备状态下的替换技能"
    }, 
    {
       name: "螺旋气流", 
       ndes: "", 
       pic: "../../assets/SMN/螺旋气流.png", 
       tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/ZwJFxv3XnfqB5N6tKbgXKnj6BU.png", 
       tname: "召唤师", 
       ticon: "", 
       lvl: "Lv86", 
       classification: "魔法", 
       cast: "即时", 
       recast: "3秒", 
       cost: "3.5秒", 
       distant:"25", 
       range: 0, 
       content: "对目标及其周围敌人造成风属性范围魔法攻击  威力：430<BR>攻击复数目标时，对目标之外的敌人威力降低65%<BR>追加效果：以目标为中心产生伤害区域<BR>威力：30　持续时间：12秒<BR>发动条件：螺旋气流预备状态中<BR><BR>※该技能无法设置到热键栏", 
       change: "星极超流在螺旋气流预备状态下的替换技能"
    }, 
    {
       name: "Summon Ifrit II<BR>火神召唤II", 
       ndes: "", 
       pic: "../../assets/SMN/火神召唤II.png", 
       tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/ZwJFxv3XnfqB5N6tKbgXKnj6BU.png", 
       tname: "召唤师", 
       ticon: "", 
       lvl: "Lv90", 
       classification: "魔法", 
       cast: "即时", 
       recast: "2.5秒", 
       cost: "-", 
       distant:"25", 
       range: 0, 
       content: "召唤火神伊芙利特，令其发动地狱之火炎<BR>对目标及其周围敌人造成火属性范围魔法伤害  威力：700<BR>攻击复数敌人时，对目标之外的敌人威力降低60%<BR>追加效果：2档火属性以太<BR>火属性以太效果：宝石之光和宝石之耀变为火属性魔法<BR>持续时间：30秒<BR>追加效果：深红旋风预备<BR>持续时间：永久<BR>深红旋风可用状态在使用其他属性召唤技能时结束<BR>发动条件：红宝石奥秘，且宝石兽处于同行状态<BR>不能在自身附加了土属性以太或风属性以太时使用", 
       change: "新技能，上位替换火神召唤"
    }, 
    {
      name: "Summon Ifrit II<BR>土神召唤II", 
      ndes: "", 
      pic: "../../assets/SMN/土神召唤II.png", 
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/ZwJFxv3XnfqB5N6tKbgXKnj6BU.png", 
      tname: "召唤师", 
      ticon: "", 
      lvl: "Lv90", 
      classification: "魔法", 
      cast: "即时", 
      recast: "2.5秒", 
      cost: "-", 
      distant:"25", 
      range: 0, 
      content: "召唤土神泰坦，令其发动大地之怒<BR>对目标及其周围敌人造成土属性范围魔法伤害  威力：700<BR>攻击复数敌人时，对目标之外的敌人威力降低60%<BR>追加效果：4档土属性以太<BR>土属性以太效果：宝石之光和宝石之耀变为土属性魔法<BR>持续时间：30秒<BR>发动条件：黄宝石奥秘，且宝石兽处于同行状态<BR>不能在自身附加了火属性以太或风属性以太时使用", 
      change: "新技能，上位替换土神召唤"
    }, 
    {
      name: "Summon Titan II<BR>风神召唤II", 
      ndes: "", 
      pic: "../../assets/SMN/风神召唤II.png", 
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/ZwJFxv3XnfqB5N6tKbgXKnj6BU.png", 
      tname: "召唤师", 
      ticon: "", 
      lvl: "Lv90", 
      classification: "魔法", 
      cast: "即时", 
      recast: "2.5秒", 
      cost: "-", 
      distant:"25", 
      range: 0, 
      content: "召唤风神迦楼罗，令其发动大气爆发<BR>对目标及其周围敌人造成风属性范围魔法伤害  威力：700<BR>攻击复数敌人时，对目标之外的敌人威力降低60%<BR>追加效果：4档风属性以太<BR>风属性以太效果：宝石之光和宝石之耀变为风属性魔法<BR>持续时间：30秒<BR>追加效果：螺旋气流预备<BR>持续时间：永久<BR>螺旋气流可用状态在使用其他属性召唤技能时结束<BR>发动条件：绿宝石奥秘，且宝石兽处于同行状态<BR>不能在自身附加了火属性以太或土属性以太时使用", 
      change: "新技能，上位替换风神召唤"
    }
];

  roleSkills: any[] = [
   {
       name: "昏乱", 
       ndes: "", 
       pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Magical Ranged DPS Role Action_01.png", 
       tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/8Dnf8Wy9IyxIt21y6lrE5atKt0.png", 
       tname: "远程魔法职业", 
       ticon: [
         {
           "url": "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/8Dnf8Wy9IyxIt21y6lrE5atKt0.png", 
           tname: "远程魔法职业"
         }
       ], 
       lvl: "Lv8", 
       classification: "能力", 
       cast: "即时", 
       recast: "90秒", 
       cost: "-", 
       distant: "25", 
       range: 0, 
       content: "一定时间内，令目标的物理伤害降低5%，魔法伤害降低10% <BR>持续时间：10秒", 
       change: "效果从「令目标的智力与精神降低10% 」变更为「令目标的物理伤害降低5%，魔法伤害降低10% 」"
   }, 
   {
       name: "催眠", 
       ndes: "", 
       pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Action_05.png", 
       tiurl: "", 
       tname: "", 
       ticon: [
           {
               "url": "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/8Dnf8Wy9IyxIt21y6lrE5atKt0.png", 
               tname: "远程魔法职业"
           }
       ], 
       lvl: "Lv10", 
       classification: "魔法", 
       cast: "2.5秒", 
       recast: "2.5秒", 
       cost: "800", 
       distant: 30, 
       range: 5, 
       content: "令目标及其周围的敌人陷入睡眠状态<BR>持续时间：30秒<BR>发动之后会停止自动攻击", 
       change: "新增特性"
   }, 
   {
       name: "即刻咏唱", 
       ndes: "", 
       pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Magical Ranged DPS Role Action_02.png", 
       tiurl: "", 
       tname: "", 
       ticon: [
           {
               "url": "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/V5xx3kfnREBO-2xWbTUW2Csy_Q.png", 
               tname: "治疗职业"
           }, 
           {
               "url": "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/8Dnf8Wy9IyxIt21y6lrE5atKt0.png", 
               tname: "远程魔法职业"
           }
       ], 
       lvl: "Lv18", 
       classification: "能力", 
       cast: "即时", 
       recast: "60秒", 
       cost: "-", 
       distant: 0, 
       range: 0, 
       content: "一定时间内，下次咏唱的魔法没有任何咏唱时间<BR>持续时间：10秒", 
       change: ""
   }, 
   {
       name: "醒梦", 
       ndes: "", 
       pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Magical Ranged DPS Role Action_03.png", 
       tiurl: "", 
       tname: "", 
       ticon: [
           {
               "url": "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/V5xx3kfnREBO-2xWbTUW2Csy_Q.png", 
               tname: "治疗职业"
           }, 
           {
               "url": "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/8Dnf8Wy9IyxIt21y6lrE5atKt0.png", 
               tname: "远程魔法职业"
           }
       ], 
       lvl: "Lv24", 
       classification: "能力", 
       cast: "即时", 
       recast: "60秒", 
       cost: "-", 
       distant: 0, 
       range: 0, 
       content: "持续恢复自身魔力<BR>效果量：50　持续时间：21秒", 
       change: ""
   }, 
   {
       name: "沉稳咏唱", 
       ndes: "", 
       pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Magical Ranged DPS Role Action_04.png", 
       tiurl: "", 
       tname: "", 
       ticon: [
           {
               "url": "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/V5xx3kfnREBO-2xWbTUW2Csy_Q.png", 
               tname: "治疗职业"
           }, 
           {
               "url": "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/8Dnf8Wy9IyxIt21y6lrE5atKt0.png", 
               tname: "远程魔法职业"
           }
       ], 
       lvl: "Lv44", 
       classification: "能力", 
       cast: "即时", 
       recast: "120秒", 
       cost: "-", 
       distant: 0, 
       range: 0, 
       content: "一定时间内，咏唱的魔法不会被任何妨碍打断<BR>同时，令除特定攻击之外其他所有击退与吸引效果失效<BR>持续时间：6秒", 
       change: ""
   }
];



  traits: any[] = [
   {
      name: "以太充能效果提高", 
      ndes: "", 
      pic: "../../assets/SMN/以太充能效果提高.png", 
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/_3v-EDzckpsEC39oe0t4A8pLJk.png", 
      tname: "秘术师", 
      ticon: "", 
      lvl: "Lv15", 
      classification: "", 
      cast: "", 
      recast: "", 
      cost: "", 
      distant: "", 
      range: "", 
      content: "为自身附加红宝石奥秘、黄宝石奥秘状态<BR>发动条件：发动以太充能时", 
      change: ""
   },
   {
       name: "技能效果提高", 
       ndes: "", 
       pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Summoner/Trait_01.png", 
       tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/_3v-EDzckpsEC39oe0t4A8pLJk.png", 
       tname: "秘术师", 
       ticon: "", 
       lvl: "Lv20", 
       classification: "", 
       cast: "", 
       recast: "", 
       cost: "", 
       distant: "", 
       range: "", 
       content: "除自动攻击外的技能造成的伤害提高至基本值的1.1倍，恢复技能的恢复量也提高至基本值的1.1倍", 
       change: ""
    }, 
    {
      name: "以太充能效果提高II", 
      ndes: "", 
      pic: "../../assets/SMN/以太充能效果提高II.png", 
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/_3v-EDzckpsEC39oe0t4A8pLJk.png", 
      tname: "秘术师", 
      ticon: "", 
      lvl: "Lv22", 
      classification: "", 
      cast: "", 
      recast: "", 
      cost: "", 
      distant: "", 
      range: "", 
      content: "为自身附加红宝石奥秘、黄宝石奥秘、绿宝石奥秘状态<BR>发动条件：发动以太充能时", 
      change: ""
   },
   {
      name: "毁灭变为毁坏", 
      ndes: "", 
      pic: "../../assets/SMN/毁灭变为毁坏.png", 
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/_3v-EDzckpsEC39oe0t4A8pLJk.png", 
      tname: "秘术师", 
      ticon: "", 
      lvl: "Lv30", 
      classification: "", 
      cast: "", 
      recast: "", 
      cost: "", 
      distant: "", 
      range: "", 
      content: "毁灭变为毁坏", 
      change: ""
   },
   {
      name: "红宝石兽召唤精通", 
      ndes: "", 
      pic: "../../assets/SMN/.png", 
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/_3v-EDzckpsEC39oe0t4A8pLJk.png", 
      tname: "召唤师", 
      ticon: "", 
      lvl: "Lv30", 
      classification: "", 
      cast: "", 
      recast: "", 
      cost: "", 
      distant: "", 
      range: "", 
      content: "红宝石兽召唤变为火神召唤", 
      change: ""
   }, 
   {
      name: "黄宝石兽召唤精通", 
      ndes: "", 
      pic: "../../assets/SMN/黄宝石兽召唤精通.png", 
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/_3v-EDzckpsEC39oe0t4A8pLJk.png", 
      tname: "召唤师", 
      ticon: "", 
      lvl: "Lv35", 
      classification: "", 
      cast: "", 
      recast: "", 
      cost: "", 
      distant: "", 
      range: "", 
      content: "黄宝石兽召唤变为土神召唤", 
      change: ""
   },
    {
       name: "技能效果提高II", 
       ndes: "", 
       pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Summoner/Trait_03.png", 
       tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/_3v-EDzckpsEC39oe0t4A8pLJk.png", 
       tname: "秘术师", 
       ticon: "", 
       lvl: "Lv40", 
       classification: "", 
       cast: "", 
       recast: "", 
       cost: "", 
       distant: "", 
       range: "", 
       content: "除自动攻击外的技能造成的伤害提高至基本值的1.3倍，恢复技能的恢复量也提高至基本值的1.3倍", 
       change: ""
    }, 
    {
       name: "绿宝石兽召唤精通", 
       ndes: "", 
       pic: "../../assets/SMN/绿宝石兽召唤精通.png", 
       tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/_3v-EDzckpsEC39oe0t4A8pLJk.png", 
       tname: "召唤师", 
       ticon: "", 
       lvl: "Lv45", 
       classification: "", 
       cast: "", 
       recast: "", 
       cost: "", 
       distant: "", 
       range: "", 
       content: "绿宝石兽召唤变为风神召唤", 
       change: ""
    },
    {
       name: "内力迸发", 
       ndes: "", 
       pic: "../../assets/SMN/内力迸发.png", 
       tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/_3v-EDzckpsEC39oe0t4A8pLJk.png", 
       tname: "召唤师", 
       ticon: "", 
       lvl: "Lv50", 
       classification: "", 
       cast: "", 
       recast: "", 
       cost: "", 
       distant: "", 
       range: "", 
       content: "火神召唤、土神召唤、风神召唤的召唤兽发动的技能产生变化<BR>伊弗利特之灵：燃火强袭变为地狱之火炎<BR>泰坦之灵：碎岩变为大地之怒<BR>迦楼罗之灵：大气风斩变为大气爆发", 
       change: ""
    },
    {
      name: "毁灭精通II", 
      ndes: "", 
      pic: "../../assets/SMN/毁灭精通II.png", 
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/_3v-EDzckpsEC39oe0t4A8pLJk.png", 
      tname: "召唤师", 
      ticon: "", 
      lvl: "Lv54", 
      classification: "", 
      cast: "", 
      recast: "", 
      cost: "", 
      distant: "", 
      range: "", 
      content: "毁坏变为毁荡", 
      change: ""
    },
    {
       name: "以太充能精通", 
       ndes: "", 
       pic: "../../assets/SMN/以太充能精通.png", 
       tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/_3v-EDzckpsEC39oe0t4A8pLJk.png", 
       tname: "召唤师", 
       ticon: "", 
       lvl: "Lv58", 
       classification: "", 
       cast: "", 
       recast: "", 
       cost: "", 
       distant: "", 
       range: "", 
       content: "以太充能变为龙神附体", 
       change: ""
    },
    {
       name: "能量抽取效果提高", 
       ndes: "", 
       pic: "../../assets/SMN/能量抽取效果提高.png", 
       tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/_3v-EDzckpsEC39oe0t4A8pLJk.png", 
       tname: "召唤师", 
       ticon: "", 
       lvl: "Lv62", 
       classification: "", 
       cast: "", 
       recast: "", 
       cost: "", 
       distant: "", 
       range: "", 
       content: "为自身附加毁绝预备状态<BR>发动条件：发动能量吸收和能量抽取时", 
       change: ""
    },
    {
       name: "龙神附体效果提高", 
       ndes: "通过特职任务获得", 
       pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Summoner/Trait_08.png", 
       tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/ZwJFxv3XnfqB5N6tKbgXKnj6BU.png", 
       tname: "召唤师", 
       ticon: "", 
       lvl: "Lv70", 
       classification: "", 
       cast: "", 
       recast: "", 
       cost: "", 
       distant: "", 
       range: "", 
       content: "自身附体深度加深1档<BR>发动条件：龙神附体状态结束时", 
       change: ""
    },
    {
       name: "毁灭精通III", 
       ndes: "", 
       pic: "../../assets/SMN/毁灭精通III.png", 
       tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/_3v-EDzckpsEC39oe0t4A8pLJk.png", 
       tname: "召唤师", 
       ticon: "", 
       lvl: "Lv72", 
       classification: "", 
       cast: "", 
       recast: "", 
       cost: "", 
       distant: "", 
       range: "", 
       content: "宝石之光根据自身以太效果发动对应技能<BR>火属性以太时效果：变为红宝石之仪<BR>土属性以太时效果：变为黄宝石之仪<BR>风属性以太时效果：变为绿宝石之仪", 
       change: ""
    },
    {
       name: "迸裂精通", 
       ndes: "", 
       pic: "../../assets/SMN/迸裂精通.png", 
       tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/_3v-EDzckpsEC39oe0t4A8pLJk.png", 
       tname: "召唤师", 
       ticon: "", 
       lvl: "Lv74", 
       classification: "", 
       cast: "", 
       recast: "", 
       cost: "", 
       distant: "", 
       range: "", 
       content: "迸裂变为三重灾祸", 
       change: ""
    },
    {
       name: "龙神召唤效果提高", 
       ndes: "", 
       pic: "../../assets/SMN/龙神召唤效果提高.png", 
       tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/_3v-EDzckpsEC39oe0t4A8pLJk.png", 
       tname: "召唤师", 
       ticon: "", 
       lvl: "Lv80", 
       classification: "", 
       cast: "", 
       recast: "", 
       cost: "", 
       distant: "", 
       range: "", 
       content: "龙神召唤变为不死鸟召唤<BR>发动条件：亚灵神巴哈姆特显现结束", 
       change: ""
    },
    {
       name: "迸裂精通II", 
       ndes: "", 
       pic: "../../assets/SMN/迸裂精通II.png", 
       tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/_3v-EDzckpsEC39oe0t4A8pLJk.png", 
       tname: "召唤师", 
       ticon: "", 
       lvl: "Lv82", 
       classification: "", 
       cast: "", 
       recast: "", 
       cost: "", 
       distant: "", 
       range: "", 
       content: "宝石之耀根据自身以太效果产生变化<BR>火属性以太时效果：变为红宝石之灾<BR>土属性以太时效果：变为黄宝石之灾<BR>风属性以太时效果：变为绿宝石之灾", 
       change: ""
    },
    {
       name: "毁灭精通IV", 
       ndes: "", 
       pic: "../../assets/SMN/毁灭精通IV.png", 
       tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/_3v-EDzckpsEC39oe0t4A8pLJk.png", 
       tname: "召唤师", 
       ticon: "", 
       lvl: "Lv84", 
       classification: "", 
       cast: "", 
       recast: "", 
       cost: "", 
       distant: "", 
       range: "", 
       content: "毁荡威力提高到310，红宝石之仪威力提高到430，黄宝石之仪威力提高到330，绿宝石之仪威力提高到230", 
       change: ""
    },
    {
       name: "元素精通", 
       ndes: "", 
       pic: "../../assets/SMN/元素精通.png", 
       tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/_3v-EDzckpsEC39oe0t4A8pLJk.png", 
       tname: "召唤师", 
       ticon: "", 
       lvl: "Lv86", 
       classification: "", 
       cast: "", 
       recast: "", 
       cost: "", 
       distant: "", 
       range: "", 
       content: "星极超流根据自身以太效果产生变化<BR>火属性以太时效果：变为深红旋风<BR>土属性以太时效果：变为山崩<BR>风属性以太时效果：变为螺旋气流", 
       change: ""
    },
    {
       name: "守护之光效果提高", 
       ndes: "", 
       pic: "../../assets/SMN/守护之光效果提高.png", 
       tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/_3v-EDzckpsEC39oe0t4A8pLJk.png", 
       tname: "召唤师", 
       ticon: "", 
       lvl: "Lv88", 
       classification: "", 
       cast: "", 
       recast: "", 
       cost: "", 
       distant: "", 
       range: "", 
       content: "守护之光变为积蓄技能<BR>积蓄次数：2", 
       change: ""
    },
    {
       name: "召唤精通IV", 
       ndes: "", 
       pic: "../../assets/SMN/召唤精通IV.png", 
       tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/_3v-EDzckpsEC39oe0t4A8pLJk.png", 
       tname: "召唤师", 
       ticon: "", 
       lvl: "Lv90", 
       classification: "", 
       cast: "", 
       recast: "", 
       cost: "", 
       distant: "", 
       range: "", 
       content: "火神召唤变为火神召唤II，土神召唤变为土神召唤II，风神召唤变为风神召唤II", 
       change: ""
    }
];

  ngOnInit(): void {
  }

}
