import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-samurai',
  templateUrl: './samurai.component.html',
  styleUrls: ['./samurai.component.css']
})
export class SamuraiComponent implements OnInit {

  constructor() { }

  today: Date = new Date();

  skills: any[] = [
    {
      isDisabled: "false",
      name: "刃风",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Samurai/Action_01.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Ra2GV79gVQhy6SwCrU19boTghc.png",
      tname: "武士",
      ticon: "",
      lvl: "Lv1",
      classification: "战技",
      cast: "即时",
      recast: "2.5秒",
      cost: "-",
      distant: "3",
      range: "0",
      rangeType: "zero",
      content: "对目标发动物理攻击　威力：200<BR>追加效果：获得5点剑气",
      change: "威力从150变更为200。"
    },
    {
      isDisabled: "false",
      name: "阵风",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Samurai/Action_02.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Ra2GV79gVQhy6SwCrU19boTghc.png",
      tname: "武士",
      ticon: "",
      lvl: "Lv4",
      classification: "战技",
      cast: "即时",
      recast: "2.5秒",
      cost: "-",
      distant: "3",
      range: "0",
      rangeType: "zero",
      content: "对目标发动物理攻击　威力：100<BR>连击条件：刃风　连击中威力：320<BR>连击成功：攻击伤害提高13%<BR>持续时间：40秒<BR>连击成功：获得5点剑气",
      change: "连击时威力由340变为320。"
    },
    {
      isDisabled: "false",
      name: "心眼",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Samurai/Action_03.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Ra2GV79gVQhy6SwCrU19boTghc.png",
      tname: "武士",
      ticon: "",
      lvl: "Lv6",
      classification: "能力",
      cast: "即时",
      recast: "15秒",
      cost: "-",
      distant: "0",
      range: "0",
      rangeType: "zero",
      content: "一定时间内，受到的第一次攻击伤害减轻10%<BR>持续时间：3秒<BR>追加效果：成功减轻伤害后对自身附加开眼状态<BR>持续时间：15秒",
      change: ""
    },
    {
      isDisabled: "false",
      name: "燕飞",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Samurai/Action_04.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Ra2GV79gVQhy6SwCrU19boTghc.png",
      tname: "武士",
      ticon: "",
      lvl: "Lv15",
      classification: "战技",
      cast: "即时",
      recast: "2.5秒",
      cost: "-",
      distant: "15",
      range: "0",
      rangeType: "zero",
      content: "对目标发动远距离物理攻击　威力：100<BR>“燕飞效果提高”状态中威力：320<BR>追加效果：获得10点剑气",
      change: ""
    },
    {
      isDisabled: "false",
      name: "士风",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Samurai/Action_05.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Ra2GV79gVQhy6SwCrU19boTghc.png",
      tname: "武士",
      ticon: "",
      lvl: "Lv18",
      classification: "战技",
      cast: "即时",
      recast: "2.5秒",
      cost: "-",
      distant: "3",
      range: "0",
      rangeType: "zero",
      content: "对目标发动物理攻击　威力：100<BR>连击条件：刃风　连击中威力：320<BR>连击成功：自身的自动攻击间隔、战技与魔法的咏唱及复唱时间缩短13%　持续时间：40秒<BR>连击成功：获得5点剑气",
      change: "连击中威力从340变更为320。"
    },
    {
      isDisabled: "false",
      name: "风雅",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Samurai/Action_06.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Ra2GV79gVQhy6SwCrU19boTghc.png",
      tname: "武士",
      ticon: "",
      lvl: "Lv26",
      classification: "战技",
      cast: "即时",
      recast: "2.5秒",
      cost: "-",
      distant: "8",
      range: "8",
      rangeType: "zero",
      content: "向目标所在方向发出扇形范围物理攻击　威力：100<BR>追加效果：获得5点剑气",
      change: "距离与范围由6m变为8m<br>扇形范围的角度扩大。"
    },
    {
      isDisabled: "false",
      name: "月光",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Samurai/Action_07.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Ra2GV79gVQhy6SwCrU19boTghc.png",
      tname: "武士",
      ticon: "",
      lvl: "Lv30",
      classification: "战技",
      cast: "即时",
      recast: "2.5秒",
      cost: "-",
      distant: "3",
      range: "0",
      rangeType: "zero",
      content: "对目标发动物理攻击　威力：100<BR>连击条件：阵风　连击中威力：480<BR>连击中背面攻击追加效果：获得5点剑气<BR>连击成功：获得月之闪与5点剑气",
      change: "连击中威力从440变更为480。"
    },
    {
      isDisabled: "false",
      name: "居合术",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Samurai/Action_08.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Ra2GV79gVQhy6SwCrU19boTghc.png",
      tname: "武士",
      ticon: "",
      lvl: "Lv30",
      classification: "战技",
      cast: "1.3秒",
      recast: "2.5秒",
      cost: "「闪」全部",
      distant: "0",
      range: "0",
      rangeType: "zero",
      content: "根据闪的数量发动居合术<BR>1闪：彼岸花<BR>2闪：天下五剑<BR>3闪：纷乱雪月花",
      change: "咏唱时间从1.8秒变更为1.3秒。"
    },
    {
      isDisabled: "false",
      name: "满月",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Samurai/Action_09.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Ra2GV79gVQhy6SwCrU19boTghc.png",
      tname: "武士",
      ticon: "",
      lvl: "Lv35",
      classification: "战技",
      cast: "即时",
      recast: "2.5秒",
      cost: "-",
      distant: "0",
      range: "5",
      rangeType: "zero",
      content: "对自身周围的敌人发动范围物理攻击　威力：100<BR>连击条件：风雅　连击中威力：160<BR>连击成功：阵风的持续时间延长15秒<BR>最多可延长至40秒<BR>连击成功：获得月之闪与10点剑气",
      change: "删除“攻击复数目标时，每多1目标，对该目标威力降低10%，最低降为50%。<br>连击成功时上升的威力不受到影响”。<br>连击中威力从200变更为160。<br>新增“连击成功：阵风的持续时间延长15秒<br>最多可延长至40秒”。"
    },
    {
      isDisabled: "false",
      name: "花车",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Samurai/Action_10.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Ra2GV79gVQhy6SwCrU19boTghc.png",
      tname: "武士",
      ticon: "",
      lvl: "Lv40",
      classification: "战技",
      cast: "即时",
      recast: "2.5秒",
      cost: "-",
      distant: "3",
      range: "0",
      rangeType: "zero",
      content: "对目标发动物理攻击　威力：100<BR>连击条件：士风　连击中威力：480<BR>连击中侧面攻击追加效果：获得5点剑气<BR>连击成功：获得花之闪与5点剑气",
      change: "连击中威力从440变更为480。"
    },
    {
      isDisabled: "false",
      name: "樱花",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Samurai/Action_11.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Ra2GV79gVQhy6SwCrU19boTghc.png",
      tname: "武士",
      ticon: "",
      lvl: "Lv45",
      classification: "战技",
      cast: "即时",
      recast: "2.5秒",
      cost: "-",
      distant: "0",
      range: "5",
      rangeType: "zero",
      content: "对自身周围的敌人发动范围物理攻击　威力：100<BR>连击条件：风雅　连击中威力：160<BR>连击成功：士风的持续时间延长15秒<BR>最多可延长至40秒<BR>连击成功：获得花之闪与10点剑气",
      change: "删除“攻击复数目标时，每多1目标，对该目标威力降低10%，最低降为50%。<br>连击成功时上升的威力不受到影响”。<br>连击中威力从200变更为160。<br>新增“士风的持续时间延长15秒<br>最多可延长至40秒”。"
    },
    {
      isDisabled: "false",
      name: "雪风",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Samurai/Action_12.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Ra2GV79gVQhy6SwCrU19boTghc.png",
      tname: "武士",
      ticon: "",
      lvl: "Lv50",
      classification: "战技",
      cast: "即时",
      recast: "2.5秒",
      cost: "-",
      distant: "3",
      range: "0",
      rangeType: "zero",
      content: "对目标发动物理攻击　威力：100<BR>连击条件：刃风　连击中威力：360<BR>连击成功：获得雪之闪与15点剑气",
      change: "连击中威力从400变更为360。"
    },
    {
      isDisabled: "false",
      name: "明镜止水",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Samurai/Action_13.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Ra2GV79gVQhy6SwCrU19boTghc.png",
      tname: "武士",
      ticon: "",
      lvl: "Lv50",
      classification: "能力",
      cast: "即时",
      recast: "55秒",
      cost: "-",
      distant: "0",
      range: "0",
      rangeType: "zero",
      content: "一定时间内，战技无需连击条件即可连击成功<BR>持续时间结束或发动3次居合术之外的战技后取消该状态　持续时间：15秒",
      change: "状态栏中的效果图标将显示剩余次数"
    },
    {
      isDisabled: "false",
      name: "必杀剑·回天",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Samurai/Action_14.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Ra2GV79gVQhy6SwCrU19boTghc.png",
      tname: "武士",
      ticon: "",
      lvl: "Lv52",
      classification: "能力",
      cast: "即时",
      recast: "1秒",
      cost: "「剑气」20",
      distant: "0",
      range: "0",
      rangeType: "zero",
      content: "效果时间内发动的第1个战技威力提高50%　持续时间：10秒<BR>发动条件：剑气20点",
      change: "复唱时间从5秒变更为1秒。"
    },
    {
      isDisabled: "false",
      name: "必杀剑·晓天",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Samurai/Action_15.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Ra2GV79gVQhy6SwCrU19boTghc.png",
      tname: "武士",
      ticon: "",
      lvl: "Lv54",
      classification: "能力",
      cast: "即时",
      recast: "10秒",
      cost: "「剑气」10",
      distant: "20",
      range: "0",
      rangeType: "zero",
      content: "冲向目标并发动物理攻击　威力：100<BR>发动条件：剑气10点<BR>止步状态下无法发动",
      change: ""
    },
    {
      isDisabled: "false",
      name: "必杀剑·夜天",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Samurai/Action_16.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Ra2GV79gVQhy6SwCrU19boTghc.png",
      tname: "武士",
      ticon: "",
      lvl: "Lv56",
      classification: "能力",
      cast: "即时",
      recast: "10秒",
      cost: "「剑气」10",
      distant: "5",
      range: "0",
      rangeType: "zero",
      content: "对目标发动物理攻击　威力：100<BR>追加效果：后跳10米距离<BR>追加效果：燕飞效果提高<BR>持续时间：15秒<BR>发动条件：剑气10点<BR>止步状态下无法发动",
      change: ""
    },
    {
      isDisabled: "false",
      name: "慈眼",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Samurai/Action_17.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Ra2GV79gVQhy6SwCrU19boTghc.png",
      tname: "武士",
      ticon: "",
      lvl: "Lv58",
      classification: "能力",
      cast: "即时",
      recast: "1秒",
      cost: "-",
      distant: "0",
      range: "0",
      rangeType: "zero",
      content: "恢复自身体力　恢复力：200<BR>发动条件：开眼状态中<BR>与必杀剑·星眼共享复唱时间",
      change: "删除“追加效果：自身仇恨减少20%”。"
    },
    {
      isDisabled: "false",
      name: "默想",
      ndes: "通过特职任务获得",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Samurai/Action_18.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Ra2GV79gVQhy6SwCrU19boTghc.png",
      tname: "武士",
      ticon: "",
      lvl: "Lv60",
      classification: "能力",
      cast: "即时",
      recast: "60秒",
      cost: "-",
      distant: "0",
      range: "0",
      rangeType: "zero",
      content: "进入默想状态持续获得剑气　持续时间：15秒<BR>追加效果：连续叠加剑压状态<BR>最大档数：3档　持续时间：永久<BR>效果时间内发动技能或进行移动、转身都会立即解除默想<BR>发动之后会停止自动攻击<BR>非战斗中无法获得剑气，也不会附加剑压状态,非战斗中无法获得剑气<BR>该能力不仅有单独计算的复唱时间，还会与战技共享复唱时间",
      change: "追加效果由「连续叠加默想深度状态 最大档数：5档　持续时间：45秒」改为「连续叠加剑压状态 最大档数：3档　持续时间：永久」<br>增加「该能力不仅有单独计算的复唱时间，还会与战技共享复唱时间」。"
    },
    {
      isDisabled: "false",
      name: "必杀剑·震天",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Samurai/Action_19.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Ra2GV79gVQhy6SwCrU19boTghc.png",
      tname: "武士",
      ticon: "",
      lvl: "Lv62",
      classification: "能力",
      cast: "即时",
      recast: "1秒",
      cost: "「剑气」25",
      distant: "3",
      range: "0",
      rangeType: "zero",
      content: "对目标发动物理攻击　威力：320<BR>发动条件：剑气25点",
      change: "威力从300变更为320。"
    },
    {
      isDisabled: "false",
      name: "必杀剑·九天",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Samurai/Action_20.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Ra2GV79gVQhy6SwCrU19boTghc.png",
      tname: "武士",
      ticon: "",
      lvl: "Lv64",
      classification: "能力",
      cast: "即时",
      recast: "1秒",
      cost: "「剑气」25",
      distant: "0",
      range: "5",
      rangeType: "zero",
      content: "对自身周围的敌人发动范围物理攻击　威力：150<BR>发动条件：剑气25点",
      change: ""
    },
    {
      isDisabled: "false",
      name: "必杀剑·星眼",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Samurai/Action_21.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Ra2GV79gVQhy6SwCrU19boTghc.png",
      tname: "武士",
      ticon: "",
      lvl: "Lv66",
      classification: "能力",
      cast: "即时",
      recast: "1秒",
      cost: "「剑气」15",
      distant: "3",
      range: "0",
      rangeType: "zero",
      content: "对目标发动物理攻击　威力：220<BR>发动条件：剑气15点<BR>发动条件：开眼状态中<BR>与慈眼共享复唱时间",
      change: "威力从200变更为220。"
    },
    {
      isDisabled: "false",
      name: "叶隐",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Samurai/Action_22.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Ra2GV79gVQhy6SwCrU19boTghc.png",
      tname: "武士",
      ticon: "",
      lvl: "Lv68",
      classification: "能力",
      cast: "即时",
      recast: "5秒",
      cost: "「闪」全部",
      distant: "0",
      range: "0",
      rangeType: "zero",
      content: "将闪转换为剑气<BR>每一道闪可转换10点剑气<BR>发动条件：雪之闪或月之闪或花之闪状态中",
      change: "每一道闪可转换的剑气从5变更为10。"
    },
    {
      isDisabled: "false",
      name: "意气冲天",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Samurai/Action_23.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Ra2GV79gVQhy6SwCrU19boTghc.png",
      tname: "武士",
      ticon: "",
      lvl: "Lv68",
      classification: "能力",
      cast: "即时",
      recast: "60秒",
      cost: "-",
      distant: "0",
      range: "0",
      rangeType: "zero",
      content: "获得50点剑气<BR>发动条件：自身处于战斗状态",
      change: ""
    },
    {
      isDisabled: "false",
      name: "必杀剑·红莲",
      ndes: "通过特职任务获得",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Samurai/Action_24.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Ra2GV79gVQhy6SwCrU19boTghc.png",
      tname: "武士",
      ticon: "",
      lvl: "Lv70",
      classification: "能力",
      cast: "即时",
      recast: "120秒",
      cost: "「剑气」50",
      distant: "10",
      range: "10",
      rangeType: "zero",
      content: "向目标所在方向发出直线范围物理攻击　威力：850<BR>发动条件：剑气50点<BR>与必杀剑·闪影共享复唱时间",
      change: "威力从800变更为850。<br>删除“攻击复数目标时，每多1目标，对该目标威力降低25%，最低降为50%”。<br>新增“与必杀剑·闪影共享复唱时间”。"
    },
    {
      isDisabled: "false",
      name: "必杀剑·闪影",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Samurai/Action_25.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Ra2GV79gVQhy6SwCrU19boTghc.png",
      tname: "武士",
      ticon: "",
      lvl: "Lv72",
      classification: "能力",
      cast: "即时",
      recast: "120秒",
      cost: "「剑气」50",
      distant: "3",
      range: "0",
      rangeType: "zero",
      content: "对目标发动物理攻击　威力：1100<BR>发动条件：剑气50点<BR>与必杀剑·红莲共享复唱时间",
      change: ""
    },
    {
      isDisabled: "false",
      name: "燕回返",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Samurai/Action_26.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Ra2GV79gVQhy6SwCrU19boTghc.png",
      tname: "武士",
      ticon: "",
      lvl: "Lv76",
      classification: "能力",
      cast: "即时",
      recast: "60秒",
      cost: "-",
      distant: "0",
      range: "0",
      rangeType: "zero",
      content: "发动上一次使用的居合术<BR>发动条件：居合术使用完毕<BR>该能力不仅有单独计算的复唱时间，还会与战技共享复唱时间",
      change: "技能名称由“燕返”变更为“燕回返”"
    },
    {
      isDisabled: "false",
      name: "照破",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Samurai/Action_27.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Ra2GV79gVQhy6SwCrU19boTghc.png",
      tname: "武士",
      ticon: "",
      lvl: "Lv80",
      classification: "能力",
      cast: "即时",
      recast: "15秒",
      cost: "「剑压」3档",
      distant: "3",
      range: "0",
      rangeType: "zero",
      content: "对目标发动物理攻击<BR>威力：400<BR>发动条件：「剑压」3档",
      change: "・威力由「1档时威力： 100，2档时威力： 300，3档时威力： 400，4档时威力： 450，5档时威力： 500」改为「威力：400」<nr>增加「发动条件：剑压3档」。<br>复唱时间由1秒变为15秒"
    }
  ];


  others: any[] = [
    {
        isDisabled: "false",
      name: "彼岸花",
        ndes: "",
        pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Samurai/Action_28.png",
        tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Ra2GV79gVQhy6SwCrU19boTghc.png",
        tname: "武士",
        ticon: "",
        lvl: "Lv30",
        classification: "战技",
        cast: "1.3秒",
        recast: "2.5秒",
        cost: "「闪」全部",
        distant: "3",
        range: "0",
        rangeType: "zero",
      content: "对目标发动物理攻击　威力：250<BR>追加效果：持续伤害<BR>威力：40　持续时间：60秒<br>追加效果：剑压 最大档数：3档　持续时间：永久<BR><BR>※该技能无法设置到热键栏",
        change: "增加「追加效果：剑压 最大档数：3档　持续时间：永久」。"
    },
    {
        isDisabled: "false",
      name: "天下五剑",
        ndes: "",
        pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Samurai/Action_29.png",
        tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Ra2GV79gVQhy6SwCrU19boTghc.png",
        tname: "武士",
        ticon: "",
        lvl: "Lv40",
        classification: "战技",
        cast: "1.3秒",
        recast: "2.5秒",
        cost: "「闪」全部",
        distant: "8",
        range: "8",
        rangeType: "zero",
      content: "向目标所在方向发出扇形范围物理攻击　威力：360<br>追加效果：剑压 最大档数：3档　持续时间：永久<BR><BR>※该技能无法设置到热键栏",
        change: "增加「追加效果：剑压 最大档数：3档　持续时间：永久」。"
    },
    {
        isDisabled: "false",
      name: "纷乱雪月花",
        ndes: "",
        pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Samurai/Action_30.png",
        tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Ra2GV79gVQhy6SwCrU19boTghc.png",
        tname: "武士",
        ticon: "",
        lvl: "Lv50",
        classification: "战技",
        cast: "1.3秒",
        recast: "2.5秒",
        cost: "「闪」全部",
        distant: "3",
        range: "0",
        rangeType: "zero",
      content: "对目标发动物理攻击　威力：800<br>追加效果：剑压 最大档数：3档　持续时间：永久<BR><BR>※该技能无法设置到热键栏",
        change: "增加「追加效果：剑压 最大档数：3档　持续时间：永久」。"
    },
    {
        isDisabled: "false",
      name: "回返彼岸花",
        ndes: "",
        pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Samurai/Action_31.png",
        tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Ra2GV79gVQhy6SwCrU19boTghc.png",
        tname: "武士",
        ticon: "",
        lvl: "Lv76",
        classification: "能力",
        cast: "即时",
        recast: "60秒",
        cost: "-",
        distant: "3",
        range: "0",
        rangeType: "zero",
      content: "对目标发动物理攻击　威力：375<BR>追加效果：持续伤害<BR>威力：60　持续时间：60秒<BR>无法与彼岸花的持续伤害叠加<BR>该能力不仅有单独计算的复唱时间，还会与战技共享复唱时间<br>追加效果：剑压 最大档数：3档　持续时间：永久<BR><BR>※该技能无法设置到热键栏",
        change: "增加「追加效果：剑压 最大档数：3档　持续时间：永久」。"
    },
    {
        isDisabled: "false",
      name: "回返五剑",
        ndes: "",
        pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Samurai/Action_32.png",
        tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Ra2GV79gVQhy6SwCrU19boTghc.png",
        tname: "武士",
        ticon: "",
        lvl: "Lv76",
        classification: "能力",
        cast: "即时",
        recast: "60秒",
        cost: "-",
        distant: "8",
        range: "8",
        rangeType: "zero",
      content: "向目标所在方向发出扇形范围物理攻击　威力：540<BR>该能力不仅有单独计算的复唱时间，还会与战技共享复唱时间<br>追加效果：剑压 最大档数：3档　持续时间：永久<BR><BR>※该技能无法设置到热键栏",
        change: "增加「追加效果：剑压 最大档数：3档　持续时间：永久」。"
    },
    {
        isDisabled: "false",
      name: "回返雪月花",
        ndes: "",
        pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Samurai/Action_33.png",
        tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Ra2GV79gVQhy6SwCrU19boTghc.png",
        tname: "武士",
        ticon: "",
        lvl: "Lv76",
        classification: "能力",
        cast: "即时",
        recast: "60秒",
        cost: "-",
        distant: "3",
        range: "0",
        rangeType: "zero",
      content: "对目标发动物理攻击　威力：1200<BR>该能力不仅有单独计算的复唱时间，还会与战技共享复唱时间<br>追加效果：剑压 最大档数：3档　持续时间：永久<BR><BR>※该技能无法设置到热键栏",
        change: "增加「追加效果：剑压 最大档数：3档　持续时间：永久」。"
    }                     
             ];


  roleSkills: any[] = [
    {
      isDisabled: "false",
      name: "内丹",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/2pih1KRjQsYAb_j4w7GkRFyglk.png",
      tiurl: "",
      tname: "",
      ticon: [
        { "url": 'https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/9muqitiUXEK0W3qnM33Nb7sATk.png', tname: '近战职业' },
        { "url": 'https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/oWWxUIO2KagIEhDXy0541MRD7M.png', tname: '远程物理职业' }
      ],
      lvl: "",
      classification: "能力",
      cast: "即时",
      recast: "120秒",
      cost: "-",
      distant: "0",
      range: "0",
      rangeType: "zero",
      content: "恢复自身体力<br>恢复力：500",
      change: ""
    },
    {
      isDisabled: "false",
      name: "扫腿",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/h-Vwg7qPNp0rAE9sbya2c9SGC4.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/9muqitiUXEK0W3qnM33Nb7sATk.png",
      tname: "近战职业",
      ticon: [{ "url": 'https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/9muqitiUXEK0W3qnM33Nb7sATk.png', tname: '近战职业' }],
      lvl: "Lv10",
      classification: "能力",
      cast: "即时",
      recast: "40秒",
      cost: "-",
      distant: "3",
      range: "0",
      rangeType: "zero",
      content: "令目标陷入眩晕状态　持续时间：3秒",
      change: "习得等级从16变更为10。"
    },
    {
      isDisabled: "false",
      name: "浴血",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/-V15O-XUiGmZcZZepHWlHSHngQ.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/9muqitiUXEK0W3qnM33Nb7sATk.png",
      tname: "近战职业",
      ticon: [{ "url": 'https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/9muqitiUXEK0W3qnM33Nb7sATk.png', tname: '近战职业' }],
      lvl: "Lv12",
      classification: "能力",
      cast: "即时",
      recast: "90秒",
      cost: "-",
      distant: "0",
      range: "0",
      rangeType: "zero",
      content: "一定时间内，将自身物理攻击所造成伤害的一部分转化为自身的体力<BR>持续时间：20秒",
      change: "习得等级从32变更为12。"
    },
    {
      isDisabled: "false",
      name: "牵制",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/QZtAkrjZrFAcpoQbZ4PawsdbH4.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/9muqitiUXEK0W3qnM33Nb7sATk.png",
      tname: "近战职业",
      ticon: [{ "url": 'https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/9muqitiUXEK0W3qnM33Nb7sATk.png', tname: '近战职业' }],
      lvl: "Lv22",
      classification: "能力",
      cast: "即时",
      recast: "90秒",
      cost: "-",
      distant: "10",
      range: "0",
      rangeType: "zero",
      content: "一定时间内，令目标的力量与灵巧降低10%<BR>持续时间：10秒",
      change: "习得等级从40变更为22。<br>复唱时间从120秒变更为90秒。"
    },
    {
      isDisabled: "false",
      name: "亲疏自行",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/6Y_LOLWQWJSjGvQYoaGNhNaP-I.png",
      tiurl: "",
      tname: "",
      ticon: [
        { "url": 'https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/rFrCBcRe9YrmPvb4fZkuFksSLw.png', tname: '防护职业' },
        { "url": 'https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/9muqitiUXEK0W3qnM33Nb7sATk.png', tname: '近战职业' },
        { "url": 'https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/oWWxUIO2KagIEhDXy0541MRD7M.png', tname: '远程物理职业' }
      ],
      lvl: "Lv32",
      classification: "能力",
      cast: "即时",
      recast: "120秒",
      cost: "-",
      distant: "0",
      range: "0",
      rangeType: "zero",
      content: "为自身张开一个防护罩，一定时间内令除特定攻击之外其他所有击退与吸引效果失效　持续时间：6秒<BR>防护罩追加效果（受到物理攻击时，发动几率100%）：攻击者减速20%　持续时间：15秒",
      change: "习得等级从12变更为32。<br>复唱时间从60秒变更为120秒。<br>适应职业新增防护职业和远程物理职业。<br>效果时间从5秒变更为6秒。"
    },
    {
      isDisabled: "false",
      name: "真北",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/XZP5ljS8oyG6Fc82vyjrpY36Uk.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/9muqitiUXEK0W3qnM33Nb7sATk.png",
      tname: "近战职业",
      ticon: [{ "url": 'https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/9muqitiUXEK0W3qnM33Nb7sATk.png', tname: '近战职业' }],
      lvl: "Lv50",
      classification: "能力",
      cast: "即时",
      recast: "45秒",
      cost: "-",
      distant: "0",
      range: "0",
      rangeType: "zero",
      content: "一定时间内无视技能的方向要求　持续时间：10秒<BR>积蓄次数：2",
      change: "习得等级从48变更为50。<br>复唱时间从90秒变更为45秒。<br>效果时间从15秒变更为10秒。<br>新增“积蓄次数：2”。"
    }
  ];

  traits: any[] =  [
    {
        isDisabled: "false",
      name: "剑气精通",
        ndes: "",
        pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Samurai/Trait_01.png",
        tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Ra2GV79gVQhy6SwCrU19boTghc.png",
        tname: "武士",
        ticon: "",
        lvl: "Lv52",
        classification: "",
        cast: "",
        recast: "",
        cost: "",
        distant: "",
        range: "",
        rangeType: "zero",
      content: "可获得剑气量值<BR>发动条件：特定战技命中时",
        change: ""
    },
    {
        isDisabled: "false",
      name: "剑气精通II",
        ndes: "",
        pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Samurai/Trait_02.png",
        tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Ra2GV79gVQhy6SwCrU19boTghc.png",
        tname: "武士",
        ticon: "",
        lvl: "Lv62",
        classification: "",
        cast: "",
        recast: "",
        cost: "",
        distant: "",
        range: "",
        rangeType: "zero",
      content: "可以追加获得剑气量值<BR>发动条件：除居合术之外的战技命中时",
        change: ""
    },
    {
        isDisabled: "false",
      name: "居合术效果提高",
        ndes: "",
        pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Samurai/Trait_03.png",
        tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Ra2GV79gVQhy6SwCrU19boTghc.png",
        tname: "武士",
        ticon: "",
        lvl: "Lv74",
        classification: "",
        cast: "",
        recast: "",
        cost: "",
        distant: "",
        range: "",
        rangeType: "zero",
      content: "居合术的咏唱时间缩短到1.3秒",
        change: ""
    },
    {
        isDisabled: "false",
      name: "阵风士风效果提高",
        ndes: "",
        pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Samurai/Trait_04.png",
        tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Ra2GV79gVQhy6SwCrU19boTghc.png",
        tname: "武士",
        ticon: "",
        lvl: "Lv78",
        classification: "",
        cast: "",
        recast: "",
        cost: "",
        distant: "",
        range: "",
        rangeType: "zero",
      content: "阵风与士风效果量提高到13%",
        change: ""
    }                     
             ];

  ngOnInit(): void {
  }

  //获取攻击范围图标
  getRangeImage(rangeType: string) {
    return "../../assets/rangeUI/" + rangeType + ".png";
  }

}
