import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-monk',
  templateUrl: './monk.component.html',
  styleUrls: ['./monk.component.css']
})
export class MonkComponent implements OnInit {

  constructor() { }

  today: Date = new Date();

  skills: any[] = [
    {
      isDisabled: "false",
      name: "连击",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Monk/Action_01.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/5cqUqFtgdpy9D9-dk0OPyDN9Os.png",
      tname: "格斗家",
      ticon: "",
      lvl: "Lv1",
      classification: "战技",
      cast: "即时",
      recast: "2.5秒",
      cost: "-",
      distant: "3",
      range: "0",
      rangeType: "zero",
      content: "对目标发动物理攻击　威力：200<BR>连击效果提高时威力：370<BR>“魔猿身形”中追加效果：背面攻击必定暴击<BR>追加效果：盗龙身形　持续时间：15秒",
      change: "威力从150变更为200。<br>连击效果提高时威力从300变更为370。"
    },
    {
      isDisabled: "false",
      name: "正拳",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Monk/Action_02.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/5cqUqFtgdpy9D9-dk0OPyDN9Os.png",
      tname: "格斗家",
      ticon: "",
      lvl: "Lv4",
      classification: "战技",
      cast: "即时",
      recast: "2.5秒",
      cost: "-",
      distant: "3",
      range: "0",
      rangeType: "zero",
      content: "对目标发动物理攻击　威力：270<BR>背面攻击威力：300<BR>追加效果：猛豹身形　持续时间：15秒<BR>发动条件：盗龙身形状态中",
      change: "威力从220变更为270。<br>背面攻击威力从240变更为300。"
    },
    {
      isDisabled: "false",
      name: "崩拳",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Monk/Action_03.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/5cqUqFtgdpy9D9-dk0OPyDN9Os.png",
      tname: "格斗家",
      ticon: "",
      lvl: "Lv6",
      classification: "战技",
      cast: "即时",
      recast: "2.5秒",
      cost: "-",
      distant: "3",
      range: "0",
      rangeType: "zero",
      content: "对目标发动物理攻击　威力：270<BR>侧面攻击威力：300<BR>追加效果：魔猿身形　持续时间：15秒<BR>发动条件：猛豹身形状态中",
      change: "威力从210变更为270。<BR>侧面攻击威力从230变更为300。<BR>删除「追加效果：疾风迅雷」"
    },
    {
      isDisabled: "false",
      name: "金刚体势",
      ndes: "通过特职任务获得",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Monk/Action_04.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/5cqUqFtgdpy9D9-dk0OPyDN9Os.png",
      tname: "格斗家",
      ticon: "",
      lvl: "Lv15",
      classification: "能力",
      cast: "即时",
      recast: "3秒",
      cost: "-",
      distant: "0",
      range: "0",
      rangeType: "zero",
      content: "令自身受到的伤害减轻10%<BR>再次发动时则取消该状态　持续时间：永久<BR>无法与红莲体势、疾风体势同时使用<BR>与红莲体势、疾风体势共享复唱时间",
      change: ""
    },
    {
      isDisabled: "false",
      name: "双掌打",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Monk/Action_05.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/5cqUqFtgdpy9D9-dk0OPyDN9Os.png",
      tname: "格斗家",
      ticon: "",
      lvl: "Lv18",
      classification: "战技",
      cast: "即时",
      recast: "2.5秒",
      cost: "-",
      distant: "3",
      range: "0",
      rangeType: "zero",
      content: "对目标发动物理攻击　威力：230<BR>侧面攻击威力：260<BR>追加效果：攻击伤害提高10%<BR>持续时间：15秒<BR>追加效果：猛豹身形　持续时间：15秒<BR>发动条件：盗龙身形状态中",
      change: "威力从150变更为230。<BR>侧面攻击威力从170变更为260。"
    },
    {
      isDisabled: "false",
      name: "破坏神冲",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Monk/Action_06.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/5cqUqFtgdpy9D9-dk0OPyDN9Os.png",
      tname: "格斗家",
      ticon: "",
      lvl: "Lv26",
      classification: "战技",
      cast: "即时",
      recast: "2.5秒",
      cost: "-",
      distant: "0",
      range: "5",
      rangeType: "zero",
      content: "对自身周围的敌人发动范围物理攻击　威力：110<BR>“魔猿身形”中威力：140<BR>追加效果：盗龙身形　持续时间：15秒",
      change: "威力从80变更为110。<BR>“魔猿身形”中威力从110变更为140。"
    },
    {
      isDisabled: "false",
      name: "破碎拳",
      ndes: "通过特职任务获得",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Monk/Action_07.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/5cqUqFtgdpy9D9-dk0OPyDN9Os.png",
      tname: "格斗家",
      ticon: "",
      lvl: "Lv30",
      classification: "战技",
      cast: "即时",
      recast: "2.5秒",
      cost: "-",
      distant: "3",
      range: "0",
      rangeType: "zero",
      content: "对目标发动物理攻击　威力：80<BR>背面攻击威力：110<BR>追加效果：持续伤害<BR>威力：80　持续时间：18秒<BR>追加效果：魔猿身形　持续时间：15秒<BR>发动条件：猛豹身形状态中",
      change: "威力从70变更为80。<BR>背面攻击威力从90变更为110。<BR>持续伤害效果的威力从65变更为80。<BR>删除「追加效果：疾风迅雷」。"
    },
    {
      isDisabled: "false",
      name: "地烈劲",
      ndes: "通过特职任务获得",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Monk/Action_08.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Ce_VQB6VPPJKTGJwxf3h5iujp4.png",
      tname: "武僧",
      ticon: "",
      lvl: "Lv30",
      classification: "战技",
      cast: "即时",
      recast: "2.5秒",
      cost: "-",
      distant: "5",
      range: "5",
      rangeType: "zero",
      content: "自身周围发动物理攻击　威力：150<BR>追加效果：魔猿身形　持续时间：15秒<BR>发动条件：猛豹身形状态中",
      change: "威力从120变更为150。<BR>删除「追加效果：疾风迅雷」。"
    },
    {
      isDisabled: "false",
      name: "疾风体势",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Monk/Action_09.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/5cqUqFtgdpy9D9-dk0OPyDN9Os.png",
      tname: "格斗家",
      ticon: "",
      lvl: "Lv34",
      classification: "能力",
      cast: "即时",
      recast: "3秒",
      cost: "-",
      distant: "0",
      range: "0",
      rangeType: "zero",
      content: "令自身移动速度提高<BR>再次发动时则取消该状态　持续时间：永久<BR>无法与金刚体势、红莲体势同时使用<BR>与金刚体势、红莲体势共享复唱时间",
      change: ""
    },
    {
      isDisabled: "false",
      name: "罗刹冲",
      ndes: "通过特职任务获得",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Monk/Action_10.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Ce_VQB6VPPJKTGJwxf3h5iujp4.png",
      tname: "武僧",
      ticon: "",
      lvl: "Lv35",
      classification: "能力",
      cast: "即时",
      recast: "30秒",
      cost: "-",
      distant: "20",
      range: "0",
      rangeType: "zero",
      content: "冲向目标并发动物理攻击　威力：100<BR>积蓄次数：2<BR>止步状态下无法发动",
      change: "删除“追加效果：眩晕  持续时间：2秒”。<br>新增“积蓄次数：2”。"
    },
    {
      isDisabled: "false",
      name: "红莲体势",
      ndes: "通过特职任务获得",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Monk/Action_11.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Ce_VQB6VPPJKTGJwxf3h5iujp4.png",
      tname: "武僧",
      ticon: "",
      lvl: "Lv40",
      classification: "能力",
      cast: "即时",
      recast: "3秒",
      cost: "-",
      distant: "0",
      range: "0",
      rangeType: "zero",
      content: "令自身攻击造成的伤害提高10%<BR>再次发动时则取消该状态　持续时间：永久<BR>无法与金刚体势、疾风体势同时使用<BR>与金刚体势、疾风体势共享复唱时间",
      change: "效果量从6%变更为10%。"
    },
    {
      isDisabled: "false",
      name: "真言",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Monk/Action_12.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/5cqUqFtgdpy9D9-dk0OPyDN9Os.png",
      tname: "格斗家",
      ticon: "",
      lvl: "Lv42",
      classification: "能力",
      cast: "即时",
      recast: "90秒",
      cost: "-",
      distant: "0",
      range: "15",
      rangeType: "zero",
      content: "一定时间内，自身与周围队员所受的体力恢复效果提高10%　持续时间：15秒",
      change: "体力恢复效果效果量由20％变为10％"
    },
    {
      isDisabled: "false",
      name: "四面脚",
      ndes: "通过特职任务获得",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Monk/Action_13.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Ce_VQB6VPPJKTGJwxf3h5iujp4.png",
      tname: "武僧",
      ticon: "",
      lvl: "Lv45",
      classification: "战技",
      cast: "即时",
      recast: "2.5秒",
      cost: "-",
      distant: "0",
      range: "5",
      rangeType: "zero",
      content: "对自身周围的敌人发动范围物理攻击　威力：140<BR>追加效果：双掌打的持续时间延长10秒<BR>最多可延长至15秒<BR>追加效果：猛豹身形　持续时间：15秒<BR>发动条件：盗龙身形状态中",
      change: "威力从120变更为140。"
    },
    {
      isDisabled: "false",
      name: "震脚",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Monk/Action_14.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/5cqUqFtgdpy9D9-dk0OPyDN9Os.png",
      tname: "格斗家",
      ticon: "",
      lvl: "Lv50",
      classification: "能力",
      cast: "即时",
      recast: "90秒",
      cost: "-",
      distant: "0",
      range: "0",
      rangeType: "zero",
      content: "对自身附加6档的震脚状态。持续时间：15秒<BR>震脚效果：可以无视身形要求发动战技。",
      change: "「一定时间内可以无视身形要求发动战技。持续时间：10秒」变更为「对自身附加6档的震脚状态。持续时间：15秒   震脚效果：可以无视身形要求发动战技。」"
    },
    {
      isDisabled: "false",
      name: "双龙脚",
      ndes: "通过特职任务获得",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Monk/Action_15.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Ce_VQB6VPPJKTGJwxf3h5iujp4.png",
      tname: "武僧",
      ticon: "",
      lvl: "Lv50",
      classification: "战技",
      cast: "即时",
      recast: "2.5秒",
      cost: "-",
      distant: "3",
      range: "0",
      rangeType: "zero",
      content: "对目标发动物理攻击　威力：230<BR>侧面攻击威力：260<BR>“魔猿身形”中追加效果：连击效果提高<BR>持续时间：30秒<BR>追加效果：盗龙身形　持续时间：15秒",
      change: "威力从180变更为230。<BR>侧面攻击威力从200变更为260。"
    },
    {
      isDisabled: "false",
      name: "演武",
      ndes: "通过特职任务获得",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Monk/Action_16.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Ce_VQB6VPPJKTGJwxf3h5iujp4.png",
      tname: "武僧",
      ticon: "",
      lvl: "Lv52",
      classification: "战技",
      cast: "即时",
      recast: "2.5秒",
      cost: "-",
      distant: "0",
      range: "0",
      rangeType: "zero",
      content: "对自身附加无相身形状态。持续时间：15秒<BR>无相身形效果：可以无视身形要求发动战技，同时触发追加效果。",
      change: "「令自身的拳法身形变换至下一阶段。当前没有摆出身形时则变换至魔猿身形。追加效果：自身疾风迅雷的持续时间恢复到最大值。」变更为「对自身附加无相身形状态。持续时间：15秒  无相身形效果：可以无视身形要求发动战技，同时触发追加效果。」"
    },
    {
      isDisabled: "false",
      name: "斗气",
      ndes: "通过特职任务获得",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Monk/Action_17.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Ce_VQB6VPPJKTGJwxf3h5iujp4.png",
      tname: "武僧",
      ticon: "",
      lvl: "Lv54",
      classification: "能力",
      cast: "即时",
      recast: "1秒",
      cost: "-",
      distant: "0",
      range: "0",
      rangeType: "zero",
      content: "对自身附加斗气状态，最多可以积累5档<BR>持续时间：永久<BR>自身处于非战斗状态时直接获得5档斗气<BR>与战技共享复唱时间",
      change: "复唱时间从1.2秒变更为1秒。"
    },
    {
      isDisabled: "false",
      name: "阴阳斗气斩",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Monk/Action_18.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Ce_VQB6VPPJKTGJwxf3h5iujp4.png",
      tname: "武僧",
      ticon: "",
      lvl: "Lv54",
      classification: "能力",
      cast: "即时",
      recast: "1秒",
      cost: "「斗气5档」",
      distant: "3",
      range: "0",
      rangeType: "zero",
      content: "对目标发动物理攻击　威力：340<BR>发动后会取消斗气状态<BR>发动条件：自身处于战斗状态且斗气5档<BR>与万象斗气圈共享复唱时间<BR><BR>※该技能无法设置到热键栏",
      change: "威力从370变更为340。"
    },
    {
      isDisabled: "false",
      name: "苍气炮",
      ndes: "通过特职任务获得",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Monk/Action_19.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Ce_VQB6VPPJKTGJwxf3h5iujp4.png",
      tname: "武僧",
      ticon: "",
      lvl: "Lv56",
      classification: "能力",
      cast: "即时",
      recast: "30秒",
      cost: "-",
      distant: "0",
      range: "5",
      rangeType: "zero",
      content: "对自身周围的敌人发动范围物理攻击　威力：250",
      change: "威力从200变更为250。"
    },
    {
      isDisabled: "false",
      name: "斗魂旋风脚",
      ndes: "通过特职任务获得",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Monk/Action_20.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Ce_VQB6VPPJKTGJwxf3h5iujp4.png",
      tname: "武僧",
      ticon: "",
      lvl: "Lv60",
      classification: "能力",
      cast: "即时",
      recast: "45秒",
      cost: "-",
      distant: "3",
      range: "0",
      rangeType: "zero",
      content: "对目标发动物理攻击　威力：400",
      change: "威力从430变更为400。<br>复唱时间从10秒变更为45秒。<br>删除「发动条件：疾风迅雷最大档数」。"
    },
    {
      isDisabled: "false",
      name: "金刚极意",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Monk/Action_21.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Ce_VQB6VPPJKTGJwxf3h5iujp4.png",
      tname: "武僧",
      ticon: "",
      lvl: "Lv64",
      classification: "能力",
      cast: "即时",
      recast: "30秒",
      cost: "-",
      distant: "0",
      range: "0",
      rangeType: "zero",
      content: "对自身附加3档『金刚极意』。持续时间结束或发动3次战技后取消该状态。效果时间：10秒<br>金刚极意效果：自身所受的伤害减轻10%。同时无视技能的方向要求。积蓄次数：3",
      "type": "update",
      change: "效果从「一定时间内，自身所受的伤害减轻10%。同时无视技能的方向要求。效果时间：6秒积蓄次数：3」变更为「对自身附加3档『金刚极意』。持续时间结束或发动3次战技后取消该状态。效果时间：10秒 金刚极意效果：自身所受的伤害减轻10%。同时无视技能的方向要求。积蓄次数：3」。"
    },
    {
      isDisabled: "false",
      name: "红莲极意",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Monk/Action_22.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Ce_VQB6VPPJKTGJwxf3h5iujp4.png",
      tname: "武僧",
      ticon: "",
      lvl: "Lv68",
      classification: "能力",
      cast: "即时",
      recast: "90秒",
      cost: "-",
      distant: "0",
      range: "0",
      rangeType: "zero",
      content: "一定时间内，自身发动攻击造成的伤害提高25%<BR>持续时间：20秒",
      change: "效果更新。"
    },
    {
      isDisabled: "false",
      name: "义结金兰",
      ndes: "通过特职任务获得",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Monk/Action_23.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Ce_VQB6VPPJKTGJwxf3h5iujp4.png",
      tname: "武僧",
      ticon: "",
      lvl: "Lv70",
      classification: "能力",
      cast: "即时",
      recast: "90秒",
      cost: "-",
      distant: "0",
      range: "15",
      rangeType: "zero",
      content: "为自身与周围队员附加义结金兰：斗气状态<BR>自身与周围队员发动战技与魔法时有20%几率为自身附加1档斗气<BR>为自身与周围队员附加义结金兰：攻击状态<BR>发动攻击造成的伤害提高5%<BR>持续时间：15秒",
      change: "「义结金兰：攻击」的效果从「发动物理攻击造成的伤害提高5%」变更为「发动攻击造成的伤害提高5%」。<BR>「义结金兰：斗气」为自身附加「斗气」的条件中追加「魔法」。<BR>「义结金兰：斗气」为自身附加「斗气」的几率从30％变更为20％。"
    },
    {
      isDisabled: "false",
      name: "万象斗气圈",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Monk/Action_24.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Ce_VQB6VPPJKTGJwxf3h5iujp4.png",
      tname: "武僧",
      ticon: "",
      lvl: "Lv74",
      classification: "能力",
      cast: "即时",
      recast: "1秒",
      cost: "「斗气5档」",
      distant: "10",
      range: "10",
      rangeType: "zero",
      content: "向目标所在方向发出直线范围物理攻击　威力：220<BR>发动后会取消斗气状态<BR>发动条件：自身处于战斗状态且斗气5档<BR>与阴阳斗气斩共享复唱时间",
      change: ""
    },
    {
      isDisabled: "false",
      name: "无我",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Monk/Action_25.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Ce_VQB6VPPJKTGJwxf3h5iujp4.png",
      tname: "武僧",
      ticon: "",
      lvl: "Lv78",
      classification: "能力",
      cast: "即时",
      recast: "60秒",
      cost: "-",
      distant: "0",
      range: "0",
      rangeType: "zero",
      content: "令自身附加的身形与双掌打的持续时间恢复到最大值，同时暂停持续时间的流逝<BR>效果时间内发动技能或进行移动、转身都会立即解除无我<BR>发动之后会停止自动攻击　持续时间：30秒<BR>该能力不仅有单独计算的复唱时间，还会与战技共享复唱时间",
      change: "「令自身附加的身形与疾风迅雷的持续时间暂停。自身处于战斗状态时，疾风迅雷的持续时间恢复到最大值，且不断叠加疾风迅雷状态。」变更为「令自身附加的身形与双掌打的持续时间恢复到最大值，同时暂停持续时间的流逝。」"
    },
    {
      isDisabled: "false",
      name: "六合星导脚",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Monk/Action_26.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Ce_VQB6VPPJKTGJwxf3h5iujp4.png",
      tname: "武僧",
      ticon: "",
      lvl: "Lv80",
      classification: "战技",
      cast: "即时",
      recast: "5秒",
      cost: "-",
      distant: "3",
      range: "0",
      rangeType: "zero",
      content: "对目标发动物理攻击　威力：540<BR>追加效果：提高自身的移动速度<BR>持续时间：5秒<BR>该战技有单独计算的复唱时间，发动后其他战技与魔法会产生与该战技相同的复唱时间",
      change: "威力从400变更为540。<BR>追加「追加效果：提高自身的移动速度。持续时间：5秒」。<BR>删除「追加效果：自身疾风迅雷的持续时间恢复到最大值。」。"
    }
  ];

  roleSkills: any[] = [
    {
      isDisabled: "false",
      name: "内丹",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/2pih1KRjQsYAb_j4w7GkRFyglk.png",
      tiurl: "",
      tname: "",
      ticon: [
        { "url": 'https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/9muqitiUXEK0W3qnM33Nb7sATk.png', tname: '近战职业' },
        { "url": 'https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/oWWxUIO2KagIEhDXy0541MRD7M.png', tname: '远程物理职业' }
      ],
      lvl: "",
      classification: "能力",
      cast: "即时",
      recast: "120秒",
      cost: "-",
      distant: "0",
      range: "0",
      rangeType: "zero",
      content: "恢复自身体力<br>恢复力：500",
      change: ""
    },
    {
      isDisabled: "false",
      name: "扫腿",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/h-Vwg7qPNp0rAE9sbya2c9SGC4.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/9muqitiUXEK0W3qnM33Nb7sATk.png",
      tname: "近战职业",
      ticon: [{ "url": 'https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/9muqitiUXEK0W3qnM33Nb7sATk.png', tname: '近战职业' }],
      lvl: "Lv10",
      classification: "能力",
      cast: "即时",
      recast: "40秒",
      cost: "-",
      distant: "3",
      range: "0",
      rangeType: "zero",
      content: "令目标陷入眩晕状态　持续时间：3秒",
      change: "习得等级从16变更为10。"
    },
    {
      isDisabled: "false",
      name: "浴血",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/-V15O-XUiGmZcZZepHWlHSHngQ.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/9muqitiUXEK0W3qnM33Nb7sATk.png",
      tname: "近战职业",
      ticon: [{ "url": 'https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/9muqitiUXEK0W3qnM33Nb7sATk.png', tname: '近战职业' }],
      lvl: "Lv12",
      classification: "能力",
      cast: "即时",
      recast: "90秒",
      cost: "-",
      distant: "0",
      range: "0",
      rangeType: "zero",
      content: "一定时间内，将自身物理攻击所造成伤害的一部分转化为自身的体力<BR>持续时间：20秒",
      change: "习得等级从32变更为12。"
    },
    {
      isDisabled: "false",
      name: "牵制",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/QZtAkrjZrFAcpoQbZ4PawsdbH4.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/9muqitiUXEK0W3qnM33Nb7sATk.png",
      tname: "近战职业",
      ticon: [{ "url": 'https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/9muqitiUXEK0W3qnM33Nb7sATk.png', tname: '近战职业' }],
      lvl: "Lv22",
      classification: "能力",
      cast: "即时",
      recast: "90秒",
      cost: "-",
      distant: "10",
      range: "0",
      rangeType: "zero",
      content: "一定时间内，令目标的力量与灵巧降低10%<BR>持续时间：10秒",
      change: "习得等级从40变更为22。<br>复唱时间从120秒变更为90秒。"
    },
    {
      isDisabled: "false",
      name: "亲疏自行",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/6Y_LOLWQWJSjGvQYoaGNhNaP-I.png",
      tiurl: "",
      tname: "",
      ticon: [
        { "url": 'https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/rFrCBcRe9YrmPvb4fZkuFksSLw.png', tname: '防护职业' },
        { "url": 'https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/9muqitiUXEK0W3qnM33Nb7sATk.png', tname: '近战职业' },
        { "url": 'https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/oWWxUIO2KagIEhDXy0541MRD7M.png', tname: '远程物理职业' }
      ],
      lvl: "Lv32",
      classification: "能力",
      cast: "即时",
      recast: "120秒",
      cost: "-",
      distant: "0",
      range: "0",
      rangeType: "zero",
      content: "为自身张开一个防护罩，一定时间内令除特定攻击之外其他所有击退与吸引效果失效　持续时间：6秒<BR>防护罩追加效果（受到物理攻击时，发动几率100%）：攻击者减速20%　持续时间：15秒",
      change: "习得等级从12变更为32。<br>复唱时间从60秒变更为120秒。<br>适应职业新增防护职业和远程物理职业。<br>效果时间从5秒变更为6秒。"
    },
    {
      isDisabled: "false",
      name: "真北",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/XZP5ljS8oyG6Fc82vyjrpY36Uk.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/9muqitiUXEK0W3qnM33Nb7sATk.png",
      tname: "近战职业",
      ticon: [{ "url": 'https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/9muqitiUXEK0W3qnM33Nb7sATk.png', tname: '近战职业' }],
      lvl: "Lv50",
      classification: "能力",
      cast: "即时",
      recast: "45秒",
      cost: "-",
      distant: "0",
      range: "0",
      rangeType: "zero",
      content: "一定时间内无视技能的方向要求　持续时间：10秒<BR>积蓄次数：2",
      change: "习得等级从48变更为50。<br>复唱时间从90秒变更为45秒。<br>效果时间从15秒变更为10秒。<br>新增“积蓄次数：2”。"
    }
  ];


  traits: any[] = [
    {
      isDisabled: "false",
      name: "疾风迅雷",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Monk/Trait_00.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/5cqUqFtgdpy9D9-dk0OPyDN9Os.png",
      tname: "格斗家",
      ticon: "",
      lvl: "Lv1",
      classification: "",
      cast: "",
      recast: "",
      cost: "",
      distant: "",
      range: "",
      rangeType: "zero",
      content: "自动攻击间隔、战技与魔法的咏唱及复唱时间缩短5%",
      "type": "new",
      change: ""
    },
    {
      isDisabled: "false",
      name: "疾风迅雷效果提高",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Monk/Trait_01.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/5cqUqFtgdpy9D9-dk0OPyDN9Os.png",
      tname: "格斗家",
      ticon: "",
      lvl: "Lv20",
      classification: "",
      cast: "",
      recast: "",
      cost: "",
      distant: "",
      range: "",
      rangeType: "zero",
      content: "自动攻击间隔、战技与魔法的咏唱及复唱时间缩短10%",
      "type": "new",
      change: "「疾风迅雷可以累积到2档」变更为「自动攻击间隔、战技与魔法的咏唱及复唱时间缩短10%」"
    },
    {
      isDisabled: "false",
      name: "疾风迅雷效果提高II",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Monk/Trait_02.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/5cqUqFtgdpy9D9-dk0OPyDN9Os.png",
      tname: "格斗家",
      ticon: "",
      lvl: "Lv40",
      classification: "",
      cast: "",
      recast: "",
      cost: "",
      distant: "",
      range: "",
      rangeType: "zero",
      content: "自动攻击间隔、战技与魔法的咏唱及复唱时间缩短15%",
      "type": "new",
      change: "「疾风迅雷可以累积到3档」变更为「自动攻击间隔、战技与魔法的咏唱及复唱时间缩短15%」"
    },
    {
      isDisabled: "false",
      name: "斗气积累提高",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Monk/Trait_03.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Ce_VQB6VPPJKTGJwxf3h5iujp4.png",
      tname: "武僧",
      ticon: "",
      lvl: "Lv62",
      classification: "",
      cast: "",
      recast: "",
      cost: "",
      distant: "",
      range: "",
      rangeType: "zero",
      content: "对自身附加斗气状态<BR>发动条件：战技暴击时（发动几率80%）",
      change: "斗气积累的发动几率从50%变更为80%。"
    },
    {
      isDisabled: "false",
      name: "罗刹冲精通",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Monk/Trait_04.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Ce_VQB6VPPJKTGJwxf3h5iujp4.png",
      tname: "武僧",
      ticon: "",
      lvl: "Lv66",
      classification: "",
      cast: "",
      recast: "",
      cost: "",
      distant: "",
      range: "",
      rangeType: "zero",
      content: "罗刹冲变为积蓄技能<BR>积蓄次数：2",
      change: "效果更新。"
    },
    {
      isDisabled: "false",
      name: "红莲体势效果提高",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Monk/Trait_05.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Ce_VQB6VPPJKTGJwxf3h5iujp4.png",
      tname: "武僧",
      ticon: "",
      lvl: "Lv72",
      classification: "",
      cast: "",
      recast: "",
      cost: "",
      distant: "",
      range: "",
      rangeType: "zero",
      content: "效果量提高到10%",
      change: ""
    },
    {
      isDisabled: "false",
      name: "斗气积累提高II",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Monk/Trait_06.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Ce_VQB6VPPJKTGJwxf3h5iujp4.png",
      tname: "武僧",
      ticon: "",
      lvl: "Lv74",
      classification: "",
      cast: "",
      recast: "",
      cost: "",
      distant: "",
      range: "",
      rangeType: "zero",
      content: "对自身附加斗气状态的几率上升到100%<BR>发动条件：战技暴击时",
      change: "对自身附加斗气状态的上升几率从70%变更为100%。"
    },
    {
      isDisabled: "false",
      name: "疾风迅雷效果提高II",
      ndes: "",
      pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Monk/Trait_08.png",
      tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Ce_VQB6VPPJKTGJwxf3h5iujp4.png",
      tname: "武僧",
      ticon: "",
      lvl: "Lv76",
      classification: "",
      cast: "",
      recast: "",
      cost: "",
      distant: "",
      range: "",
      rangeType: "zero",
      content: "自动攻击间隔、战技与魔法的咏唱及复唱时间缩短20%",
      "type": "new",
      change: ""
    }];


  ngOnInit(): void {
  }

  //获取攻击范围图标
  getRangeImage(rangeType: string) {
    return "../../assets/rangeUI/" + rangeType + ".png";
  }

}
