import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-black-mage',
  templateUrl: './black-mage.component.html',
  styleUrls: ['./black-mage.component.css']
})
export class BlackMageComponent implements OnInit {

  constructor() { }

  skills: any[] = [
    {
        name: "冰结", 
        ndes: "", 
        pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Action_01.png", 
        tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Zlo0xBHOBte3IGPo8SY9XUcGes.png", 
        tname: "咒术师", 
        ticon: "", 
        lvl: "Lv1", 
        classification: "魔法", 
        cast: "2.5秒", 
        recast: "2.5秒", 
        cost: "魔力400", 
        distant: "25", 
        range: 0, 
        content: "对目标发动冰属性魔法攻击　威力：180<BR>追加效果：灵极冰　持续时间：15秒<BR>在处于星极火状态时只会解除该状态<BR>持续时间：15秒", 
        change: "效果时间从13秒变更为15秒。"
    }, 
    {
        name: "火炎", 
        ndes: "", 
        pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Action_02.png", 
        tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Zlo0xBHOBte3IGPo8SY9XUcGes.png", 
        tname: "咒术师", 
        ticon: "", 
        lvl: "Lv2", 
        classification: "魔法", 
        cast: "2.5秒", 
        recast: "2.5秒", 
        cost: "魔力800", 
        distant: "25", 
        range: 0, 
        content: "对目标发动火属性魔法攻击　威力：180<BR>追加效果：星极火　持续时间：15秒<BR>在处于灵极冰状态时只会解除该状态<BR>持续时间：15秒<BR>追加效果（发动几率40%）：下次发动爆炎不消耗魔力，同时也没有咏唱时间　持续时间：18秒", 
        change: "效果时间从13秒变更为15秒。"
    }, 
    {
        name: "星灵移位", 
        ndes: "", 
        pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Action_03.png", 
        tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Zlo0xBHOBte3IGPo8SY9XUcGes.png", 
        tname: "咒术师", 
        ticon: "", 
        lvl: "Lv4", 
        classification: "能力", 
        cast: "即时", 
        recast: "5秒", 
        cost: "-", 
        distant: 0, 
        range: 0, 
        content: "自身处于星极火或灵极冰的状态时迅速切换到另一状态的初级阶段", 
        change: "复唱时间从8秒变更为5秒。"
    }, 
    {
        name: "闪雷", 
        ndes: "", 
        pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Action_04.png", 
        tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Zlo0xBHOBte3IGPo8SY9XUcGes.png", 
        tname: "咒术师", 
        ticon: "", 
        lvl: "Lv6", 
        classification: "魔法", 
        cast: "2.5秒", 
        recast: "2.5秒", 
        cost: "魔力200", 
        distant: "25", 
        range: 0, 
        content: "对目标发动雷属性魔法攻击　威力：30<BR>追加效果：雷属性持续伤害<BR>威力：40　持续时间：18秒<BR>自身对目标附加的雷系魔法持续伤害效果同时只能存在一种<BR>追加效果（持续伤害每次起效时，发动几率10%）：<BR>下次发动的雷系魔法咏唱时间与消耗魔力均为0<BR>且命中时的威力会加算持续伤害的总和<BR>持续时间：18秒", 
        change: ""
    }, 
    {
        name: "催眠", 
        ndes: "", 
        pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Action_05.png", 
        tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Zlo0xBHOBte3IGPo8SY9XUcGes.png", 
        tname: "咒术师", 
        ticon: "", 
        lvl: "Lv10", 
        classification: "魔法", 
        cast: "2.5秒", 
        recast: "2.5秒", 
        cost: "魔力800", 
        distant: "30", 
        range: "5", 
        content: "令目标及其周围的敌人陷入睡眠状态　持续时间：30秒<BR>发动之后会停止自动攻击", 
        change: ""
    }, 
    {
        name: "冰冻", 
        ndes: "", 
        pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Action_06.png", 
        tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Zlo0xBHOBte3IGPo8SY9XUcGes.png", 
        tname: "咒术师", 
        ticon: "", 
        lvl: "Lv12", 
        classification: "魔法", 
        cast: "2秒", 
        recast: "2.5秒", 
        cost: "魔力800", 
        distant: 0, 
        range: "5", 
        content: "对周围的敌人发动冰属性范围魔法攻击　威力：50<BR>追加效果：灵极冰　持续时间：15秒<BR>在处于星极火状态时只会解除该状态<BR>持续时间：15秒", 
        change: "删除“追加效果：止步　效果时间：8秒”。<br>效果时间从13秒变更为15秒。"
    }, 
    {
        name: "崩溃", 
        ndes: "通过特职任务获得", 
        pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Action_07.png", 
        tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Zlo0xBHOBte3IGPo8SY9XUcGes.png", 
        tname: "咒术师", 
        ticon: "", 
        lvl: "Lv15", 
        classification: "魔法", 
        cast: "即时", 
        recast: "2.5秒", 
        cost: "魔力800", 
        distant: "25", 
        range: 0, 
        content: "对目标发动无属性魔法攻击　威力：100<BR>追加效果（发动几率20%）：伤害变为2倍", 
        change: ""
    }, 
    {
        name: "烈炎", 
        ndes: "", 
        pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Action_08.png", 
        tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Zlo0xBHOBte3IGPo8SY9XUcGes.png", 
        tname: "咒术师", 
        ticon: "", 
        lvl: "Lv18", 
        classification: "魔法", 
        cast: "3秒", 
        recast: "2.5秒", 
        cost: "魔力1500", 
        distant: "25", 
        range: "5", 
        content: "对目标及其周围的敌人发动火属性范围魔法攻击　威力：80<BR>追加效果：星极火　持续时间：15秒<BR>在处于灵极冰状态时只会解除该状态<BR>持续时间：15秒", 
        change: "效果时间从13秒变更为15秒。"
    }, 
    {
        name: "震雷", 
        ndes: "", 
        pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Action_09.png", 
        tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Zlo0xBHOBte3IGPo8SY9XUcGes.png", 
        tname: "咒术师", 
        ticon: "", 
        lvl: "Lv26", 
        classification: "魔法", 
        cast: "3秒", 
        recast: "2.5秒", 
        cost: "魔力400", 
        distant: "25", 
        range: "5", 
        content: "对目标发动雷属性魔法攻击　威力：50<BR>追加效果：雷击　持续时间：21秒<BR>雷击效果：雷属性持续伤害　威力：40　<BR>追加效果（雷击效果中，发动几率10%）：下次发动的闪雷、震雷、暴雷的咏唱时间与消耗魔力均为0，并且威力变为330<BR>持续时间：12秒", 
        change: ""
    }, 
    {
        name: "魔罩", 
        ndes: "通过特职任务获得", 
        pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Action_10.png", 
        tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Zlo0xBHOBte3IGPo8SY9XUcGes.png", 
        tname: "咒术师", 
        ticon: "", 
        lvl: "Lv30", 
        classification: "能力", 
        cast: "即时", 
        recast: "120秒", 
        cost: "-", 
        distant: 0, 
        range: 0, 
        content: "为自身张开一个防护罩，在一定时间内能抵消相当于最大体力30%的伤害量<BR>抵消的伤害量超过上限时防护罩自动消失<BR>持续时间：20秒", 
        change: ""
    }, 
    {
        name: "魔泉", 
        ndes: "通过特职任务获得", 
        pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Action_11.png", 
        tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/7JuT00VSwaFqTfcTYUCUnGPFQE.png", 
        tname: "黑魔法师", 
        ticon: "", 
        lvl: "Lv30", 
        classification: "能力", 
        cast: "即时", 
        recast: "180秒", 
        cost: "-", 
        distant: 0, 
        range: 0, 
        content: "恢复最大魔力的30%", 
        change: "技能名称变更。<br>效果更新。"
    }, 
    {
        name: "爆炎", 
        ndes: "", 
        pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Action_12.png", 
        tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Zlo0xBHOBte3IGPo8SY9XUcGes.png", 
        tname: "咒术师", 
        ticon: "", 
        lvl: "Lv34", 
        classification: "魔法", 
        cast: "3.5秒", 
        recast: "2.5秒", 
        cost: "魔力2000", 
        distant: "25", 
        range: 0, 
        content: "对目标发动火属性魔法攻击　威力：240<BR>追加效果：星极火最大档数　持续时间：15秒<BR>在处于灵极冰状态时会同时解除该状态", 
        change: "效果时间从13秒变更为15秒。"
    }, 
    {
        name: "玄冰", 
        ndes: "通过特职任务获得", 
        pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Action_13.png", 
        tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/7JuT00VSwaFqTfcTYUCUnGPFQE.png", 
        tname: "黑魔法师", 
        ticon: "", 
        lvl: "Lv35", 
        classification: "魔法", 
        cast: "2.5秒", 
        recast: "2.5秒", 
        cost: "魔力1000", 
        distant: "25", 
        range: "5", 
        content: "对目标及其周围的敌人发动冰属性范围魔法攻击　威力：100<BR>追加效果：灵极冰最大档数　持续时间：15秒<BR>在处于星极火状态时会同时解除该状态<BR>追加效果：1档灵极心<BR>灵极心效果：抵消星极火状态中发动火系魔法增加的魔力消耗<BR>另外，发动核爆时会消耗全部的灵极心将魔力消耗降为2/3", 
        change: "效果更新。<br>咏唱时间从3秒变更为2.5秒。"
    }, 
    {
        name: "冰封", 
        ndes: "通过特职任务获得", 
        pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Action_14.png", 
        tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/7JuT00VSwaFqTfcTYUCUnGPFQE.png", 
        tname: "黑魔法师", 
        ticon: "", 
        lvl: "Lv40", 
        classification: "魔法", 
        cast: "3.5秒", 
        recast: "2.5秒", 
        cost: "魔力800", 
        distant: "25", 
        range: 0, 
        content: "对目标发动冰属性魔法攻击　威力：240<BR>追加效果：灵极冰最大档数　持续时间：15秒<BR>在处于星极火状态时会同时解除该状态", 
        change: "效果时间从13秒变更为15秒。"
    }, 
    {
        name: "暴雷", 
        ndes: "通过特职任务获得", 
        pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Action_15.png", 
        tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/7JuT00VSwaFqTfcTYUCUnGPFQE.png", 
        tname: "黑魔法师", 
        ticon: "", 
        lvl: "Lv45", 
        classification: "魔法", 
        cast: "2.5秒", 
        recast: "2.5秒", 
        cost: "魔力400", 
        distant: "25", 
        range: 0, 
        content: "对目标发动雷属性魔法攻击　威力：70<BR>追加效果：雷属性持续伤害<BR>威力：40　持续时间：24秒<BR>自身对目标附加的雷系魔法持续伤害效果同时只能存在一种<BR>追加效果（持续伤害每次起效时，发动几率10%）：<BR>下次发动的雷系魔法咏唱时间与消耗魔力均为0<BR>且命中时的威力会加算持续伤害的总和<BR>持续时间：18秒", 
        change: ""
    }, 
    {
        name: "以太步", 
        ndes: "", 
        pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Action_16.png", 
        tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/7JuT00VSwaFqTfcTYUCUnGPFQE.png", 
        tname: "黑魔法师", 
        ticon: "", 
        lvl: "Lv50", 
        classification: "能力", 
        cast: "即时", 
        recast: "10秒", 
        cost: "-", 
        distant: "25", 
        range: 0, 
        content: "指定一名队员为目标，自身快速移动到目标身边<BR>止步状态下无法发动", 
        change: ""
    }, 
    {
        name: "核爆", 
        ndes: "通过特职任务获得", 
        pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Action_17.png", 
        tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Zlo0xBHOBte3IGPo8SY9XUcGes.png", 
        tname: "咒术师", 
        ticon: "", 
        lvl: "Lv50", 
        classification: "魔法", 
        cast: "4秒", 
        recast: "2.5秒", 
        cost: "全部魔力", 
        distant: "25", 
        range: "5", 
        content: "对目标及其周围的敌人发动火属性范围魔法攻击　威力：260<BR>攻击复数敌人时，对目标之外的敌人威力降低40%<BR>追加效果：星极火最大档数　持续时间：15秒<BR>在处于灵极冰状态时会同时解除该状态", 
        change: "从“攻击复数目标时，每多1目标，对该目标威力降低15%，最低降为30%”变更为“攻击复数敌人时，对目标之外的敌人威力降低40%”。<br>效果时间从13秒变更为15秒。<br>"
    }, 
    {
        name: "黑魔纹", 
        ndes: "通过特职任务获得", 
        pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Action_18.png", 
        tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/7JuT00VSwaFqTfcTYUCUnGPFQE.png", 
        tname: "黑魔法师", 
        ticon: "", 
        lvl: "Lv52", 
        classification: "能力", 
        cast: "即时", 
        recast: "90秒", 
        cost: "-", 
        distant: 0, 
        range: "3", 
        content: "在自身脚下产生黑魔纹<BR>黑魔纹效果：自身的自动攻击间隔、魔法的咏唱及复唱时间缩短15%<BR>持续时间：30秒", 
        change: ""
    }, 
    {
        name: "激情咏唱", 
        ndes: "通过特职任务获得", 
        pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Action_19.png", 
        tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/7JuT00VSwaFqTfcTYUCUnGPFQE.png", 
        tname: "黑魔法师", 
        ticon: "", 
        lvl: "Lv54", 
        classification: "能力", 
        cast: "即时", 
        recast: "30秒", 
        cost: "-", 
        distant: 0, 
        range: 0, 
        content: "效果时间内，自身发动的1次“崩溃”或“火炎”或“雷系魔法”必定触发“崩溃的追加效果”“火苗”“雷云”<BR>持续时间：15秒", 
        change: "复唱时间从60秒变更为30秒。"
    }, 
    {
        name: "天语", 
        ndes: "通过特职任务获得", 
        pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Action_20.png", 
        tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/7JuT00VSwaFqTfcTYUCUnGPFQE.png", 
        tname: "黑魔法师", 
        ticon: "", 
        lvl: "Lv56", 
        classification: "能力", 
        cast: "即时", 
        recast: "30秒", 
        cost: "-", 
        distant: 0, 
        range: 0, 
        content: "一定时间内，自身发动魔法攻击造成的伤害提高15%<BR>同时可以咏唱冰澈、炽炎、绝望、灵极魂<BR>星极火及灵极冰状态全部消失时天语状态也会同时消失<BR>追加效果：天语状态持续30秒可对自身附加通晓状态<BR>最大档数：2档　持续时间：永久<BR>发动条件：星极火或灵极冰状态中", 
        change: "效果量从10%变更为15%。<br>从“可以咏唱冰澈与炽炎”变更为“可以咏唱冰澈、炽炎、绝望、灵极魂”。<br>新增“最大档数：2档　效果时间：永久”。"
    }, 
    {
        name: "冰澈", 
        ndes: "通过特职任务获得", 
        pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Action_21.png", 
        tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/7JuT00VSwaFqTfcTYUCUnGPFQE.png", 
        tname: "黑魔法师", 
        ticon: "", 
        lvl: "Lv58", 
        classification: "魔法", 
        cast: "2.8秒", 
        recast: "2.5秒", 
        cost: "魔力800", 
        distant: "25", 
        range: 0, 
        content: "对目标发动冰属性魔法攻击　威力：300<BR>追加效果：3档灵极心<BR>灵极心效果：抵消星极火状态中发动火系魔法增加的魔力消耗<BR>另外，发动核爆时会消耗全部的灵极心将魔力消耗降为2/3<BR>发动条件：天语及灵极冰状态中", 
        change: "威力从260变更为300。"
    }, 
    {
        name: "炽炎", 
        ndes: "", 
        pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Action_22.png", 
        tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/7JuT00VSwaFqTfcTYUCUnGPFQE.png", 
        tname: "黑魔法师", 
        ticon: "", 
        lvl: "Lv60", 
        classification: "魔法", 
        cast: "2.8秒", 
        recast: "2.5秒", 
        cost: "魔力800", 
        distant: "25", 
        range: 0, 
        content: "对目标发动火属性魔法攻击　威力：300<BR>发动条件：天语及星极火状态中", 
        change: ""
    }, 
    {
        name: "魔纹步", 
        ndes: "", 
        pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Action_23.png", 
        tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/7JuT00VSwaFqTfcTYUCUnGPFQE.png", 
        tname: "黑魔法师", 
        ticon: "", 
        lvl: "Lv62", 
        classification: "能力", 
        cast: "即时", 
        recast: "3秒", 
        cost: "-", 
        distant: "25", 
        range: 0, 
        content: "快速移动到自身留下的黑魔纹中心<BR>止步状态下无法发动", 
        change: ""
    }, 
    {
        name: "霹雷", 
        ndes: "", 
        pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Action_24.png", 
        tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/7JuT00VSwaFqTfcTYUCUnGPFQE.png", 
        tname: "黑魔法师", 
        ticon: "", 
        lvl: "Lv64", 
        classification: "魔法", 
        cast: "3秒", 
        recast: "2.5秒", 
        cost: "魔力800", 
        distant: "25", 
        range: "5", 
        content: "对目标及其周围敌人发动雷属性范围魔法攻击　威力：50<BR>追加效果：雷属性持续伤害<BR>威力：30　持续时间：18秒<BR>自身对目标附加的雷系魔法持续伤害效果同时只能存在一种<BR>追加效果（持续伤害每次起效时，发动几率3%）：下次发动的雷系魔法咏唱时间与消耗魔力均为0<BR>且命中时的威力会加算持续伤害的总和<BR>持续时间：18秒", 
        change: ""
    }, 
    {
        name: "三连咏唱", 
        ndes: "", 
        pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Action_25.png", 
        tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/7JuT00VSwaFqTfcTYUCUnGPFQE.png", 
        tname: "黑魔法师", 
        ticon: "", 
        lvl: "Lv66", 
        classification: "能力", 
        cast: "即时", 
        recast: "60秒", 
        cost: "-", 
        distant: 0, 
        range: 0, 
        content: "效果时间内，前3次咏唱的魔法没有任何咏唱时间　持续时间：15秒", 
        change: "状态栏中的效果图标将显示剩余次数"
    }, 
    {
        name: "秽浊", 
        ndes: "通过特职任务获得", 
        pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Action_26.png", 
        tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/7JuT00VSwaFqTfcTYUCUnGPFQE.png", 
        tname: "黑魔法师", 
        ticon: "", 
        lvl: "Lv70", 
        classification: "魔法", 
        cast: "2.5秒", 
        recast: "2.5秒", 
        cost: "「通晓」1", 
        distant: "25", 
        range: "5", 
        content: "对目标及其周围敌人发动无属性范围魔法攻击　威力：650<BR>攻击复数敌人时，对目标之外的敌人威力降低25%<BR>发动条件：通晓", 
        change: "	攻击复数目标时，对目标之外的敌人威力从「每多1目标，对该目标威力降低10%，最低降为50%」变更为「降低25％」。"
    }, 
    {
        name: "绝望", 
        ndes: "", 
        pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Action_27.png", 
        tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/7JuT00VSwaFqTfcTYUCUnGPFQE.png", 
        tname: "黑魔法师", 
        ticon: "", 
        lvl: "Lv72", 
        classification: "魔法", 
        cast: "3秒", 
        recast: "2.5秒", 
        cost: "全部魔力", 
        distant: "25", 
        range: 0, 
        content: "对目标发动火属性魔法攻击　威力：380<BR>追加效果：星极火最大档数　持续时间：15秒<BR>发动条件：天语及星极火状态中", 
        change: ""
    }, 
    {
        name: "灵极魂", 
        ndes: "", 
        pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Action_28.png", 
        tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/7JuT00VSwaFqTfcTYUCUnGPFQE.png", 
        tname: "黑魔法师", 
        ticon: "", 
        lvl: "Lv76", 
        classification: "魔法", 
        cast: "即时", 
        recast: "2.5秒", 
        cost: "-", 
        distant: 0, 
        range: 0, 
        content: "对自身附加灵极冰状态及1档灵极心<BR>灵极心效果：抵消星极火状态中发动火系魔法增加的魔力消耗<BR>另外，发动核爆时会消耗全部的灵极心将魔力消耗降为2/3<BR>发动条件：天语及灵极冰状态中", 
        change: ""
    }, 
    {
        name: "异言", 
        ndes: "", 
        pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Action_29.png", 
        tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/7JuT00VSwaFqTfcTYUCUnGPFQE.png", 
        tname: "黑魔法师", 
        ticon: "", 
        lvl: "Lv80", 
        classification: "魔法", 
        cast: "即时", 
        recast: "2.5秒", 
        cost: "「通晓」1", 
        distant: "25", 
        range: 0, 
        content: "对目标发动无属性魔法攻击　威力：750<BR>发动条件：通晓", 
        change: ""
    }
];


  roleSkills: any[] = [
    {
        name: "昏乱", 
        ndes: "", 
        pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Magical Ranged DPS Role Action_01.png", 
        tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/8Dnf8Wy9IyxIt21y6lrE5atKt0.png", 
        tname: "远程魔法职业", 
        ticon: [
          {
            "url": "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/8Dnf8Wy9IyxIt21y6lrE5atKt0.png", 
            tname: "远程魔法职业"
          }
        ], 
        lvl: "Lv8", 
        classification: "能力", 
        cast: "即时", 
        recast: "90秒", 
        cost: "-", 
        distant: "25", 
        range: 0, 
        content: "一定时间内，令目标的智力与精神降低10%<BR>持续时间：10秒", 
        change: ""
    }, 
    {
        name: "即刻咏唱", 
        ndes: "", 
        pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Magical Ranged DPS Role Action_02.png", 
        tiurl: "", 
        tname: "", 
        ticon: [
            {
                "url": "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/V5xx3kfnREBO-2xWbTUW2Csy_Q.png", 
                tname: "治疗职业"
            }, 
            {
                "url": "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/8Dnf8Wy9IyxIt21y6lrE5atKt0.png", 
                tname: "远程魔法职业"
            }
        ], 
        lvl: "Lv18", 
        classification: "能力", 
        cast: "即时", 
        recast: "60秒", 
        cost: "-", 
        distant: 0, 
        range: 0, 
        content: "一定时间内，下次咏唱的魔法没有任何咏唱时间<BR>持续时间：10秒", 
        change: "习得等级从32变更为18。"
    }, 
    {
        name: "醒梦", 
        ndes: "", 
        pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Magical Ranged DPS Role Action_03.png", 
        tiurl: "", 
        tname: "", 
        ticon: [
            {
                "url": "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/V5xx3kfnREBO-2xWbTUW2Csy_Q.png", 
                tname: "治疗职业"
            }, 
            {
                "url": "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/8Dnf8Wy9IyxIt21y6lrE5atKt0.png", 
                tname: "远程魔法职业"
            }
        ], 
        lvl: "Lv24", 
        classification: "能力", 
        cast: "即时", 
        recast: "60秒", 
        cost: "-", 
        distant: 0, 
        range: 0, 
        content: "持续恢复自身魔力<BR>效果量：50　持续时间：21秒", 
        change: "删除“将自身的仇恨减半”。<br>复唱时间从120秒变更为60秒。<br>效果量从80变更为50。"
    }, 
    {
        name: "沉稳咏唱", 
        ndes: "", 
        pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Magical Ranged DPS Role Action_04.png", 
        tiurl: "", 
        tname: "", 
        ticon: [
            {
                "url": "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/V5xx3kfnREBO-2xWbTUW2Csy_Q.png", 
                tname: "治疗职业"
            }, 
            {
                "url": "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/8Dnf8Wy9IyxIt21y6lrE5atKt0.png", 
                tname: "远程魔法职业"
            }
        ], 
        lvl: "Lv44", 
        classification: "能力", 
        cast: "即时", 
        recast: "120秒", 
        cost: "-", 
        distant: 0, 
        range: 0, 
        content: "一定时间内，咏唱的魔法不会被任何妨碍打断<BR>同时，令除特定攻击之外其他所有击退与吸引效果失效<BR>持续时间：6秒", 
        change: "复唱时间从30秒变更为120秒。<br>效果时间从5秒变更为6秒。"
    }
];


  traits: any[] = [
    {
        name: "技能效果提高", 
        ndes: "", 
        pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Trait_01.png", 
        tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Zlo0xBHOBte3IGPo8SY9XUcGes.png", 
        tname: "咒术师", 
        ticon: "", 
        lvl: "Lv20", 
        content: "除自动攻击外的技能造成的伤害提高至基本值的1.1倍，恢复技能的恢复量也提高至基本值的1.1倍", 
        change: ""
    }, 
    {
        name: "雷云", 
        ndes: "", 
        pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Trait_02.png", 
        tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Zlo0xBHOBte3IGPo8SY9XUcGes.png", 
        tname: "咒术师", 
        ticon: "", 
        lvl: "Lv28", 
        content: "下次咏唱的闪雷、震雷、暴雷、霹雷在命中时额外追加持续伤害总量的伤害，并且咏唱时间与消耗魔力均为0<BR>持续时间：18秒<BR>发动条件：闪雷、暴雷的持续伤害起效时（发动几率10%）或震雷、霹雷的持续伤害起效时（发动几率3%）", 
        change: ""
    }, 
    {
        name: "技能效果提高II", 
        ndes: "", 
        pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Trait_03.png", 
        tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Zlo0xBHOBte3IGPo8SY9XUcGes.png", 
        tname: "咒术师", 
        ticon: "", 
        lvl: "Lv40", 
        content: "除自动攻击外的技能造成的伤害提高至基本值的1.3倍，恢复技能的恢复量也提高至基本值的1.3倍", 
        change: ""
    }, 
    {
        name: "火苗", 
        ndes: "", 
        pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Trait_04.png", 
        tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Zlo0xBHOBte3IGPo8SY9XUcGes.png", 
        tname: "咒术师", 
        ticon: "", 
        lvl: "Lv42", 
        content: "下次咏唱爆炎时不需要咏唱时间也不会消耗魔力<BR>持续时间：18秒<BR>发动条件：火炎（发动几率40%）", 
        change: ""
    }, 
    {
        name: "闪雷精通", 
        ndes: "通过特职任务获得", 
        pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Trait_05.png", 
        tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/7JuT00VSwaFqTfcTYUCUnGPFQE.png", 
        tname: "黑魔法师", 
        ticon: "", 
        lvl: "Lv45", 
        content: "闪雷变为暴雷", 
        change: ""
    }, 
    {
        name: "闪雷精通II", 
        ndes: "", 
        pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Trait_06.png", 
        tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/7JuT00VSwaFqTfcTYUCUnGPFQE.png", 
        tname: "黑魔法师", 
        ticon: "", 
        lvl: "Lv64", 
        content: "震雷变为霹雷", 
        change: ""
    }, 
    {
        name: "灵极心效果提高", 
        ndes: "", 
        pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Trait_07.png", 
        tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/7JuT00VSwaFqTfcTYUCUnGPFQE.png", 
        tname: "黑魔法师", 
        ticon: "", 
        lvl: "Lv68", 
        content: "核爆的消耗魔力减为2/3<BR>发动时消耗全部灵极心<BR>发动条件：灵极心状态下", 
        change: ""
    }, 
    {
        name: "玄冰效果提高", 
        ndes: "", 
        pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Trait_08.png", 
        tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/7JuT00VSwaFqTfcTYUCUnGPFQE.png", 
        tname: "黑魔法师", 
        ticon: "", 
        lvl: "Lv68", 
        content: "对自身附加1档灵极心状态<BR>发动条件：玄冰", 
        change: ""
    }, 
    {
        name: "天语效果提高", 
        ndes: "通过特职任务获得", 
        pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Trait_09.png", 
        tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/7JuT00VSwaFqTfcTYUCUnGPFQE.png", 
        tname: "黑魔法师", 
        ticon: "", 
        lvl: "Lv70", 
        content: "对自身附加通晓状态<BR>发动条件：令天语状态持续30秒<BR>另外，天语的效果量提高到10%", 
        change: ""
    }, 
    {
        name: "极性精通", 
        ndes: "", 
        pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Trait_10.png", 
        tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/7JuT00VSwaFqTfcTYUCUnGPFQE.png", 
        tname: "黑魔法师", 
        ticon: "", 
        lvl: "Lv72", 
        content: "当自身的星极火或灵极冰达到最高档数时，相反属性的魔法将不消耗魔力<br>但不适用于核爆", 
        change: ""
    }, 
    {
        name: "激情咏唱效果提高", 
        ndes: "", 
        pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Trait_11.png", 
        tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/7JuT00VSwaFqTfcTYUCUnGPFQE.png", 
        tname: "黑魔法师", 
        ticon: "", 
        lvl: "Lv74", 
        content: "激情咏唱的复唱时间缩短到30秒", 
        change: ""
    }, 
    {
        name: "天语效果提高II", 
        ndes: "", 
        pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Trait_12.png", 
        tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/7JuT00VSwaFqTfcTYUCUnGPFQE.png", 
        tname: "黑魔法师", 
        ticon: "", 
        lvl: "Lv78", 
        content: "天语的效果量提高到15%", 
        change: ""
    }, 
    {
        name: "通晓效果提高", 
        ndes: "", 
        pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Trait_13.png", 
        tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/7JuT00VSwaFqTfcTYUCUnGPFQE.png", 
        tname: "黑魔法师", 
        ticon: "", 
        lvl: "Lv80", 
        content: "通晓可以积累到2档", 
        change: ""
    }
];

  ngOnInit(): void {
  }

}
