import { Component, OnInit } from '@angular/core';

@Component({
    selector: 'app-black-mage',
    templateUrl: './black-mage.component.html',
    styleUrls: ['./black-mage.component.css']
})
export class BlackMageComponent implements OnInit {

    constructor() { }

    today: Date = new Date();

    skills: any[] = [
        {
            isDisabled: "false",
            name: "冰结",
            ndes: "",
            pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Action_01.png",
            tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Zlo0xBHOBte3IGPo8SY9XUcGes.png",
            tname: "咒术师",
            ticon: "",
            lvl: "Lv1",
            classification: "魔法",
            cast: "2.5秒",
            recast: "2.5秒",
            cost: "魔力400",
            distant: "25",
            range: "0",
            rangeType: "zero",
            content: "对目标发动冰属性魔法攻击　威力：180<BR>追加效果：灵极冰　持续时间：15秒<BR>在处于星极火状态时只会解除该状态<BR>持续时间：15秒",
            change: ""
        },
        {
            isDisabled: "false",
            name: "火炎",
            ndes: "",
            pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Action_02.png",
            tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Zlo0xBHOBte3IGPo8SY9XUcGes.png",
            tname: "咒术师",
            ticon: "",
            lvl: "Lv2",
            classification: "魔法",
            cast: "2.5秒",
            recast: "2.5秒",
            cost: "魔力800",
            distant: "25",
            range: "0",
            rangeType: "zero",
            content: "对目标发动火属性魔法攻击　威力：180<BR>追加效果：星极火　持续时间：15秒<BR>在处于灵极冰状态时只会解除该状态<BR>追加效果（发动几率40%）：下次发动爆炎不消耗魔力，同时也没有咏唱时间　持续时间：30秒",
            change: "火苗的持续时间从18秒变更为30秒"
        },
        {
            isDisabled: "false",
            name: "星灵移位",
            ndes: "",
            pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Action_03.png",
            tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Zlo0xBHOBte3IGPo8SY9XUcGes.png",
            tname: "咒术师",
            ticon: "",
            lvl: "Lv4",
            classification: "能力",
            cast: "即时",
            recast: "5秒",
            cost: "-",
            distant: "0",
            range: "0",
            rangeType: "zero",
            content: "自身处于星极火或灵极冰的状态时迅速切换到另一状态的初级阶段",
            change: ""
        },
        {
            isDisabled: "false",
            name: "闪雷",
            ndes: "",
            pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Action_04.png",
            tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Zlo0xBHOBte3IGPo8SY9XUcGes.png",
            tname: "咒术师",
            ticon: "",
            lvl: "Lv6",
            classification: "魔法",
            cast: "2.5秒",
            recast: "2.5秒",
            cost: "魔力200",
            distant: "25",
            range: "0",
            rangeType: "zero",
            content: "对目标发动雷属性魔法攻击　威力：30<BR>追加效果：雷属性持续伤害<BR>威力：35　持续时间：21秒<BR>自身对目标附加的雷系魔法持续伤害效果同时只能存在一种<BR>追加效果（持续伤害每次起效时，发动几率10%）：<BR>下次发动的雷系魔法咏唱时间与消耗魔力均为0<BR>且命中时的威力会加算持续伤害的总和<BR>持续时间：40秒",
            change: "持续伤害威力从40变更为35<BR>持续伤害的持续时间从18秒变更为21秒<BR>雷属性魔法效果提高的持续时间从18秒变更为40秒"
        },
        {
            isDisabled: "false",
            name: "冰冻",
            ndes: "",
            pic: "../../assets/BLM/冰2.png",
            tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Zlo0xBHOBte3IGPo8SY9XUcGes.png",
            tname: "咒术师",
            ticon: "",
            lvl: "Lv12",
            classification: "魔法",
            cast: "3秒",
            recast: "2.5秒",
            cost: "魔力800",
            distant: "25",
            range: "5",
            rangeType: "circle",
            content: "对目标及其周围的敌人发动冰属性范围魔法攻击　威力：100<BR>追加效果：灵极冰最大档数　持续时间：15秒<BR>在处于星极火状态时会同时解除该状态<BR>持续时间：15秒",
            change: "威力从50变更为100<BR>效果从「对周围的敌人发动冰属性范围魔法攻击」变更为「对目标及其周围的敌人发动冰属性范围魔法攻击」<BR>追加效果从「追加效果：灵极冰　持续时间：15秒」变更为「追加效果：灵极冰最大档数」<BR>距离从「0米」变更为「25米」<BR>咏唱时间从「2秒」变更为「3秒」"
        },
        {
            isDisabled: "false",
            name: "崩溃",
            ndes: "通过特职任务获得",
            pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Action_07.png",
            tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Zlo0xBHOBte3IGPo8SY9XUcGes.png",
            tname: "咒术师",
            ticon: "",
            lvl: "Lv15",
            classification: "魔法",
            cast: "即时",
            recast: "2.5秒",
            cost: "魔力800",
            distant: "25",
            range: "0",
            rangeType: "zero",
            content: "对目标发动无属性魔法攻击　威力：100<BR>追加效果（发动几率20%）：伤害变为2倍",
            change: ""
        },
        {
            isDisabled: "false",
            name: "烈炎",
            ndes: "",
            pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Action_08.png",
            tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Zlo0xBHOBte3IGPo8SY9XUcGes.png",
            tname: "咒术师",
            ticon: "",
            lvl: "Lv18",
            classification: "魔法",
            cast: "3秒",
            recast: "2.5秒",
            cost: "魔力1500",
            distant: "25",
            range: "5",
            rangeType: "circle",
            content: "对目标及其周围的敌人发动火属性范围魔法攻击　威力：100<BR>追加效果：星极火最大档数　持续时间：15秒<BR>在处于灵极冰状态时会同时解除该状态<BR>持续时间：15秒<BR>星极火状态时追加效果：核爆效果提高<BR>该状态在星极火状态结束时会被解除",
            change: "威力从80变更为100<BR>追加效果从「星极火　持续时间：15秒  在处于灵极冰状态时只会解除该状态  持续时间：15秒」变更为「星极火最大档数　持续时间：15秒  在处于灵极冰状态时会同时解除该状态」<BR>新增效果「星极火状态时追加效果：核爆效果提高<BR>该状态在星极火状态结束时会被解除」"
        },
        {
            isDisabled: "false",
            name: "震雷",
            ndes: "",
            pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Action_09.png",
            tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Zlo0xBHOBte3IGPo8SY9XUcGes.png",
            tname: "咒术师",
            ticon: "",
            lvl: "Lv26",
            classification: "魔法",
            cast: "2.5秒",
            recast: "2.5秒",
            cost: "魔力400",
            distant: "25",
            range: "5",
            rangeType: "circle",
            content: "对目标及其周围敌人发动雷属性范围魔法攻击　威力：50<BR>追加效果：雷属性持续伤害<BR>威力：15　持续时间：18秒<BR>自身对目标附加的雷系魔法持续伤害效果同时只能存在一种<BR>追加效果（持续伤害每次起效时，发动几率3%）：下次发动的雷系魔法咏唱时间与消耗魔力均为0<BR>且命中时的威力会加算持续伤害的总和<BR>持续时间：40秒",
            change: "威力从30变更为50<BR>持续伤害的威力从30变更为15<BR>持续伤害的持续时间从12秒变更为18秒<BR>雷属性魔法效果提高的持续时间从18秒变更为40秒<BR>咏唱时间从3秒变更为2.5秒"
        },
        {
            isDisabled: "false",
            name: "魔罩",
            ndes: "通过特职任务获得",
            pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Action_10.png",
            tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Zlo0xBHOBte3IGPo8SY9XUcGes.png",
            tname: "咒术师",
            ticon: "",
            lvl: "Lv30",
            classification: "能力",
            cast: "即时",
            recast: "120秒",
            cost: "-",
            distant: "0",
            range: "0",
            rangeType: "zero",
            content: "为自身张开一个防护罩，在一定时间内能抵消相当于最大体力30%的伤害量<BR>抵消的伤害量超过上限时防护罩自动消失<BR>持续时间：20秒",
            change: ""
        },
        {
            isDisabled: "false",
            name: "魔泉",
            ndes: "通过特职任务获得",
            pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Action_11.png",
            tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/7JuT00VSwaFqTfcTYUCUnGPFQE.png",
            tname: "黑魔法师",
            ticon: "",
            lvl: "Lv30",
            classification: "能力",
            cast: "即时",
            recast: "120秒",
            cost: "-",
            distant: "0",
            range: "0",
            rangeType: "zero",
            content: "恢复最大魔力的30%",
            change: "复唱时间从180秒变更为120秒"
        },
        {
            isDisabled: "false",
            name: "爆炎",
            ndes: "",
            pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Action_12.png",
            tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Zlo0xBHOBte3IGPo8SY9XUcGes.png",
            tname: "咒术师",
            ticon: "",
            lvl: "Lv35",
            classification: "魔法",
            cast: "3.5秒",
            recast: "2.5秒",
            cost: "魔力2000",
            distant: "25",
            range: "0",
            rangeType: "zero",
            content: "对目标发动火属性魔法攻击　威力：240<BR>追加效果：星极火最大档数　持续时间：15秒<BR>在处于灵极冰状态时会同时解除该状态",
            change: "习得等级从34变更为35"
        },
        {
            isDisabled: "false",
            name: "冰封",
            ndes: "通过特职任务获得",
            pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Action_14.png",
            tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/7JuT00VSwaFqTfcTYUCUnGPFQE.png",
            tname: "黑魔法师",
            ticon: "",
            lvl: "Lv35",
            classification: "魔法",
            cast: "3.5秒",
            recast: "2.5秒",
            cost: "魔力800",
            distant: "25",
            range: "0",
            rangeType: "zero",
            content: "对目标发动冰属性魔法攻击　威力：240<BR>追加效果：灵极冰最大档数　持续时间：15秒<BR>在处于星极火状态时会同时解除该状态",
            change: "习得等级从40变更为35"
        },
        {
            isDisabled: "false",
            name: "玄冰",
            ndes: "通过特职任务获得",
            pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Action_13.png",
            tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/7JuT00VSwaFqTfcTYUCUnGPFQE.png",
            tname: "黑魔法师",
            ticon: "",
            lvl: "Lv40",
            classification: "魔法",
            cast: "2.8秒",
            recast: "2.5秒",
            cost: "魔力1000",
            distant: "25",
            range: "5",
            rangeType: "circle",
            content: "对目标及其周围的敌人发动冰属性范围魔法攻击　威力：120<BR>追加效果：3档灵极心<BR>灵极心效果：抵消星极火状态中发动火系魔法增加的魔力消耗<BR>另外，发动核爆时会消耗全部的灵极心将魔力消耗降为2/3<BR>发动条件：灵极冰状态中",
            change: "习得等级从35变更为40<BR>威力从100变更为120<BR>咏唱时间从2.5秒变更为2.8秒<BR>删除追加效果「灵极冰最大档数　持续时间：15秒<BR>在处于星极火状态时会同时解除该状态」<BR>追加效果从「1档灵极心」变更为「3档灵极心」<BR>新增「发动条件：灵极冰状态中」"
        },
        {
            isDisabled: "false",
            name: "暴雷",
            ndes: "通过特职任务获得",
            pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Action_15.png",
            tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/7JuT00VSwaFqTfcTYUCUnGPFQE.png",
            tname: "黑魔法师",
            ticon: "",
            lvl: "Lv45",
            classification: "魔法",
            cast: "2.5秒",
            recast: "2.5秒",
            cost: "魔力400",
            distant: "25",
            range: "0",
            rangeType: "zero",
            content: "对目标发动雷属性魔法攻击　威力：50<BR>追加效果：雷属性持续伤害<BR>威力：35　持续时间：30秒<BR>自身对目标附加的雷系魔法持续伤害效果同时只能存在一种<BR>追加效果（持续伤害每次起效时，发动几率10%）：<BR>下次发动的雷系魔法咏唱时间与消耗魔力均为0<BR>且命中时的威力会加算持续伤害的总和<BR>持续时间：40秒",
            change: "威力从70变更为50<BR>持续伤害的威力从40变更为35<BR>持续伤害的持续时间从24秒变更为30秒<BR>雷属性魔法效果提高的持续时间从18秒变更为40秒"
        },
        {
            isDisabled: "false",
            name: "以太步",
            ndes: "",
            pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Action_16.png",
            tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/7JuT00VSwaFqTfcTYUCUnGPFQE.png",
            tname: "黑魔法师",
            ticon: "",
            lvl: "Lv50",
            classification: "能力",
            cast: "即时",
            recast: "10秒",
            cost: "-",
            distant: "25",
            range: "0",
            rangeType: "zero",
            content: "指定一名队员为目标，自身快速移动到目标身边<BR>止步状态下无法发动",
            change: ""
        },
        {
            isDisabled: "false",
            name: "核爆",
            ndes: "通过特职任务获得",
            pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Action_17.png",
            tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Zlo0xBHOBte3IGPo8SY9XUcGes.png",
            tname: "咒术师",
            ticon: "",
            lvl: "Lv50",
            classification: "魔法",
            cast: "4秒",
            recast: "2.5秒",
            cost: "全部魔力",
            distant: "25",
            range: "5",
            rangeType: "circle",
            content: "对目标及其周围的敌人发动火属性范围魔法攻击　威力：220<BR>攻击复数敌人时，对目标之外的敌人威力降低40%<BR>核爆效果提高时威力：280<BR>追加效果：星极火最大档数　持续时间：15秒<BR>发动条件：星极火状态中",
            change: "威力从260变更为220<BR> 新增核爆效果提高时威力：280<BR>删除「在处于灵极冰状态时会同时解除该状态」的效果<br>新增「发动条件：星极火状态中」"
        },
        {
            isDisabled: "false",
            name: "黑魔纹",
            ndes: "通过特职任务获得",
            pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Action_18.png",
            tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/7JuT00VSwaFqTfcTYUCUnGPFQE.png",
            tname: "黑魔法师",
            ticon: "",
            lvl: "Lv52",
            classification: "能力",
            cast: "即时",
            recast: "120秒",
            cost: "-",
            distant: "0",
            range: "3",
            rangeType: "circle",
            content: "在自身脚下产生黑魔纹<BR>黑魔纹效果：自身的自动攻击间隔、魔法的咏唱及复唱时间缩短15%<BR>持续时间：30秒",
            change: "复唱时间从90秒变更为120秒"
        },
        {
            isDisabled: "false",
            name: "激情咏唱",
            ndes: "通过特职任务获得",
            pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Action_19.png",
            tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/7JuT00VSwaFqTfcTYUCUnGPFQE.png",
            tname: "黑魔法师",
            ticon: "",
            lvl: "Lv54",
            classification: "能力",
            cast: "即时",
            recast: "30秒",
            cost: "-",
            distant: "0",
            range: "0",
            rangeType: "zero",
            content: "效果时间内，自身发动的1次“崩溃”或“火炎”或“悖论”或“雷系魔法”必定触发“崩溃的追加效果”“火苗”“雷云”<BR>持续时间：30秒<BR>积蓄次数：2",
            change: "新增对悖论的效果<BR>新增积蓄次数：2<BR>持续时间从15秒变更为30秒"
        },
        {
            isDisabled: "false",
            name: "冰澈",
            ndes: "通过特职任务获得",
            pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Action_21.png",
            tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/7JuT00VSwaFqTfcTYUCUnGPFQE.png",
            tname: "黑魔法师",
            ticon: "",
            lvl: "Lv58",
            classification: "魔法",
            cast: "2.5秒",
            recast: "2.5秒",
            cost: "魔力800",
            distant: "25",
            range: "0",
            rangeType: "zero",
            content: "对目标发动冰属性魔法攻击　威力：300<BR>追加效果：3档灵极心<BR>灵极心效果：抵消星极火状态中发动火系魔法增加的魔力消耗<BR>另外，发动核爆时会消耗全部的灵极心将魔力消耗降为2/3<BR>发动条件：灵极冰状态中",
            change: "发动条件从「天语及灵极冰状态中」变更为「灵极冰状态中」<BR>咏唱时间从2.8秒变更为2.5秒"
        },
        {
            isDisabled: "false",
            name: "炽炎",
            ndes: "",
            pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Action_22.png",
            tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/7JuT00VSwaFqTfcTYUCUnGPFQE.png",
            tname: "黑魔法师",
            ticon: "",
            lvl: "Lv60",
            classification: "魔法",
            cast: "2.8秒",
            recast: "2.5秒",
            cost: "魔力800",
            distant: "25",
            range: "0",
            rangeType: "zero",
            content: "对目标发动火属性魔法攻击　威力：300<BR>发动条件：星极火状态中",
            change: "发动条件从「天语及星极火状态中」变更为「星极火状态中」"
        },
        {
            isDisabled: "false",
            name: "魔纹步",
            ndes: "",
            pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Action_23.png",
            tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/7JuT00VSwaFqTfcTYUCUnGPFQE.png",
            tname: "黑魔法师",
            ticon: "",
            lvl: "Lv62",
            classification: "能力",
            cast: "即时",
            recast: "3秒",
            cost: "-",
            distant: "25",
            range: "0",
            rangeType: "zero",
            content: "快速移动到自身留下的黑魔纹中心<BR>止步状态下无法发动",
            change: ""
        },
        {
            isDisabled: "false",
            name: "霹雷",
            ndes: "",
            pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Action_24.png",
            tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/7JuT00VSwaFqTfcTYUCUnGPFQE.png",
            tname: "黑魔法师",
            ticon: "",
            lvl: "Lv64",
            classification: "魔法",
            cast: "2.5秒",
            recast: "2.5秒",
            cost: "魔力400",
            distant: "25",
            range: "5",
            rangeType: "circle",
            content: "对目标及其周围敌人发动雷属性范围魔法攻击　威力：50<BR>追加效果：雷属性持续伤害<BR>威力：20　持续时间：18秒<BR>自身对目标附加的雷系魔法持续伤害效果同时只能存在一种<BR>追加效果（持续伤害每次起效时，发动几率3%）：下次发动的雷系魔法咏唱时间与消耗魔力均为0<BR>且命中时的威力会加算持续伤害的总和<BR>持续时间：40秒",
            change: "持续伤害的威力从30变更为20<BR>雷属性魔法效果提高的持续时间从18秒变更为40秒<BR>咏唱时间从3秒变更为2.5秒<BR>消费从「魔力800」变更为「魔力400」"
        },
        {
            isDisabled: "false",
            name: "三连咏唱",
            ndes: "",
            pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Action_25.png",
            tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/7JuT00VSwaFqTfcTYUCUnGPFQE.png",
            tname: "黑魔法师",
            ticon: "",
            lvl: "Lv66",
            classification: "能力",
            cast: "即时",
            recast: "60秒",
            cost: "-",
            distant: "0",
            range: "0",
            rangeType: "zero",
            content: "效果时间内，前3次咏唱的魔法没有任何咏唱时间　持续时间：15秒<BR>积蓄次数：2",
            change: "新增积蓄次数：2"
        },
        {
            isDisabled: "false",
            name: "秽浊",
            ndes: "通过特职任务获得",
            pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Action_26.png",
            tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/7JuT00VSwaFqTfcTYUCUnGPFQE.png",
            tname: "黑魔法师",
            ticon: "",
            lvl: "Lv70",
            classification: "魔法",
            cast: "即时",
            recast: "2.5秒",
            cost: "",
            distant: "25",
            range: "5",
            rangeType: "circle",
            content: "对目标及其周围敌人发动无属性范围魔法攻击　威力：560<BR>攻击复数敌人时，对目标之外的敌人威力降低60%<BR>发动条件：通晓",
            change: "威力从650变更为560<BR>攻击复数敌人时，对目标之外的敌人威力降低从25%变更为60%<BR>咏唱时间从2.5秒变更为即时"
        },
        {
            isDisabled: "false",
            name: "绝望",
            ndes: "",
            pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Action_27.png",
            tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/7JuT00VSwaFqTfcTYUCUnGPFQE.png",
            tname: "黑魔法师",
            ticon: "",
            lvl: "Lv72",
            classification: "魔法",
            cast: "3秒",
            recast: "2.5秒",
            cost: "全部魔力",
            distant: "25",
            range: "0",
            rangeType: "zero",
            content: "对目标发动火属性魔法攻击　威力：340<BR>追加效果：星极火最大档数　持续时间：15秒<BR>发动条件：星极火状态中",
            change: "威力从380变更为340<BR>发动条件从「天语及星极火状态中」变更为「星极火状态中」"
        },
        {
            isDisabled: "false",
            name: "灵极魂",
            ndes: "",
            pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Action_28.png",
            tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/7JuT00VSwaFqTfcTYUCUnGPFQE.png",
            tname: "黑魔法师",
            ticon: "",
            lvl: "Lv76",
            classification: "魔法",
            cast: "即时",
            recast: "2.5秒",
            cost: "-",
            distant: "0",
            range: "0",
            rangeType: "zero",
            content: "对自身附加灵极冰状态及1档灵极心<BR>灵极心效果：抵消星极火状态中发动火系魔法增加的魔力消耗<BR>另外，发动核爆时会消耗全部的灵极心将魔力消耗降为2/3<BR>发动条件：灵极冰状态中",
            change: "发动条件从「天语及灵极冰状态中」变更为「灵极冰状态中」"
        },
        {
            isDisabled: "false",
            name: "异言",
            ndes: "",
            pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Action_29.png",
            tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/7JuT00VSwaFqTfcTYUCUnGPFQE.png",
            tname: "黑魔法师",
            ticon: "",
            lvl: "Lv80",
            classification: "魔法",
            cast: "即时",
            recast: "2.5秒",
            cost: "",
            distant: "25",
            range: "0",
            rangeType: "zero",
            content: "对目标发动无属性魔法攻击　威力：660<BR>发动条件：通晓",
            change: "威力从750变更为660"
        },
        {
            isDisabled: "false",
            name: "High Fire II<BR>高烈炎",
            ndes: "",
            pic: "../../assets/BLM/高火2.png",
            tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/7JuT00VSwaFqTfcTYUCUnGPFQE.png",
            tname: "黑魔法师",
            ticon: "",
            lvl: "Lv82",
            classification: "魔法",
            cast: "3秒",
            recast: "2.5秒",
            cost: "魔力1500",
            distant: "25",
            range: "5",
            rangeType: "circle",
            content: "对目标及其周围的敌人发动火属性范围魔法攻击<BR>威力：140<BR>追加效果：星极火最大档数<BR>持续时间：15秒<BR>在处于灵极冰状态时会同时解除该状态<BR>星极火状态时追加效果：核爆效果提高<BR>该状态在星极火状态结束时会被解除",
            change: "新增技能"
        },
        {
            isDisabled: "false",
            name: "High Blizzard II<br>高冰冻",
            ndes: "",
            pic: "../../assets/BLM/高冰2.png",
            tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/7JuT00VSwaFqTfcTYUCUnGPFQE.png",
            tname: "黑魔法师",
            ticon: "",
            lvl: "Lv82",
            classification: "魔法",
            cast: "3秒",
            recast: "2.5秒",
            cost: "魔力800",
            distant: "25",
            range: "5",
            rangeType: "circle",
            content: "对目标及其周围的敌人发动冰属性范围魔法攻击<BR>威力：140<BR>追加效果：灵极冰最大档数<BR>持续时间：15秒<BR>在处于星极火状态时会同时解除该状态",
            change: "新增技能"
        },
        {
            isDisabled: "false",
            name: "Amplifier<BR>扩音",
            ndes: "",
            pic: "../../assets/BLM/扩音.png",
            tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/7JuT00VSwaFqTfcTYUCUnGPFQE.png",
            tname: "黑魔法师",
            ticon: "",
            lvl: "Lv86",
            classification: "能力",
            cast: "即时",
            recast: "120秒",
            cost: "-",
            distant: "0",
            range: "0",
            rangeType: "zero",
            content: "对自身附加通晓状态<BR>发动条件：星极火或灵极冰状态中",
            change: "新增技能"
        },
        {
            isDisabled: "false",
            name: "Paradox<BR>悖论",
            ndes: "",
            pic: "../../assets/BLM/悖论.png",
            tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/7JuT00VSwaFqTfcTYUCUnGPFQE.png",
            tname: "黑魔法师",
            ticon: "",
            lvl: "Lv90",
            classification: "魔法",
            cast: "2.5秒",
            recast: "2.5秒",
            cost: "魔力1600",
            distant: "0",
            range: "0",
            rangeType: "zero",
            content: "对目标发动无属性魔法攻击 威力：500<BR>星极火状态时追加效果：星极火 持续时间：15秒<BR>追加效果（发动几率40%）：下次发动爆炎不消耗魔力，同时也没有咏唱时间 持续时间：30秒<BR>灵极冰状态时追加效果：灵极冰 持续时间：15秒<BR>该魔法不消耗魔力，同时也没有咏唱时间<BR>发动条件：悖论标记<BR>*该技能无法设置到热键栏",
            change: "新增技能"
        }
    ];


    roleSkills: any[] = [
        {
            isDisabled: "false",
            name: "昏乱",
            ndes: "",
            pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Magical Ranged DPS Role Action_01.png",
            tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/8Dnf8Wy9IyxIt21y6lrE5atKt0.png",
            tname: "远程魔法职业",
            ticon: [
                {
                    "url": "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/8Dnf8Wy9IyxIt21y6lrE5atKt0.png",
                    tname: "远程魔法职业"
                }
            ],
            lvl: "Lv8",
            classification: "能力",
            cast: "即时",
            recast: "90秒",
            cost: "-",
            distant: "25",
            range: "0",
            rangeType: "zero",
            content: "一定时间内，令目标的物理伤害降低5%，魔法伤害降低10% <BR>持续时间：10秒",
            change: "效果从「令目标的智力与精神降低10% 」变更为「令目标的物理伤害降低5%，魔法伤害降低10% 」"
        },
        {
            isDisabled: "false",
            name: "催眠",
            ndes: "",
            pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Action_05.png",
            tiurl: "",
            tname: "",
            ticon: [
                {
                    "url": "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/8Dnf8Wy9IyxIt21y6lrE5atKt0.png",
                    tname: "远程魔法职业"
                }
            ],
            lvl: "Lv10",
            classification: "魔法",
            cast: "2.5秒",
            recast: "2.5秒",
            cost: "800",
            distant: "30",
            range: "5",
            rangeType: "circle",
            content: "令目标及其周围的敌人陷入睡眠状态<BR>持续时间：30秒<BR>发动之后会停止自动攻击",
            change: "新增特性"
        },
        {
            isDisabled: "false",
            name: "即刻咏唱",
            ndes: "",
            pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Magical Ranged DPS Role Action_02.png",
            tiurl: "",
            tname: "",
            ticon: [
                {
                    "url": "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/V5xx3kfnREBO-2xWbTUW2Csy_Q.png",
                    tname: "治疗职业"
                },
                {
                    "url": "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/8Dnf8Wy9IyxIt21y6lrE5atKt0.png",
                    tname: "远程魔法职业"
                }
            ],
            lvl: "Lv18",
            classification: "能力",
            cast: "即时",
            recast: "60秒",
            cost: "-",
            distant: "0",
            range: "0",
            rangeType: "zero",
            content: "一定时间内，下次咏唱的魔法没有任何咏唱时间<BR>持续时间：10秒",
            change: ""
        },
        {
            isDisabled: "false",
            name: "醒梦",
            ndes: "",
            pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Magical Ranged DPS Role Action_03.png",
            tiurl: "",
            tname: "",
            ticon: [
                {
                    "url": "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/V5xx3kfnREBO-2xWbTUW2Csy_Q.png",
                    tname: "治疗职业"
                },
                {
                    "url": "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/8Dnf8Wy9IyxIt21y6lrE5atKt0.png",
                    tname: "远程魔法职业"
                }
            ],
            lvl: "Lv24",
            classification: "能力",
            cast: "即时",
            recast: "60秒",
            cost: "-",
            distant: "0",
            range: "0",
            rangeType: "zero",
            content: "持续恢复自身魔力<BR>效果量：55　持续时间：21秒",
            change: "效果量从50变更为55"
        },
        {
            isDisabled: "false",
            name: "沉稳咏唱",
            ndes: "",
            pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Magical Ranged DPS Role Action_04.png",
            tiurl: "",
            tname: "",
            ticon: [
                {
                    "url": "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/V5xx3kfnREBO-2xWbTUW2Csy_Q.png",
                    tname: "治疗职业"
                },
                {
                    "url": "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/8Dnf8Wy9IyxIt21y6lrE5atKt0.png",
                    tname: "远程魔法职业"
                }
            ],
            lvl: "Lv44",
            classification: "能力",
            cast: "即时",
            recast: "120秒",
            cost: "-",
            distant: "0",
            range: "0",
            rangeType: "zero",
            content: "一定时间内，咏唱的魔法不会被任何妨碍打断<BR>同时，令除特定攻击之外其他所有击退与吸引效果失效<BR>持续时间：6秒",
            change: ""
        }
    ];


    traits: any[] = [
        {
            isDisabled: "false",
            name: "极性精通",
            ndes: "",
            pic: "../../assets/BLM/极性精通.png",
            tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Zlo0xBHOBte3IGPo8SY9XUcGes.png",
            tname: "咒术师",
            ticon: "",
            lvl: "Lv1",
            classification: "",
            cast: "",
            recast: "",
            cost: "",
            distant: "",
            range: "",
            rangeType: "zero",
            content: "咏唱部分火属性和冰属性魔法时对自身附加星极火和灵极冰效果<BR>最大档数：1   持续时间：15秒<BR>当自身在星极火或灵极冰状态时，相反属性的魔法将不消耗魔力<BR>但不适用于核爆",
            change: "习得等级从72变更为1<BR>更新效果"
        },
        {
            isDisabled: "false",
            name: "技能效果提高",
            ndes: "",
            pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Trait_01.png",
            tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Zlo0xBHOBte3IGPo8SY9XUcGes.png",
            tname: "咒术师",
            ticon: "",
            lvl: "Lv20",
            classification: "",
            cast: "",
            recast: "",
            cost: "",
            distant: "",
            range: "",
            rangeType: "zero",
            content: "除自动攻击外的技能造成的伤害提高至基本值的1.1倍，恢复技能的恢复量也提高至基本值的1.1倍",
            change: "删除「星极火和灵极冰可以积累到2档」"
        },
        {
            isDisabled: "false",
            name: "极性精通II",
            ndes: "",
            pic: "../../assets/BLM/极性精通2.png",
            tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Zlo0xBHOBte3IGPo8SY9XUcGes.png",
            tname: "咒术师",
            ticon: "",
            lvl: "Lv20",
            classification: "",
            cast: "",
            recast: "",
            cost: "",
            distant: "",
            range: "",
            rangeType: "zero",
            content: "星极火和灵极冰可以积累到2档",
            change: "新增特性"
        },
        {
            isDisabled: "false",
            name: "雷云",
            ndes: "",
            pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Trait_02.png",
            tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Zlo0xBHOBte3IGPo8SY9XUcGes.png",
            tname: "咒术师",
            ticon: "",
            lvl: "Lv28",
            classification: "",
            cast: "",
            recast: "",
            cost: "",
            distant: "",
            range: "",
            rangeType: "zero",
            content: "下次咏唱的闪雷、震雷、暴雷、霹雷在命中时额外追加持续伤害总量的伤害，并且咏唱时间与消耗魔力均为0<BR>持续时间：40秒<BR>发动条件：闪雷、暴雷的持续伤害起效时（发动几率10%）或震雷、霹雷的持续伤害起效时（发动几率3%）",
            change: "持续时间从18秒变更为40秒"
        },
        {
            isDisabled: "false",
            name: "极性精通III",
            ndes: "",
            pic: "../../assets/BLM/极性精通3.png",
            tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Zlo0xBHOBte3IGPo8SY9XUcGes.png",
            tname: "咒术师",
            ticon: "",
            lvl: "Lv35",
            classification: "",
            cast: "",
            recast: "",
            cost: "",
            distant: "",
            range: "",
            rangeType: "zero",
            content: "星极火和灵极冰可以积累到3档<br>咏唱烈炎或冰冻时可附加到星极火或灵极冰的最大档数",
            change: "新增特性"
        },
        {
            isDisabled: "false",
            name: "技能效果提高II",
            ndes: "",
            pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Trait_03.png",
            tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Zlo0xBHOBte3IGPo8SY9XUcGes.png",
            tname: "咒术师",
            ticon: "",
            lvl: "Lv40",
            classification: "",
            cast: "",
            recast: "",
            cost: "",
            distant: "",
            range: "",
            rangeType: "zero",
            content: "除自动攻击外的技能造成的伤害提高至基本值的1.3倍，恢复技能的恢复量也提高至基本值的1.3倍",
            change: "删除「在3档的状态下，相反属性的魔法咏唱时间减半」"
        },
        {
            isDisabled: "false",
            name: "火苗",
            ndes: "",
            pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Trait_04.png",
            tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Zlo0xBHOBte3IGPo8SY9XUcGes.png",
            tname: "咒术师",
            ticon: "",
            lvl: "Lv42",
            classification: "",
            cast: "",
            recast: "",
            cost: "",
            distant: "",
            range: "",
            rangeType: "zero",
            content: "下次咏唱爆炎时不需要咏唱时间也不会消耗魔力<BR>持续时间：30秒<BR>发动条件：火炎（发动几率40%）",
            change: "持续时间从18秒变更为30秒"
        },
        {
            isDisabled: "false",
            name: "闪雷精通",
            ndes: "通过特职任务获得",
            pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Trait_05.png",
            tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/7JuT00VSwaFqTfcTYUCUnGPFQE.png",
            tname: "黑魔法师",
            ticon: "",
            lvl: "Lv45",
            classification: "",
            cast: "",
            recast: "",
            cost: "",
            distant: "",
            range: "",
            rangeType: "zero",
            content: "闪雷变为暴雷",
            change: ""
        },
        {
            isDisabled: "false",
            name: "天语",
            ndes: "",
            pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Action_20.png",
            tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/Zlo0xBHOBte3IGPo8SY9XUcGes.png",
            tname: "黑魔法师",
            ticon: "",
            lvl: "Lv56",
            classification: "",
            cast: "",
            recast: "",
            cost: "",
            distant: "",
            range: "",
            rangeType: "zero",
            content: "自身发动魔法攻击造成的伤害提高5%<BR>发动条件：星极火或灵极冰状态中<BR>同时，星极火状态中烈炎起效时，对自身附加「核爆效果提高」状态，该状态在星极火状态结束时会被解除",
            change: "新增特性"
        },
        {
            isDisabled: "false",
            name: "闪雷精通II",
            ndes: "",
            pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Trait_06.png",
            tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/7JuT00VSwaFqTfcTYUCUnGPFQE.png",
            tname: "黑魔法师",
            ticon: "",
            lvl: "Lv64",
            classification: "",
            cast: "",
            recast: "",
            cost: "",
            distant: "",
            range: "",
            rangeType: "zero",
            content: "震雷变为霹雷",
            change: ""
        },
        {
            isDisabled: "false",
            name: "玄冰效果提高",
            ndes: "",
            pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Trait_08.png",
            tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/7JuT00VSwaFqTfcTYUCUnGPFQE.png",
            tname: "黑魔法师",
            ticon: "",
            lvl: "Lv58",
            classification: "",
            cast: "",
            recast: "",
            cost: "",
            distant: "",
            range: "",
            rangeType: "zero",
            content: "对自身附加3档灵极心状态<BR>发动条件：玄冰",
            change: "习得等级从68变更为58<BR>效果从「对自身附加1档灵极心状态」变更为「对自身附加3档灵极心状态」"
        },
        {
            isDisabled: "false",
            name: "天语效果提高",
            ndes: "通过特职任务获得",
            pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Trait_09.png",
            tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/7JuT00VSwaFqTfcTYUCUnGPFQE.png",
            tname: "黑魔法师",
            ticon: "",
            lvl: "Lv70",
            classification: "",
            cast: "",
            recast: "",
            cost: "",
            distant: "",
            range: "",
            rangeType: "zero",
            content: "对自身附加通晓状态<BR>发动条件：令天语状态持续30秒<BR>另外，天语的效果量提高到10%",
            change: ""
        },
        {
            isDisabled: "false",
            name: "激情咏唱效果提高",
            ndes: "",
            pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Trait_11.png",
            tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/7JuT00VSwaFqTfcTYUCUnGPFQE.png",
            tname: "黑魔法师",
            ticon: "",
            lvl: "Lv74",
            classification: "",
            cast: "",
            recast: "",
            cost: "",
            distant: "",
            range: "",
            rangeType: "zero",
            content: "激情咏唱的复唱时间缩短到30秒",
            change: ""
        },
        {
            isDisabled: "false",
            name: "天语效果提高II",
            ndes: "",
            pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Trait_12.png",
            tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/7JuT00VSwaFqTfcTYUCUnGPFQE.png",
            tname: "黑魔法师",
            ticon: "",
            lvl: "Lv78",
            classification: "",
            cast: "",
            recast: "",
            cost: "",
            distant: "",
            range: "",
            rangeType: "zero",
            content: "天语的效果量提高到15%",
            change: ""
        },
        {
            isDisabled: "false",
            name: "通晓效果提高",
            ndes: "",
            pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Trait_13.png",
            tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/7JuT00VSwaFqTfcTYUCUnGPFQE.png",
            tname: "黑魔法师",
            ticon: "",
            lvl: "Lv80",
            classification: "",
            cast: "",
            recast: "",
            cost: "",
            distant: "",
            range: "",
            rangeType: "zero",
            content: "通晓可以积累到2档",
            change: ""
        },
        {
            isDisabled: "false",
            name: "秽浊效果提高",
            ndes: "",
            pic: "../../assets/BLM/秽浊效果提高.png",
            tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/7JuT00VSwaFqTfcTYUCUnGPFQE.png",
            tname: "黑魔法师",
            ticon: "",
            lvl: "Lv80",
            classification: "",
            cast: "",
            recast: "",
            cost: "",
            distant: "",
            range: "",
            rangeType: "zero",
            content: "咏唱秽浊时不需要咏唱时间",
            change: "新增特性"
        },
        {
            isDisabled: "false",
            name: "极性精通IV",
            ndes: "",
            pic: "../../assets/BLM/极性精通4.png",
            tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/7JuT00VSwaFqTfcTYUCUnGPFQE.png",
            tname: "黑魔法师",
            ticon: "",
            lvl: "Lv82",
            classification: "",
            cast: "",
            recast: "",
            cost: "",
            distant: "",
            range: "",
            rangeType: "zero",
            content: "烈炎和冰冻变为高烈炎和高冰冻",
            change: "新增特性"
        },
        {
            isDisabled: "false",
            name: "魔泉效果提高",
            ndes: "",
            pic: "../../assets/BLM/魔泉效果提高.png",
            tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/7JuT00VSwaFqTfcTYUCUnGPFQE.png",
            tname: "黑魔法师",
            ticon: "",
            lvl: "Lv84",
            classification: "",
            cast: "",
            recast: "",
            cost: "",
            distant: "",
            range: "",
            rangeType: "zero",
            content: "魔泉的复唱时间缩短到120秒",
            change: "新增特性"
        },
        {
            isDisabled: "false",
            name: "天语效果提高III",
            ndes: "",
            pic: "../../assets/BLM/天语效果提高3.png",
            tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/7JuT00VSwaFqTfcTYUCUnGPFQE.png",
            tname: "黑魔法师",
            ticon: "",
            lvl: "Lv86",
            classification: "",
            cast: "",
            recast: "",
            cost: "",
            distant: "",
            range: "",
            rangeType: "zero",
            content: "天语的效果量提高到20%",
            change: "新增特性"
        },
        {
            isDisabled: "false",
            name: "激情咏唱效果提高II",
            ndes: "",
            pic: "https://static.web.sdo.com/jijiamobile/pic/ff14/20190917jobguid/Black Mage/Trait_11.png",
            tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/7JuT00VSwaFqTfcTYUCUnGPFQE.png",
            tname: "黑魔法师",
            ticon: "",
            lvl: "Lv88",
            classification: "",
            cast: "",
            recast: "",
            cost: "",
            distant: "",
            range: "",
            rangeType: "zero",
            content: "激情咏唱变为积蓄技能<BR>积蓄次数：2",
            change: "新增特性"
        },
        {
            isDisabled: "false",
            name: "极性精通V",
            ndes: "",
            pic: "../../assets/BLM/极性精通5.png",
            tiurl: "https://static.web.sdo.com/jijiamobile/pic/ff14/20170901battle/7JuT00VSwaFqTfcTYUCUnGPFQE.png",
            tname: "黑魔法师",
            ticon: "",
            lvl: "Lv90",
            classification: "",
            cast: "",
            recast: "",
            cost: "",
            distant: "",
            range: "",
            rangeType: "zero",
            content: "对自身附加悖论标记<BR>发动条件：自身的星极火在最大档数或灵极冰和灵极心在最大档数时，切换至相反属性<BR>冰结和火炎在悖论标记状态中会变为悖论",
            change: "新增特性"
        }
    ];

    ngOnInit(): void {
    }

    //获取攻击范围图标
    getRangeImage(rangeType: string) {
        return "../../assets/rangeUI/" + rangeType + ".png";
    }

}
